### ISSUE TITLE
STATSD_HOST resolution should not be one shot

### ISSUE THREAD

**Issue by concaf** [emissary-ingress/emissary#1244]
When statsd is enabled, Ambassador tries to resolve `STATSD_HOST` (statsd-sink by default) just once, and gives up if it's not resolvable at the moment. This means that if `STATSD_HOST` comes up at a later time, stats are not exported. We should fix that with a timeout or exponential backoff.

**Comment by nbkrause** [comment]
So if `STATSD_HOST` is not up at the time Ambassador tries to connect to it, it will default to `statsd-sink.AMBASSADOR_NAMESPACE`?

**Comment by containscafeine** [comment]
@nbkrause yeah, it defaults to `statsd-sink` - https://github.com/datawire/ambassador/blob/54176a90996344f929f59414db956565300557cf/ambassador/ambassador/config/config.py#L89

**Comment by containscafeine** [comment]
@stale dude, chill!

**Comment by containscafeine** [comment]
n o t s t a l e

**Comment by concaf** [comment]
n o t s t a l e

**Comment by cindymullins-dw** [comment]
Closing and the issue seems out of date now.  Please let us know if this is still needed.
