### ISSUE TITLE
Add Helm chart into regression suite

### ISSUE THREAD

**Issue by richarddli** [emissary-ingress/emissary#1361]
We're seeing more users of the Helm chart since we moved it to the official Helm repository. However, we haven't updated our automated tests to test the Helm chart.

I don't think we need to run the full regression suite against a Helm-installed Ambassador, but at a minimum, an install and successful validation of the Helm chart would be good.

**Comment by khussey** [comment]
@kflynn is this already fixed?

**Comment by cindymullins-dw** [comment]
It appears this issue has been addressed.
