### ISSUE TITLE
Support Consul ACL configuration when using the Ambassador ConsulResolver for service discovery/routing

### ISSUE THREAD

**Issue by danielbryantuk** [emissary-ingress/emissary#1485]
**Please describe your use case / problem.**
When using Consul with Ambassador I would like to be able to specify Consul ACLs to configure which Consul services can be accessed via Ambassador

**Describe the solution you'd like**
Ambassador will need to be registered as a Consul service, and also acquire an ACL token in order to access the Consul agent API

**Describe alternatives you've considered**
N/A

**Additional context**
On the roadmap for Consul there is an additional k8s integration that should make the implementation of this feature easier, and I'll update the ticket when I have more details

**Comment by kflynn** [comment]
This will continue to be relevant. Reopening.

**Comment by dan-leanix** [comment]
Any news regarding that topic?

**Comment by thomassampson** [comment]
This is what you are looking for: https://github.com/datawire/ambassador/issues/2079

**Comment by cindymullins-dw** [comment]
Closing as the issue appears out of date now.  Please let us know if still needed.
