### ISSUE TITLE
Scheme field in AuthService gRPC requests is always empty?

### ISSUE THREAD

**Issue by LukeShu** [emissary-ingress/emissary#1581]
**Describe the bug**

When using a gRPC AuthService, (as far as I can tell), the `:scheme` pseudo-header (which is included in the gRPC request as the [scheme](https://github.com/datawire/envoy/blob/ambassador-0.61.0/api/envoy/service/auth/v2/attribute_context.proto#L97-L98) field) is always unset. More concretely, in Go, `request.GetAttributes().GetRequest().GetHttp().GetScheme()` seems to always return an empty string (where `request` is an instance of [CheckRequest](https://github.com/datawire/envoy/blob/ambassador-0.61.0/api/envoy/service/auth/v2/external_auth.proto#L31-L34)).

Unlike the `query` and `fragment` fields, which the code makes no attempt to set and are [documented](https://github.com/datawire/envoy/blob/ambassador-0.61.0/api/envoy/service/auth/v2/attribute_context.proto#L100-L106) as being unset and only existing for historical compatibility, the code [does](https://github.com/datawire/envoy/blob/ambassador-0.61.0/source/extensions/filters/common/ext_authz/check_request_utils.cc#L93-L94) make an attempt to set `scheme`.

The `path` and `host` fields do seem to be set correctly.

**To Reproduce**

Set up `proto: grpc` AuthService, check the `request.GetAttributes().GetRequest().GetHttp().GetScheme()`.

**Expected behavior**

I expected `scheme` to be set to either `http` or `https` (depending on some combination of HTTP/2 headers, `X-Forwarded-Proto`, and whether the connection came in on TLS or plain TCP).

**Versions (please complete the following information):**
 - Ambassador: 0.60.3
 - Kubernetes environment: kubernaut

**Additional context**

As far as I can tell, `scheme` gets set in the router (`source/common/router/router.cc` and `source/common/router/config_impl.cc`).  It is my understanding that the router gets called after the `ext_auth` filter, which explains it not being set yet.

**Comment by LukeShu** [comment]
@gsagula

**Comment by LukeShu** [comment]
Note that `X-Forwarded-Proto` *does* seem to be set correctly. So
 - For AuthServices: A workaround is to use `….GetHeaders()["x-forwarded-proto"]` instead of `….GetScheme()`.
 - For Envoy: A bug-fix may be to go ahead and also `insertScheme()` in the connection manager to match X-Forwarded-Proto in-the-same-place-that/right-after X-Forwarded-Proto gets set (in [`source/common/http/conn_manager_utility.cc`](https://github.com/datawire/envoy/blob/ambassador-0.61.0/source/common/http/conn_manager_utility.cc#L120-L125)).

**Comment by gsagula** [comment]
@LukeShu Nice catch. Are you already working on this issue?

**Comment by kflynn** [comment]
Given that we already have a workaround for this one, I'm going to schedule it after the existing stuff for (at least) pedrera.

**Comment by LukeShu** [comment]
I am not working on it.

**Comment by LukeShu** [comment]
notstale

**Comment by LukeShu** [comment]
notstale

**Comment by LukeShu** [comment]
When/if this is ever fixed in Envoy, we should change a few things in apro.git.

**Comment by cindymullins-dw** [comment]
This issue has been addressed.
