### ISSUE TITLE
Can't set `resolver:` on an AuthService

### ISSUE THREAD

**Issue by LukeShu** [emissary-ingress/emissary#1585]
**Describe the bug**

I can't set `resolver:` on an AuthService.

**To Reproduce**

1. Set `resolver: endpoint` on an AuthService.
2. Observe `ambassador-pro.standalone.2: not a valid AuthService: Additional properties are not allowed ('resolver' was unexpected) Failed validating 'additionalProperties' in schema: {'$schema': 'http://json-schema.org/schema#', 'additionalProperties': False, 'id': 'https://getambassador.io/schemas/mapping.json', 'properties': {'allow_request_body': {'type': 'boolean'}, 'allowed_authorization_headers': {'items': {'type': 'string'}, 'type': 'array'}, 'allowed_request_headers': {'items': {'type': 'string'}, 'type': 'array'}, 'ambassador_id': {'anyOf': [{'type': 'string'}, {'items': {'type': 'string'}, 'type': 'array'}]}, 'apiVersion': {'enum': ['ambassador/v1']}, 'auth_service': {'type': 'string'}, 'include_body': {'additionalProperties': False, 'properties': {'allow_partial': {'type': 'boolean'}, 'max_bytes': {'type': 'integer'}}, 'required': ['max_bytes', 'allow_partial'], 'type': 'object'}, 'kind': {'type': 'string'}, 'name': {'type': 'string'}, 'path_prefix': {'type': 'string'}, 'proto': {'oneOf': [{'enum': ['http']}, {'enum': ['grpc']}]}, 'timeout_ms': {'type': 'integer'}, 'tls': {'type': ['string', 'boolean']}}, 'required': ['apiVersion', 'kind', 'name', 'auth_service'], 'type': 'object'} On instance: {'allow_request_body': False, 'apiVersion': 'ambassador/v1', 'auth_service': 'ambassador-pro:80', 'kind': 'AuthService', 'name': 'authentication', 'proto': 'grpc', 'resolver': 'endpoint'}` in the diag UI.

**Expected behavior**

I expected it to use endpoint routing to talk to the AuthService.

**Versions (please complete the following information):**
 - Ambassador: 0.60.3
 - Kubernetes environment: kubernaut
 - Version: 1.10

**Comment by LukeShu** [comment]
notstale

**Comment by nbkrause** [comment]
@kflynn Bumping this based on our conversation this morning
