### ISSUE TITLE
Add TLS support to ConsulResolver "address" to ensure all traffic between Ambassador and Consul is encrypted

### ISSUE THREAD

**Issue by danielbryantuk** [emissary-ingress/emissary#1597]
**Please describe your use case / problem.**
When configuring a ConsulResolver, I would like to be able to specify an HTTPS endpoint or TLSContext, so that all traffic from Ambassador to the Consul agent/server would be encrypted.

**Describe the solution you'd like**
I would ideally like to specify a TLSContext in the ConsulResolver, and wonder if we should also require the "https" prefix on the address FQDN?
```
---
apiVersion: ambassador/v1
kind: ConsulResolver
name: consul-dc1
address: https://consul-server.default.svc.cluster.local:8500
tlsContext: myconsultlscert
datacenter: dc1
```

**Describe alternatives you've considered**
I'm open to other suggestions, but as I'm assuming that this TLS certificate won't be renewed on a minute/hourly basis (like the certs used with the Consul mesh are) then I think keeping this solution simple would be best

**Additional context**
N/A

**Comment by kflynn** [comment]
Definitely not stale.

**Comment by dan-leanix** [comment]
Any news regarding that topic?

**Comment by chris-makaio** [comment]
+1, any news?

**Comment by rmgpinto** [comment]
any news?

**Comment by jhonsfran1165** [comment]
+1

**Comment by scottweitzner** [comment]
+ 1. Anyone have a workaround for this?

**Comment by fbozic** [comment]
+1

**Comment by FriedCircuits** [comment]
So I sort of have a work around I am using. I have consul connect setup and it generates a secret with a TLS cert. So I setup TLSContext to use that cert to fill in that unencrypted gap. Amazing this problem exists and still hasn't been addressed. Its a huge problem where compliance is critical.

**Comment by dan-leanix** [comment]
Haven't follow the thread anymore. In the end as we were evaluating Ambassador and Consul as service mesh we stopped our evaluation and moved over to Istio to have the full mTLS encryption between all the components.

**Comment by FriedCircuits** [comment]
@dan-leanix Yeah Istio is still our our primary for mTLS. Especially because of transparent proxy. Which Consul just released.

**Comment by cindymullins-dw** [comment]
There's been a lot of improvements to Emissary since this issue was opened.  If still needed and persisting on 2.x or 3.x version please let us know.
