### ISSUE TITLE
[ConsulResolver] For service location, use Node.Address if Service.Address is empy

### ISSUE THREAD

**Issue by danielbryantuk** [emissary-ingress/emissary#1704]
**Describe the bug**
When using the ConsulResolver, if a service is registered with Consul which doesn't have a manually specified location `Address` (via the related `consul.d` service config file) then Ambassador will not be able to route to this service. 

The Consul docs state that any app (Ambassador in this case) consuming the Consul API service endpoint should use the `Node.Address` field location details if the `Service.Address` field is empty. At the moment Ambassador doesn't do this

Example of empty Service.Address field from Consul API call:

```curl  http://127.0.0.1:8500/v1/catalog/service/shopfront

[{"ID":"bdc9c542-5101-dfdf-8dbc-524591e8e2d0","Node":"shopfront-instance-0","Address":"10.128.0.9","Datacenter":"dc1","TaggedAddresses":{"lan":"10.128.0.9","wan":"10.128.0.9"},"NodeMeta":{"consul-network-segment":""},"ServiceKind":"","ServiceID":"shopfront","ServiceName":"shopfront","ServiceTags":["springboot"],"ServiceAddress":"","ServiceWeights":{"Passing":1,"Warning":1},"ServiceMeta":{},"ServicePort":80,"ServiceEnableTagOverride":false,"ServiceProxyDestination":"","ServiceProxy":{},"ServiceConnect":{},"CreateIndex":8409,"ModifyIndex":8409}]
```

**To Reproduce**
Enable ConsulResolver within Ambassador and configure a Mapping to a Consul service that does not have the Address configuration specified.

**Expected behavior**
If Ambassador retrieves an empty `Service.Address` when querying the Consul API for the service location, then Ambassador should use the location details from `Node.Address`.

**Versions (please complete the following information):**
 - Ambassador: 0.73.0 (but presumedly earlier versions, too)
 - Kubernetes environment: GKE
 - Version: 1.13.7-gke.8

**Additional context**
Chatted about this on Datawire Internal Slack 9am EDT 24 July 2019

**Comment by rutu-k** [comment]
Is this issue resolved? I am experiencing the same issue.

**Comment by jrrdev** [comment]
> @danielbryantuk Is this issue resolved? I am experiencing the similar issue.

I think it is not resolved yet (on Master branch at least) but IMHO it shouldn't be too difficult to fix it:
https://github.com/datawire/ambassador/blob/9efcfb2396c9aa8a773b76529c987b702c32c4e9/pkg/consulwatch/servicewatcher.go#L68-L74

**Comment by jrrdev** [comment]
I think this shouldn't be marked as stale.
This issue impact significantly the ConsulResolver

**Comment by danielbryantuk** [comment]
Hey everyone, yeah, unfortunately it's still not fixed. Prioritization of the OSS efforts is often based on the most popular features. If anyone here does want to submit a PR, then that would shortcut the fix :-)

**Comment by jrrdev** [comment]
I believe this is still not fixed but this is quite annoying for anyone using the ConsulResolver.
I will have some holidays soon, I may try to look about a fix for this issue

**Comment by lawliet89** [comment]
Not stale.

**Comment by cindymullins-dw** [comment]
Emissary has gone through a lot of improvements since this was opened, so not sure if this issue is still relevant.
