### ISSUE TITLE
annoying error in the logs about missing rbac access when in singlenamespace mode

### ISSUE THREAD

**Issue by djsly** [emissary-ingress/emissary#1902]
**Describe the bug**
this line gets logged when running in singleNameapce mode

```
2019-10-09 01:57:45 kubewatch [9 TMainThread] 0.82.0 ERROR: couldn't read namespace nluaas-prod? (403)

Reason: Forbidden

HTTP response headers: HTTPHeaderDict({'Audit-Id': 'a1461e9a-3d8c-47db-91f3-87514615d8bc', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 09 Oct 2019 01:57:45 GMT', 'Content-Length': '509'})

HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"nluaas-prod\" is forbidden: User \"system:serviceaccount:nluaas-prod:ambassador-nluaas\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"nluaas-prod\": RBAC: [clusterrole.rbac.authorization.k8s.io \"ambassador-nluaas\" not found, clusterrole.rbac.authorization.k8s.io \"ambassador-nluaas-crds\" not found]","reason":"Forbidden","details":{"name":"nluaas-prod","kind":"namespaces"},"code":403}
```

**To Reproduce**
1. run the helm chart with singleNamespace mode on
2. look at the logs

**Expected behavior**
no error message for something that ambassador has a plan B

**Versions (please complete the following information):**
 - Ambassador: 0.82.0
 - Kubernetes environment AKS
 - Version 4.3.0

**Additional context**
kubewatch does a get namespace query and we don't have that access when using roleBindings with the role
https://github.com/datawire/ambassador/blob/master/ambassador/kubewatch.py#L156-L172

**Comment by michael-leon** [comment]
I have this issue even with singleNamespace mode set to false.

**Comment by djsly** [comment]
Keep open

**Comment by djsly** [comment]
The logic for Kube-watch is broken, this creates extra error in the log which is confusing our users and we keep getting this error reported to us when users are debugging their Ambassador log. 

Can this be prioritize ? I'm sure there is a cleaner way of generating a root_id...

**Comment by djsly** [comment]
PING

**Comment by djsly** [comment]
revive

**Comment by djsly** [comment]
revive

**Comment by djsly** [comment]
Up

**Comment by djsly** [comment]
clearly no one will ever look at this
