### ISSUE TITLE
Enable gzip compression for specific mappings

### ISSUE THREAD

**Issue by vijaykumark** [emissary-ingress/emissary#2233]
**Please describe your use case / problem.**
We are using Ambassador API GW to serve different types of APIs which are consumed by different clients. We would like to enable gzip compression module selectively for specific mappings. If we enable it globally then it might break existing clients and we do not want that to happen.
Is there a way to enable gzip compression module for only single mapping and not to all mappings?

**Describe the solution you'd like**
Enable gzip compression module for only single mapping selectively.

**Describe alternatives you've considered**
Implementing gzip compression upstream which is an ineffective solution.

**Comment by nadilas** [comment]
not stale

**Comment by mrnonz** [comment]
Can we implement this feature?

**Comment by dascenciohz** [comment]
any update?

**Comment by bothra90** [comment]
The ability to configure request decompression would be great to have as well. Envoy already has support for it: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/decompressor_filter.

**Comment by mrnonz** [comment]
Oh.. not planned

**Comment by kflynn** [comment]
Hey @mrnonz, were you interested in doing the implementation by any chance? 🙂
