### ISSUE TITLE
Disable rewriting of ingress paths

### ISSUE THREAD

**Issue by james-emerton** [emissary-ingress/emissary#2280]
**Describe the bug**
When using Ambassador as an Ingress controller, paths are rewritten to removed the matched prefix.

**To Reproduce**
1. Create an Ingress resource that matches a path (eg: /bar)
2. Make a request to `/bar/baz`
3. Notice the backend gets a request for `/baz`

**Expected behavior**
Requests to ingress controllers should passed verbatim.

**Versions (please complete the following information):**
 - Ambassador: 1.1.0
 - Kubernetes: DOKS
 - Version: 1.16.2

**Additional context**
I've just switched from Traefik 1.7 to Ambassador as our Ingress controller. Most things work properly, but (Harbor)[https://goharbor.io] routes requests to different backends depending on the path. Prior to switching to Ambassador this was working but now attempting to login to Harbor fails because `/c/login` is rewritten to `/login` before being passed to `harbor-core`, which responds with a 404.

I believe the standard ingress controller behavior is to pass the request without any rewriting.

**Comment by anyname2** [comment]
I am experiencing the same issue on ambassodor 1.3.1. 
Is there a way to configure rewrites with annotations?

**Comment by cindymullins-dw** [comment]
The suggestion noted above I believe is correct.  Please let us know if any issues are not addressed.
