### ISSUE TITLE
Ambassador multiple namespace scope

### ISSUE THREAD

**Issue by volatilemolotov** [emissary-ingress/emissary#2288]
**Please describe your use case / problem.**
I have tenants that should have access to just some namespaces and other tenants that should have access to other set of namespaces. These namespaces sets should have a ambassador instance that reads that namespaces for config. Team A should not be able to add a mapping with a ID of Team B, Team B ambassador should not read Team A namespaces

**Describe the solution you'd like**
When deploying Ambassador there is a env variable AMBASSADOR_NAMESPACES with a list of namespaces that Ambassador will read config form. It will use that list to fetch mappings and other stuff from the API. Single namespace scope variable would be deprecated as you will need just to give one namespace to achieve the same functionality

**Describe alternatives you've considered**
Having a single namespace scoped ambassador for each namespace is just expensive.

**Comment by volatilemolotov** [comment]
Nope, still need it :D

**Comment by cindymullins-dw** [comment]
It's now possible to configure Emissary / Edge Stack to a [single namespace](https://www.getambassador.io/docs/emissary/latest/topics/running/running#namespaces).  Let us know if there's any issues here still unresolved.
