### ISSUE TITLE
Sort out Netlify token

### ISSUE THREAD

**Issue by LukeShu** [emissary-ingress/emissary#2448]
In https://github.com/datawire/ambassador-docs/pull/168 I wrote:

> In the travis-ci.org webui, I set the environment variable `NETLIFY_AUTH_TOKEN` to a personal access token for my Netlify account. Someone (@richarddli?) who as access to the "Datawire Automation (Robot Account)" Netlify account should replace it with a personal access token for that account.

**Comment by cindymullins-dw** [comment]
This workflow is no longer relevant.
