### ISSUE TITLE
Add option to disable AES rendering API docs

### ISSUE THREAD

**Issue by scoyle391** [emissary-ingress/emissary#2457]
Thanks to Gabor Horvath for suggesting this feature: 

> Is the Rendering API documentation feature mandatory for starting up AES? If not, maybe there should be an option offered to disable it. For our use case, an option to disable it and as a result of that disabling calling home to GitHub would be useful.

**Comment by AndrewBell** [comment]
Ditto for the community version. I don't have OpenAPI endpoints setup for my services and I had to add in logic to remove this from my logs. In a perfect world, this is a really cool feature, but until I get to that point, it's just causing a lot of unnecessary logs and network traffic.

**Comment by kflynn** [comment]
@AndrewBell You're talking about Edge Stack with the community license, correct?

**Comment by AndrewBell** [comment]
I'm using the Community Ambassador API Gateway (Or, I've accidentally configured AES 😆)

**Comment by kflynn** [comment]
For quite some time, it's been possible to set `POLL_EVERY_SECS=0` in the Edge Stack environment to completely disable all things dev portal. Closing this one. 🙂
