### ISSUE TITLE
AWS L4 ELB HTTP -> HTTPS Redirection Loop

### ISSUE THREAD

**Issue by imranismail** [emissary-ingress/emissary#2494]
**Describe the bug**
After upgrading to Ambassador v1.3 and following the steps defined here to setup AWS LB to terminate TLS (nothing changed since 0.86) and send the traffic to Ambassador: https://www.getambassador.io/reference/ambassador-with-aws/

With extra emphasis on this part:

>  Note: Ensure there is no ambassador-certs secret in the Ambassador Edge Stack Namespace. If present, the tls Module will configure the Ambassador Edge Stack to expect HTTPS traffic.

We ended up in a 308 redirect loop on all mapping

**To Reproduce**
1. Setup [Ambassador Gateway 1.3](https://www.getambassador.io/docs/latest/topics/install/install-ambassador-oss/#4-enable-https) (skip step 4: TLS Setup)
2. [Terminate TLS on the LB](https://www.getambassador.io/reference/ambassador-with-aws/)
3. Add TLSContext/TLS Module and setup the `redirect_cleartext_from: 8080`
4. Don't create the cert secret

**Expected behavior**
- Ambassador redirects request to port 8080 to `https`
- Ambassador expects plaintext traffic on port 8443 when no cert secret created

**Versions (please complete the following information):**
 - Ambassador: 1.3
 - Kubernetes environment: AWS EKS
 - Version: 1.14.9

**Comment by phillycheeze** [comment]
Also experiencing the same issue. Please let me know if you found a solution.

**Comment by daveharding** [comment]
We are also experiencing this issue, has anyone found a solution? Ambassador 1.4.2.

**Comment by c58** [comment]
the same problem, Ambassador 1.4.2

**Comment by umarizulkifli** [comment]
need to create a no-https host to successfully get ambassador to listen for cleartext when TLS is being terminated at the LB.
https://github.com/datawire/ambassador/issues/2462

**Comment by scampuza** [comment]
@umarizulkifli That solution worked for me! Thanks so much.  The update process is not clear and this is kind of documented:

HTTP-only
This example is the same with an L4 LB, or without a load balancer at all.

Copy
```
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: minimal-host
spec:
  hostname: host.example.com
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route
```

**Comment by scampuza** [comment]
Ambassador should update the documentation for properly doing the Ambassador to AES migration.

**Comment by PHameete** [comment]
We were also using this to terminate TLS at the AWS ELB and use Ambassador for HTTP -> HTTPS redirect by listening on two ports for plantext.

It seems like this is no longer possible. Can this functionality be restored? I think many users will prefer to use an L4 LB over a L7 LB and not lose HTTP -> HTTPS redirect when upgrading from previous Ambassador versions.

**Comment by georgekaz** [comment]
I've spent a couple of hours working around this today, it's been infuriating. I've been using it with the ELB SSL termination for ages and I couldn't figure out what was going on until I discovered that AES enables TLS by default and has no convenient way to turn it off.

I install this using the helm chart and my resolution has been to change the image repo to docker.io/datawire/ambassador from the default of docker.io/datawire/aes that is in the chart. The forced TLS is gone. Hope this helps someone.

**Comment by cindymullins-dw** [comment]
Edge Stack 2.x and greater uses [Listeners and Host to route secure and insecure traffic](https://www.getambassador.io/docs/edge-stack/latest/howtos/configure-communications#basic-http-and-https).
_TLSContext redirect_cleartext_from and Host insecure.additionalPort
redirect_cleartext_from has been removed from the TLSContext resource; insecure.additionalPort has been removed from the Host CRD. Both of these cases are covered by adding additional Listeners. For further examples, see [Configuring Emissary-ingress Communications_](https://www.getambassador.io/docs/emissary/latest/howtos/configure-communications).
