### ISSUE TITLE
Ambassador is serving the same certificate for different domains

### ISSUE THREAD

**Issue by tsunny** [emissary-ingress/emissary#2567]
**Describe the bug**
Ambassador is not picking up the correct cert for the different hosts in the cluster

When there are two or more Host objects in the cluster with different hostnames, ambassador is serving the same cert all the different services.

**Test Scenario**
There are two services deployed in the cluster `echo1` and `echo2` that would serve traffic for different domains - `echo1.demoapp.com` and `echo2.differentdomain.com` respectively.

**To Reproduce**
1. Deploy ambassador version 1.4.0
2. Execute the below scripts in files echo1.yaml and echo2.yaml to deploy the echo1 and echo2 services and have the mappings and host objects created.

*echo1.yaml*: https://gist.github.com/tsunny/7dd546ffabe48dca5f5007abbcd73d18
*echo2.yaml*: https://gist.github.com/tsunny/b99ec2830b0d93f6029d4521a9a8e1a6

**Expected behavior**
When the `echo1` service is accessed using the hostname `echo1.demoapp.com`, the cert for domain `echo1.demoapp.com` should be presented by ambassador.

When the `echo2` service is accessed using the hostname `echo2.differentdomain.com`, the cert for domain `echo2.differentdomain.com` should be presented by ambassador.

**Actual behavior**
Accessing either service endpoints is presenting the same certificate. See the curl responses below.
***echo1 service curl response***
`curl -kv -H 'Host: echo1.demoapp.com' https://<LB-IP>/echo1`
```
*   Trying 10.31.153.56...
* TCP_NODELAY set
* Connected to REMOVED-HOST port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=US; L=US; O=US; OU=US; CN=echo1.demoapp.com
*  start date: Apr  9 07:00:13 2020 GMT
*  expire date: Apr  9 07:00:13 2021 GMT
*  issuer: C=US; ST=US; L=US; O=US; OU=US; CN=echo1.demoapp.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /echo1 HTTP/1.1
> Host: echo1.demoapp.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/plain
< date: Thu, 09 Apr 2020 07:44:20 GMT
< content-length: 363
< x-envoy-upstream-service-time: 0
< server: envoy
<
Request served by echo1-deployment-5b5b79b8c7-bhbrj

HTTP/1.1 GET /echo1

Host: echo1.demoapp.com
X-Request-Id: 916e26bf-dd12-45b2-a111-e226cddf3a55
X-Envoy-Expected-Rq-Timeout-Ms: 3000
User-Agent: curl/7.54.0
X-Forwarded-Proto: https
X-Envoy-Original-Path: /echo1
Content-Length: 0
Accept: */*
X-Forwarded-For: 100.120.0.0
X-Envoy-External-Address: 100.120.0.0
```

***echo2 service curl response***
`curl -kv -H 'Host: echo2.differentdomain.com' https://<LB-IP>/echo2`
```
*   Trying 10.31.153.56...
* TCP_NODELAY set
* Connected to REMOVED-HOST port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=US; L=US; O=US; OU=US; CN=echo1.demoapp.com
*  start date: Apr  9 07:00:13 2020 GMT
*  expire date: Apr  9 07:00:13 2021 GMT
*  issuer: C=US; ST=US; L=US; O=US; OU=US; CN=echo1.demoapp.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /echo2 HTTP/1.1
> Host: echo2.differentdomain.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/plain
< date: Thu, 09 Apr 2020 07:42:42 GMT
< content-length: 371
< x-envoy-upstream-service-time: 0
< server: envoy
<
Request served by echo2-deployment-8596c44ff7-gfjjd

HTTP/1.1 GET /echo2

Host: echo2.differentdomain.com
X-Envoy-Expected-Rq-Timeout-Ms: 3000
X-Envoy-Original-Path: /echo2
Content-Length: 0
User-Agent: curl/7.54.0
Accept: */*
X-Forwarded-For: 100.118.0.0
X-Forwarded-Proto: https
X-Envoy-External-Address: 100.118.0.0
X-Request-Id: ada75c31-7077-4569-b41c-f60ba7540f39
```
Notice the **CN=echo1.demoapp.com** being returned for domain **echo2.differentdomain.com**

**Versions:**
 - Ambassador: 1.4.0
 - Kubernetes environment: - AWS
 - Version v1.15.9

**Additional context**
I was looking at the tests for the Host object in the source code. Looks like this scenario is supported. However, it does not seem to be working in an actual cluster
https://github.com/datawire/ambassador/blob/master/python/tests/t_hosts.py#L285

**Comment by lixiaofei123** [comment]
same question,do you solved it??

**Comment by cakuros** [comment]
This issue comes from curl's use of the -k flag disabling SNI in addition to ignoring self-signed certificates.  Ambassador relies on SNI to make sure you get the right certificate, so it's looking for the hostname, but since the entire header is encoded, it has no idea where to look and so it sends a default certificate (in this case echo1-cert).

If you use postman instead to send your custom header, you will get the appropriate certificate back in the postman console, since disabling ssl certificate verification in the preferences does not also disable SNI.

Alternatively (and more simply if you don't already have postman), you can use
`openssl s_client -connect IP_ADDRESS:443 -servername my.domainname.com` to force SNI and inspect the certificate.

When I use `openssl s_client -connect REDACTED:443 -servername echo2.differentdomain.com` I get
```
CONNECTED(00000003)
depth=0 C = US, ST = US, L = US, O = US, OU = US, CN = echo2.differentdomain.com
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, ST = US, L = US, O = US, OU = US, CN = echo2.differentdomain.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=US/L=US/O=US/OU=US/CN=echo2.differentdomain.com
   i:/C=US/ST=US/L=US/O=US/OU=US/CN=echo2.differentdomain.com
---
Server certificate
-----BEGIN CERTIFICATE-----
[REDACTED]
-----END CERTIFICATE-----
subject=/C=US/ST=US/L=US/O=US/OU=US/CN=echo2.differentdomain.com
issuer=/C=US/ST=US/L=US/O=US/OU=US/CN=echo2.differentdomain.com
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 1485 bytes and written 315 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-CHACHA20-POLY1305
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-CHACHA20-POLY1305
    Session-ID: [REDACTED]
    Session-ID-ctx: 
    Master-Key: [REDACTED]
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    [REDACTED]
    Start Time: 1587170325
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
---
```

**Comment by cindymullins-dw** [comment]
Closing as this issue has been explained.
