### ISSUE TITLE
./cmd/capabilties_wrapper doesn't compile on macOS

### ISSUE THREAD

**Issue by LukeShu** [emissary-ingress/emissary#2589]
**Describe the bug**

`go build ./cmd/capabilities_wrapper` doesn't work (so neither does `go build ./...`) on macOS, and that's a pain for all of the macOS-using developers we have.

**Comment by ark3** [comment]
Fixed in #2648?

**Comment by cindymullins-dw** [comment]
This issue has been addressed.
