### ISSUE TITLE
Ambassador CrashLoopBackOff while using with Knative

### ISSUE THREAD

**Issue by Sharathmk99** [emissary-ingress/emissary#2617]
**Describe the bug**
I have configured ambassador to use Knative. We have around 150 services in Knative. Suddenly ambassador started to restart 1000 of times and shows CrashLoopBackOff. Some of the Knative is not registered in ambassador as well.
`kubectl get pods -n ambassador`
```
ambassador-8cbdb64dd-68c2g   0/1     Running            986        23d
ambassador-8cbdb64dd-wnktv   0/1     Running            1742       23d
ambassador-8cbdb64dd-xcwvj   0/1     CrashLoopBackOff   2919       23d 
```
Knative service shows Status as False ans reason as RevisionMissing

```
sc7a7b5f1-3919-420d-913a-f533d17e17b7-knative-deployment   http://sc7a7b5f1-xxxx-420d-913a-f533dxxxxx-knative-deployment.xxxxxx.com   sc7a7b5f1-3919-42xxx-xxxx-f533d17e17b7-knative-deployment-65c2v            False   RevisionMissing
```

When i check the logs of ambassdor, there is no error logs.

Ambassador CrashLoopBackOff events,

```
Events:
  Type     Reason     Age                      From                                          Message
  ----     ------     ----                     ----                                          -------
  Warning  Unhealthy  45m (x1122 over 14d)     kubelet, xxx-appnodepool-17318896-vmss000001  Readiness probe failed: Get http://xxxxxx:8877/ambassador/v0/check_ready: dial tcp xxxx:8877: connect: connection refused
  Warning  Unhealthy  36m (x14953 over 14d)    kubelet, xxx-appnodepool-17318896-vmss000001  Liveness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy  5m50s (x16737 over 14d)  kubelet, xxx-appnodepool-17318896-vmss000001  Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  BackOff    60s (x12659 over 9d)     kubelet, xxx-appnodepool-17318896-vmss000001  Back-off restarting failed container
```

**Versions (please complete the following information):**
 - Ambassador: 1.3.1 
 - Kubernetes environment Azure AKS
 - Version 1.15.6

Whole my cluster services will be down. For us its very important to have stable Ambassador, else our application is down. Requesting to please.

**Comment by Sharathmk99** [comment]
Do i need to increase Liveness probe and Readiness probe initial delay time? Because of more than 150 services, default 30seconds is not enough?
Please suggest.

**Comment by Sharathmk99** [comment]
Getting Kubestatus timeout error.
`KubeStatus DONE 127: result se60bf65b-e132-47bd-a956-b6574d9da82b-knative-deployment.recobo-ml-api-deploy-ns: timed out`

Increased Readiness and Liveness probe initialDelay to 10min, but it shows timeout for all knative services. 

We are running only 31 Knative service currently. I tried upgrading ambassador to 1.4.1 also, the error remains the same.

**Comment by Sharathmk99** [comment]
After debugging for couple of hours, we saw below behavior.
Working flow:

1. Ambassador is up and running with Knative env 
2. Create Knative service with zero scaling enabled
3. Ambassador creates mapping for the same
4. I can access knative service using ambssador URL

Error Flow:

1. Same as above
2. Restart ambssador by either upgrading to newer version or delete pods
3. Now you will see Kubestatus timeout error. Because as knative service is scaled to zero, Kubestatus can't validate service
4. It will keep on trying still all services are up.
5. Because of readiness and liveness probe, it will restart
6. When it loops and check for service status, CPU usage will be 2CPU.

As we are using Knative because of scale zero feature and our most of our services are not used so frequently.

How can we solve this issue @concaf @richarddli

**Comment by kflynn** [comment]
I believe that this is actually fixed in current versions of Ambassador -- there's been a lot of work around Knative. Can you try this with Ambassador 1.10? Thanks!
