### ISSUE TITLE
Mapping configured by CRD are not being picked up by default when also configuring from the filesystem

### ISSUE THREAD

**Issue by tmatias** [emissary-ingress/emissary#2645]
**Describe the bug**

https://www.getambassador.io/docs/latest/topics/running/running/#configuration-from-the-filesystem says:

> Note well that while the Ambassador Edge Stack will read its initial configuration from this directory, configuration loaded from Kubernetes annotations will replace this initial configuration. If this is not what you want, you will need to set the environment variable AMBASSADOR_NO_KUBEWATCH so that the Ambassador Edge Stack will not try to update its configuration from Kubernetes resources.

but when I do that, I only see the mapping configured from the filesystem.

**To Reproduce**
1. Deploying ambassador from the [chart](https://github.com/datawire/ambassador-chart/) and pass a valid configuration to `ambassadorConfig`
2. Apply a simple mapping as described in https://www.getambassador.io/docs/latest/topics/using/mappings/#advanced-mapping-configuration
3. Open the diagnostics UI
4. The mappings defined throught the config will be there, but the ones done via CRD will not

**Expected behavior**
I expected both the mapping configured using the config and the CRDs to show up

**Versions (please complete the following information):**
 - Ambassador: 1.4.0
 - Kubernetes environment: N/A

**Additional context**

I see a log line in the ambassador pods that says:

```
AMBASSADOR INFO not watching for Kubernetes config
```
which I believe comes from:

https://github.com/datawire/ambassador/blob/081cb9b1a8743e3155b0ab21f4cbd141f848d2b2/python/entrypoint.sh#L159-L169

So, it seems that the docs are saying the contrary of what happens. Can we update the docs? (not sure if we can change the default or it will be considered a braking change).

**Comment by kflynn** [comment]
We can definitely update those (very out-of-date 🙁) docs -- in fact, if you want to submit a PR there, that'd be awesome! Otherwise we'll tackle it as soon as we can.

**Comment by cindymullins-dw** [comment]
The CRDs are available in our [QuickStart guide](https://www.getambassador.io/docs/emissary/latest/tutorials/getting-started).
