### ISSUE TITLE
Edge Policy Console is inaccessible through port-forward when AES is running on a LoadBalancer

### ISSUE THREAD

**Issue by johnyacuta** [emissary-ingress/emissary#2649]
**Describe the bug**
If the Ambassador Edge Stack service is running on a LoadBalancer, then the Edge Policy Console will be inaccessible through port-forwarding to `https://localhost:8443`.

Here are the two cases:

1. If there is NO LB (LoadBalancer) deployed, then the EPC (Edge Policy Console) will work and you should be able to access/navigate to `https://localhost:8443` through port-forward.
2. If there is a LB deployed, then the EPC will NOT work in `https://localhost:8443`, but it will at `https://<AES_URL>/edge_stack/admin/#`

I believe bullet 2 is unexpected and both ways should be a way to access the EPC. Why is it that I cannot access the EPC when the LB successfully deploys?

**To Reproduce**

1. Deploy initial AES helm chart from https://github.com/datawire/ambassador-chart/
2. Added service annotations which included mapping + TLSContext + Module resources
3. Errors occurred but I was able to access the Edge Policy Console at `https://localhost:8443` for debugging. I used `kubectl port-forward -n ambassador deployment/ambassador-edge-stack 8443:8443` and `edgectl login --namespace=ambassador localhost:8443`
4. Updated my resources to a standard that was acceptable to AES similar to https://github.com/datawire/ambassador/issues/1792
5. When fixed, I am no longer able to access the EPC with the same steps I mentioned above

**Expected behavior**
I'm able to access the EPC at `https://localhost:8443` and `https://<AES_URL>/edge_stack/admin/#`

**Versions (please complete the following information):**
 - Ambassador: 1.4.2
 - Kubernetes environment: AWS EKS
 - Version 1.14.0

**Comment by cindymullins-dw** [comment]
The Edge Policy Console has been deprecated in favor of Ambassador Cloud.
