### ISSUE TITLE
Red Hat Universal Base Image support

### ISSUE THREAD

**Issue by ntolia** [emissary-ingress/emissary#2663]
**Please describe your use case / problem.**

It would be great to get an ambassador image with Red Hat Universal Base Image support. This is required for Red Hat OpenShift certification and I am pretty sure we aren't the only Ambassador users being asked for this.

**Describe the solution you'd like**

Either rebase or have a separate concurrent UBI-based release.

**Describe alternatives you've considered**

Creating our own ambassador images that are UBI based.

**Comment by richarddli** [comment]
We've looked at this, and the challenge is that it doubles our regression test matrix (which is pretty huge as you can imagine with different cloud providers, performance tests, etc.) plus requires different security processes, etc.

Right now I don't expect this to be something we'd get to in the next couple quarters. That said, if you're interested in maintaining a UBI-based distro, we can talk about that.
