### ISSUE TITLE
ambassador替代nginx的重定向，在ambassador里发现把url的后缀都没有重定向

### ISSUE THREAD

**Issue by xuhuajie** [emissary-ingress/emissary#2682]
环境：

nginx的配置如下：

..............................
               rewrite /newprop-web/index.html /newprop-web/share/index.html permanent;
               location ^~ /newprop-web/ {
                        rewrite /newprop-web/(.+?)$ /$1 break;
                        proxy_pass http://newprop.server:8496; #k8s
...............................

然后我这边用ambassador代替：

---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  prop-newprop-web-rewrite-index
spec:
  prefix: "/newprop-web/index.html.*"
  path_redirect: "/newprop-web/share/index.html"
  service: hjd.80166.com
  prefix_regex: true
  host_redirect: true
  host: hjd.80166.com

---

apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  prop-newprop-web
spec:
  prefix: "/newprop-web/"
  service: prop-prop-external:8496
  host: hjd.80166.com

kubectl   create -f   test.yaml

最后浏览器访问：

应该预期的实现是：

https://hjd.80166.com/newprop-web/index.html?sharer=jackqwert&pid=5e985eee-ddf8-4d81-b0f8-87c8a5809366

跳转到：

https://hjd.80166.com/newprop-web/share/index.html?sharer=jackqwert&pid=5e985eee-ddf8-4d81-b0f8-87c8a5809366

其实是最终的效果是：

https://hjd.80166.com/newprop-web/share/index.html  后面的id都没有带上 

求助，是那配置不对？

**Comment by kflynn** [comment]
If translate.google.com is telling me the truth, I think you may be able to use `regex_rewrite` to solve this problem with Ambassador 1.5.4?
