### ISSUE TITLE
TLSContext Annotations do not respect cipher suite list

### ISSUE THREAD

**Issue by BrendanThompson** [emissary-ingress/emissary#2684]
# Description

When using the following definition of a Kubernetes Service using an Ambassador Annotation the Cipher suit is not restricted, and TLSv1.0, TLSv1.1 are offered:

```
resource "kubernetes_service" "app_traffic" {
  metadata {
    annotations = {
      "getambassador.io/config" = <<EOF
---
apiVersion: ambassador/v1
kind: TLSContext
name: app-${var.environment}-app-traffic-context
hosts:
- ${local.dns.traffic}
- ${local.dns.admin}
secret: ambassador-certs
min_tls_version: v1.2
max_tls_version: v1.3
cipher_suites:
- [ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]
- [ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]
- ECDHE-ECDSA-AES128-SHA256
- ECDHE-RSA-AES128-SHA256
- ECDHE-ECDSA-AES256-GCM-SHA384
- ECDHE-RSA-AES256-GCM-SHA384
- ECDHE-ECDSA-AES256-SHA384
- ECDHE-RSA-AES256-SHA384
---
apiVersion: ambassador/v1
kind: Mapping
name: app-${var.environment}-app-traffic-mapping
prefix: /
remove_response_headers:
  - x-envoy-upstream-service-time
service: https://app-traffic.${var.environment}.svc.cluster.local:8441
host: ${local.dns.traffic}
tls: true
EOF
    }

    labels = {
      app = "app"
    }

    name      = "app-traffic"
    namespace = var.environment
  }

  spec {
    port {
      name        = "app-traffic"
      port        = 8441
      protocol    = "TCP"
      target_port = 8441
    }

    selector = {
      app       = "app"
      component = "traffic"
    }
  }

  depends_on = [kubernetes_deployment.app_traffic]
}
```

If however, I remove the `cipher_suites:` it will respect the TLS versions defined.

# Reproduction

1. Create yaml/tf to generate a kubernetes service for anything
2. Apply the above annotations to said service
3. Test with `testssl.sh`

# Expected Behaviour
I would expect that only the cipher suites defined are returned by Ambassador.

**Versions (please complete the following information):**
 - Ambassador: 0.86.1
 - Kubernetes environment: AKS
 - Version: v1.16.7

**Comment by BrendanThompson** [comment]
@kflynn wondering if you've any insight here?

**Comment by BrendanThompson** [comment]
@kflynn don’t suppose you’ve had a chance to look at this yet?

**Comment by BrendanThompson** [comment]
Any updates here???

**Comment by BrendanThompson** [comment]
This still has had zero response from maintainers.

**Comment by BrendanThompson** [comment]
8 months and not a single reply...

**Comment by BrendanThompson** [comment]
10 months no reply.

**Comment by cindymullins-dw** [comment]
Hi @BrendanThompson , thanks for flagging the issue and apologies for the non-response.  TLS1.2 and 1.3 are now available and I think the behavior is improved in the 2.x and 3.x series.

[_The cipher_suites](https://www.getambassador.io/docs/emissary/latest/topics/running/tls#tls-parameters) setting configures the supported ciphers found below using the [configuration parameters for BoringSSL](https://commondatastorage.googleapis.com/chromium-boringssl-docs/ssl.h.html#Cipher-suite-configuration) when negotiating a TLS 1.0-1.2 connection. This setting has no effect when negotiating a TLS 1.3 connection. When a client does not support a matching cipher a handshake error will result._
