### ISSUE TITLE
Ambassador is not able to detect file changes

### ISSUE THREAD

**Issue by KowalczykBartek** [emissary-ingress/emissary#2692]
**Describe the bug**
After updating to Ambassador 1.5.2, Ambassador is not able to detect file changes, because of that, if we have certificate secret mounter as file (for example as istio.default), and that secret will be updated (certificate will be rotated by Istio), ambassador will not hot-restart (causing downtime). I am reporting that as bug - because it worked ( I am 100% sure ) since 0.5 as described here https://github.com/datawire/ambassador/pull/821 

**Expected behavior**
Ambassador detect file changes and restart. 

**Versions (please complete the following information):**
 - Ambassador: 1.5.2

**Comment by KowalczykBartek** [comment]
lorem ipsum

**Comment by cindymullins-dw** [comment]
It appears this issue was resolved with version 1.10.
