### ISSUE TITLE
Ingress mode does not support servicePort: http

### ISSUE THREAD

**Issue by hmklabs-dclow** [emissary-ingress/emissary#2723]
**Describe the bug**
When using Ambassador as an ingress controller, the following error is received when the ingress is configured with `servicePort: http`:

```
cluster_keycloak_http_keycloak_http_keycloak: found invalid port for service keycloak-http.keycloak:http. Please specify a valid port between 0 and 65535 - invalid literal for int() with base 10: 'http'. Service keycloak-http.keycloak:http cluster will be ignored, please re-configure
```

**To Reproduce**
1. Create ingress with `servicePort: http`
2. Add annotation `kubernetes.io/ingress.class: ambassador`
3. See error

**Expected behavior**
Behavior should match k8s spec and behavior when using nginx ingress.

**Versions (please complete the following information):**
 - Ambassador: 1.4.3
 - Kubernetes environment EKS
 - Version 1.16

**Comment by cindymullins-dw** [comment]
This should be fixed in more recent versions.  Please upgrade to 2.x or 3.x and reopen if issues persist.
