### ISSUE TITLE
Reintroduce a way to use redirect via 8080 and cleartext via 8443

### ISSUE THREAD

**Issue by imranismail** [emissary-ingress/emissary#2725]
**Please describe your use case / problem.**
This feature was removed since 1.0 and we've been holding back upgrading to AES because of this.

**Describe the solution you'd like**
Reintroduce a way to redirect to https via 8080 and allow cleartext traffic via 8443

**Describe alternatives you've considered**
Running a sidecar that does the redirection

**Comment by imranismail** [comment]
not stale

**Comment by Heraclitus** [comment]
Looking at the current documentation ( https://www.getambassador.io/docs/latest/topics/running/ambassador-with-aws/#tls-termination-at-the-load-balancer ) on this topic it seems that cleartext redirection only functions through`x-forwarded-proto`

```
Ambassador uses the value of X-Forwarded-Proto to know if the request originated as encrypted or cleartext. Unlike L4 load balancers, L7 load balancers will set this header so HTTP -> HTTPS redirection is possible when terminating TLS at a L7 load balancer.
```
comparted against L4 
```
HTTP -> HTTPS redirection is not possible when terminating TLS at a L4 load balancer.
```

I happen to be one those who utilized the split 8080/8443 redirect capability described here https://github.com/datawire/ambassador/blob/v0.86.1/docs/reference/ambassador-with-aws.md#l4-load-balancer

and now I'm trying to leave those good old days of pre-1.x and it's unclear how to proceed without an outage. Is this something planned for the future? To allow that 8080/8443 distinction for redirect?

**Comment by zahodi** [comment]
not stale.

**Comment by cindymullins-dw** [comment]
With 2.x we believe you can configure [a Listener](https://www.getambassador.io/docs/emissary/latest/topics/running/listener/#the-listener-crd) to do this.  If you could please try that and let us know.

**Comment by cindymullins-dw** [comment]
Feel free to reopen this issue if the Listener config on 2.x or 3.x does not resolve the issue.
