### ISSUE TITLE
Edge Console Showing Mappings for all values of `ambassador_id`

### ISSUE THREAD

**Issue by suever** [emissary-ingress/emissary#2802]
**Describe the bug**
We have multiple AES deployments, each with their own `ambassador_id`. When viewing the Edge Console for each of the deployments, the `Mappings` associated with *all* of the Ambassador deployments are shown rather than just the ones for the Ambassador deployment I am looking at.

**To Reproduce**
1. Create two Ambassador deployments/services with different `ambassador_id` values
2. Create a mapping for each of the Ambassador deployments, specifying the `ambassador_id` in the `spec` 
3. Access the Edge Stack dashboard for either of the Ambassador deployments
4. Notice that both `Mappings` are shown and the `ambassador_id` value is disregarded.

**Expected behavior**
I would expect the `Mappings` shown to be filtered by the `ambassador_id` such that only the ones applied to the Ambassador deployment I am looking at will show up in the UI.

**Versions (please complete the following information):**
 - AES: 1.5.2
 - Kubernetes environment: GKE
 - Version 1.16

Here is an example screenshot showing the YAML with two `ambassador_id` values appearing in the same UI

![84777428-93153680-afaf-11ea-8225-1e666a848249](https://user-images.githubusercontent.com/653357/84788908-acbd7a80-afbd-11ea-8fce-5800e1dae613.png)

**Comment by muscovitebob** [comment]
I also observe this behaviour in the same circumstances. A further surprising twist is that if you set `AMBASSADOR_SINGLE_NAMESPACE` to true on one deployment, that deployment will as you expect not show you the other deployments values in its Policy Console deployment, but the other deployments Policy Console will still have full view and access of the first’s values.

**Comment by kflynn** [comment]
This is unquestionably a bug. We'll get it dealt with.

**Comment by conblem** [comment]
Also just ran into this, would be nice to get it fixed.

**Comment by cindymullins-dw** [comment]
The Edge Policy Console has been replaced by Ambassador Cloud for 2.x and 3.x.  We'd love to know how you find the [Ambassador Cloud UI](https://www.getambassador.io/products/ambassador-cloud/) with regards to viewing your mappings by `ambassasdor_id`.
