### ISSUE TITLE
Edge Policy console does not show on Safari after authenticating with edgectl login

### ISSUE THREAD

**Issue by muscovitebob** [emissary-ingress/emissary#2804]
**Describe the bug**
After installing the Ambassador Edge Stack via the helm chart, I can navigate to my domain and see the page that tells me to do:

```
edgectl login --namespace=namespace domain
```

Running this opens a new window where I see the Edge Policy Console for a split second before I get the same instruction page.

**To Reproduce**

1. Go to the /edge_stack/admin/#dashboard endpoint
2. Run the edgectl command listed
3. Witness a failure to see the Policy Console
4. Try the same sequence on Chrome and be able to successfully go to the Policy Console.

**Expected behavior**
Can access policy console.

**Versions (please complete the following information):**
 - Ambassador helm chart 6.4.0
 - Ambassador 1.5.0
 - GKE Cluster version 1.14.10-gke.36
 - Safari Version 13.1.1 (15609.2.9.1.2)

**Comment by dneves-gxm** [comment]
Not stale. I am experiencing as well.

**Comment by Qasim-Aziz** [comment]
still facing this issue. unable to login dashboard

**Comment by cindymullins-dw** [comment]
The edgectl CLI tool has been deprecated and the Edge Policy Console has been replaced by `[Ambassador Cloud](https://www.getambassador.io/products/ambassador-cloud/)` for 2.x and 3.x.
