### ISSUE TITLE
Filters created with kubectl are ignored.

### ISSUE THREAD

**Issue by rafmonteiro** [emissary-ingress/emissary#2811]
**Describe the bug**
Edge stack admin console is not in sync with Filters created with kubectl.
**To Reproduce**
1. Create a Oauth2 filter yaml file and run kubectl apply -f <your_filter>.yaml
2. edgectl login --namespace=<ambassador-namespace> <host>
3. Navigate to <host>/edge_stack/admin/#filters
4. Filter is missing, 
5. check that the filter exists with kubectl get filter
6. Navigate to the protected domain 
7. See the error `{
message: "could not find not filter: "google.default"",
request_id: "48329042384092384230948",
status_code: 500
}`

**Expected behavior**
Filters created with kubectl are available and working.

**Versions (please complete the following information):**
 - Ambassador: 1.5.3
 - Kubernetes environment [EKS] 1.14, 1.15

**Comment by kflynn** [comment]
Can you attach the YAML for a filter you're trying to create, so that we have it recorded here? (I know you're on Slack as well, which is great. 🙂)

**Comment by fd-automox** [comment]
Is this a known issue? I'm also trying to create filters / policies via `kubectl` and they appear to take no effect (requests never even hit the auth service). Creating in the admin UI work as expected.

**Comment by cindymullins-dw** [comment]
Edge Policy Console has been replaced by [Ambassador Cloud](https://www.getambassador.io/products/ambassador-cloud/).  We encourage users to upgrade to 2.x or 3.x and use the Ambassador Cloud UI instead.
