### ISSUE TITLE
Rework support for l5d-dst-override header to assume namespace

### ISSUE THREAD

**Issue by iNoahNothing** [emissary-ingress/emissary#2867]
In 1.0.0 we moved to assuming the namespace of the `service` in a `Mapping` is the same namespace as the `Mapping`.

With https://github.com/datawire/ambassador/issues/1594 we added support to automatically add the `l5d-dst-override` header to support Linkerd service discovery and mTLS. This header does not include the namespace if it is omitted from the `service` in the `Mapping` which leaders to the request not being sent to the mesh.

**Comment by kflynn** [comment]
Can you give me a concrete configuration to reproduce this?
