### ISSUE TITLE
Ability to configure keepalive for downstream connection

### ISSUE THREAD

**Issue by imranismail** [emissary-ingress/emissary#2922]
**Please describe your use case / problem.**

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout

> Elastic Load Balancing sets the idle timeout value for TCP flows to 350 seconds. You cannot modify this value. Clients or targets can use TCP keepalive packets to reset the idle timeout.

This can be set through the socket_options in listener config.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener.proto
https://github.com/envoyproxy/envoy/issues/10301
https://github.com/envoyproxy/envoy/issues/3634

**Comment by jujugrrr** [comment]
Hi,
It's quite a big one as it prevent the integration with AWS NLB

**Comment by jujugrrr** [comment]
Mean bot, it's still an important issue 😅. We had to implement fixes client side to force closing the connection

**Comment by cindymullins-dw** [comment]
Closing this issue to consolidate on 2847 as it's been confirmed as persisting on 1.14.
