### ISSUE TITLE
Python causes poor performance of ambassador, which consumes high memory and CPU. Is there a plan to use golang instead of Python?

### ISSUE THREAD

**Issue by niaiwomattt** [emissary-ingress/emissary#2927]
Python causes poor performance of ambassador, which consumes high memory and CPU. Is there a plan to use golang instead of Python?

**Comment by cindymullins-dw** [comment]
Hi @niaiwomattt , we do still use Python but mostly Golang now.  If you test on the latest version we'd love to know how memory / CPU usage is for you there.
