### ISSUE TITLE
ambassador-crds.yaml with api apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by dfl-erik** [emissary-ingress/emissary#2929]
**Please describe your use case / problem.**
When trying to upgrade from Ambassador version 1.3.0 to version 1.6.2 we now get the following error:
unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceSubresources

The Azure Kubernetes cluster is running version 1.18.6.

**Describe the solution you'd like**
A version of ambassador-crds.yaml that is based on apiextension.k8s.io/v1 and enables Validation to work with Azure Kubernetes Service cluster version 1.18.6. Or a way to make the crd yaml work with the cluster.

We think that perhaps Azure Kubernetes Services may not have support for Validation under v1Beta1

**Describe alternatives you've considered**
We have tried manually switching to v1 of the api which resulted in the same error message.

**Additional context**
N/A

**Comment by cindymullins-dw** [comment]
@dfl-erik , we believe on more recent versions of Ambassador/Kubernetes this should be resolved.  Please let us know if otherwise.
