### ISSUE TITLE
Specify "VOLUMES" in dockerfile for read only root volumes for docker.io/datawire/aes:1.6.2

### ISSUE THREAD

**Issue by acherla** [emissary-ingress/emissary#2937]
**Describe the bug**
Need to specify VOLUMES ["/ambassador"] for security hardened environments that only have root volumes as read only.  This is specifically for docker.io/datawire/aes:1.6.2 and the ambassador-redis dockerFile's

**To Reproduce**
1. Specify the below configuration in your kube.yaml deployment file
```
    securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
```

2. Get this error: "Terminated due to readOnly volume /ambassador"

**Expected behavior**
Should have VOLUMES ["/ambassador"] specified as a volume within the dockerfile or any other directory used.  

Versions (please complete the following information):
 - Ambassador: 1.6.2
 - Kubernetes environment: 1.16

Additional context

**Comment by cindymullins-dw** [comment]
Hi @acherla , this should be working on more recent versions.  If you upgrade and retest please let us know how it works for you.

**Comment by cindymullins-dw** [comment]
Closing but feel free to reopen if issues persist on Ambassador 2.x or 3.x.
