### ISSUE TITLE
Ambassador drops or corrupts 20% of requests

### ISSUE THREAD

**Issue by borenstein** [emissary-ingress/emissary#2958]
I used the Ambassador Helm chart to deploy Ambassador API Gateway v1.6.2 to a DigitalOcean Kubernetes cluster. (No edge stack; just the gateway.) There are three 8GB/4CPU droplets and I used the default settings for the Helm chart. TLS termination is disabled; all communication is in plaintext.

When I route traffic to a service through Ambassador through a `Mapping` resource, 10-20% of the requests either time out or are corrupted in repeated tests of 1,000 sequential requests to the same URL on a 1Gbps fiber connection. (Expected response is an 87kb JSON file). 

When I set `timeout_ms` to zero, the failing requests pend forever. Corrupted responses are truncated, typically by 50-75%. Results are similar when making 1,000 concurrent requests (i.e., performance doesn't seem to get any worse).

When I port-forward to the same service and perform the same two tests (sequential and concurrent requests to the same URL), every response comes back in 50-75ms, with no dropped requests. 

To eliminate the DigitalOcean load balancer as a cause of the poor performance, I created a DO load balancer that routes directly to the service. I then ran the same tests. No requests were dropped or truncated, and response times were similar to the port-forwarding case.

All three nodes had more than 50% of their RAM available throughout the above experiments. There was no significant server load during the sequential tests, although server load was substantial during concurrent tests.

Based on the above experiments, I can rule out the server health, the internal network, the cloud load balancer, the public internet, and the target service as causes of the poor performance. The only explanation, as far as I can tell, is that the degraded performance is originating with Ambassador.

Why would this be the case?

**Comment by cakuros** [comment]
Can you try this on AES version 1.7.1?  There were some changes in certain behaviors where people were seeing intermittent interruptions by the Authentication sidecar.  I wonder if that's related to what you're seeing.
