### ISSUE TITLE
Contribute via test case link is broken in readme page

### ISSUE THREAD

**Issue by shubhamitc** [emissary-ingress/emissary#2979]
**Describe the bug**
Link is broken results 404. 
Link: https://github.com/datawire/ambassador/tree/master/ambassador/tests

**To Reproduce**
1. Go to '...' https://github.com/datawire/ambassador/tree/master/ambassador/tests and you should find a 404 issue. 

**Expected behavior**
The link should open to the issues tab where users can find the issues with the coverage flag. There should be a flag suggesting coverage required in the issues tag, and the above link should point to that. 
It seems like the datawire team changed the tags and it is referencing a broken link now. 

I would like to contribute to this once the tag is finalized.

**Comment by cindymullins-dw** [comment]
At version 2.x the repos were split into Emissary and Edge Stack repos so I don't think this link is still relevant.
