### ISSUE TITLE
Support sending generated x-request-id in the response

### ISSUE THREAD

**Issue by ngrigoriev** [emissary-ingress/emissary#2981]
**Please describe your use case / problem.**

If tracing is enabled, Ambassador generates x-request-id header, which is used by the upstreams for logging and other tracing-related purposes. Often the clients need this value so they can ask the API provider about the details of a particular request. The clients may use their x-client-request-id or may prefer to rely on the ID generated by the API provider.

Ambassador does not send x-request-id value back to the caller and does not seem to have a way to do it. 

**Describe the solution you'd like**

I'l like Envoy option (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-always-set-request-id-in-response) to be exposed via Ambassador configuration.

**Describe alternatives you've considered**

Currently the only alternative seems to be to have each microservice echoing back the value of the x-request-id header in the response, response headers or trailers (gRPC).

**Additional context**

n/a

**Comment by raffis** [comment]
A late response is better than no response, what I did is using lua declared in the ambassador module as a workaround:
```
     lua_scripts: |
      function envoy_on_request(handle)
        local metadata = handle:streamInfo():dynamicMetadata()
        local headers = handle:headers()
        local rid = headers:get("x-request-id")
        if rid ~= nil then
          metadata:set("envoy.filters.http.lua", "req.x-request-id", rid)
        end
      end
      function envoy_on_response(handle)
        local metadata = handle:streamInfo():dynamicMetadata():get("envoy.filters.http.lua")
        local rid = metadata["req.x-request-id"]
        if rid ~= nil then
          handle:headers():add("x-request-id", rid)
        end
      end
```

**Comment by cindymullins-dw** [comment]
Closing as a workaround solution is avaialable.
