### ISSUE TITLE
Optionally validate uniqueness of hostname & prefix across all mappings

### ISSUE THREAD

**Issue by scottillogical** [emissary-ingress/emissary#3000]
**Please describe your use case / problem.**
I would like to have the ability to prevent breaking things by two different applications with the same hostname & prefix mapping.  

**Describe the solution you'd like**
An optional flag on the mapping (such as unique: true, defaulting to false) that will cause ambassador to refuse to parse a mapping if it duplicates an already existing mapping

**Describe alternatives you've considered**
As a workaround, we could in our own code that creates mappings check to see if a prefix & hostname already exists before creating the mapping.     If this feature is undesirable in ambassador I will pursue this route.  
Update: one of my coworkers @factorypreset  suggested we could work around this by ensuring that all the mappings with the same hostname & prefix are named the same.

**Comment by cindymullins-dw** [comment]
Thanks for this feature request, @scottillogical.  We've implemented [Automated Configuration Analysis](https://www.getambassador.io/docs/cloud/latest/config-analysis/reference/#what-are-the-current-capabilities-of-the-automated-configuration-analysis-integration) as part of Ambassador Cloud and it checks for Mapping conflicts among other things.  We'd love for you to [check it out](url).

**Comment by scottillogical** [comment]
@cindymullins-dw thanks! Currently we are on bitbucket cloud (unfortunately) but this would work for some of our use cases except for when we create the mappings dynamically (like with an operator)
