### ISSUE TITLE
Add support for scope regex in JWT filter

### ISSUE THREAD

**Issue by pepjo** [emissary-ingress/emissary#3014]
**Please describe your use case / problem.**
We have a very granular auth system that allows us to give or take permissions for specific actions. Each service has an auth layer, however, we like the possibility of enabling some auth in the gateway layer, features like token signature validation and expire date. We would also like to use scope validation. Our scopes are structured like `user:read`, `user:update`, `user:create`, etc. In some cases, there might be more than 30 different scopes in the same "group". 

**Describe the solution you'd like**
We would like to define scopes by regex in the JWT filter. Following the example set previously, we could have a regex that is `user:.*` for the `/user` path.

**Describe alternatives you've considered**
Add every single scope in the scopes list. Keep it up to date when applying changes to the service.

**Comment by gigashiro** [comment]
This is a very useful and needed feature!

**Describe the solution you'd like**
Following the `/user` example, we could have an `admin` scope allowed to access this path
