### ISSUE TITLE
Expose rate_limited_as_resource_exhausted in Ambassador configuration

### ISSUE THREAD

**Issue by pwen** [emissary-ingress/emissary#3016]
**Please describe your use case / problem.**

We've configured Ambassador to send rate limit requests to a 3rd party service, and noticed that all 429 HTTP responses code are translated to `UNAVAILABLE`, as per [gRPC mapping document](https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md). This isn't particularly helpful. [Per Google's recommendation](https://cloud.google.com/apis/design/errors#generating_errors), 429 response shall be translated to `RESOURCE_EXHAUSTED`. 

Envoy added the support to explicitly specify whether we want 429 responses to be mapped to `RESOURCE_EXHAUSTED` while `UNAVAILABLE` remains default;[ this is configurable through a flag named `rate_limited_as_resource_exhausted`](https://github.com/envoyproxy/envoy/blob/549164c42cae84b59154ca4c36009e408aa10b52/api/envoy/config/filter/http/rate_limit/v2/rate_limit.proto#L59). 

It doesn't seem like Ambassador supports this configuration.

**Describe the solution you'd like**

We'd like Envoy option `rate_limited_as_resource_exhausted` to be exposed via Ambassador configuration.

**Describe alternatives you've considered**
Not at this moment.

**Additional context**
Reference: 
- https://cloud.google.com/apis/design/errors#generating_errors
- https://github.com/envoyproxy/envoy/pull/4879

**Comment by OmegaVVeapon** [comment]
Hate to necro this thread but... is there still no way to do this?

`UNAVAILABLE` gRPC status codes for rate-limited responses isn't cutting it for us...

**Comment by cindymullins-dw** [comment]
This was addressed in 3.8.2.  Please let us know if issues persist.
