### ISSUE TITLE
Support more modern Ratelimit proto

### ISSUE THREAD

**Issue by CheesyFeet** [emissary-ingress/emissary#3017]
**Please describe your use case / problem.**
We're using the excellent [envoyproxy/ratelimit](https://github.com/envoyproxy/ratelimit) as a RateLimitService backend in Ambassador OSS. Recently they have removed support for the legacy [ratelimit.proto](https://github.com/envoyproxy/ratelimit/blob/0ded92a2af8261d43096eba4132e45b99a3b8b14/proto/ratelimit/ratelimit.proto) and have announced a deprecation timeline for the [v2 proto](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/service/ratelimit/v2/rls.proto) (the [v3 proto](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/service/ratelimit/v3/rls.proto) is the new default).

From what I can tell from the [Ambassador documentation](https://www.getambassador.io/docs/latest/topics/running/services/rate-limit-service/#external-rate-limit-service), only the legacy ratelimit proto is currently supported. I had a look at the Ambassador protos and saw that the v2 proto is imported and tried to upgrade to the lastest envoyproxy/ratelimit but no limits were applied so I assume this isn't yet supported.

**Describe the solution you'd like**
Support for the v2 (and ideally v3) protos to be added for RateLimitService backends. I appreciate this is breaking and would probably sit behind a config var or feature flag. If the v2 proto is actually supported, it would be useful to clear up in the documentation the current state of affairs and how the Ambassador RateLimit proto compares to the envoy proto.

Thanks!

**Comment by lawliet89** [comment]
Bump

**Comment by CheesyFeet** [comment]
It appears support for the newer protos and documentation has been added - see docs here for more info: https://www.getambassador.io/docs/edge-stack/latest/topics/running/services/rate-limit-service/
