### ISSUE TITLE
Allow Ambassador to act as an Egress Controller

### ISSUE THREAD

**Issue by salilgupta1** [emissary-ingress/emissary#3064]
**Please describe your use case / problem.**

I have containers running in a Kubernetes cluster and I would like to limit the external http connections they make out to the internet via a domain whitelist. Since we already use Ambassador as our Ingress controller into our K8s cluster it would be nice to able to leverage it as our Egress Controller, as well.

**Describe the solution you'd like**

I think there are two key components to a solution here. 

The first is the ability to target a set of pods for egress control. Whether that be wrapping those containers behind a Kubernetes Service resource or defining a CRD that targets certain pods based off of labels or annotations, we need a way to identify which pods are under these restrictions. Second, we need a way to define a domain whitelist. A CRD would be ideal here as well. I can envision us defining a CRD that takes in the target and list of domains we'd like to allow outbound traffic to.

**Describe alternatives you've considered**

This is probably the best solution we have right now. Unfortunately, this is not Kubernetes native.
[Domain Whitelisting](https://aws.amazon.com/blogs/security/how-to-set-up-an-outbound-vpc-proxy-with-domain-whitelisting-and-content-filtering/)

**Additional context**

It seems like Envoy supports [Dynamic Forward Proxying](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy) which allows it to act as an http proxy.

**Comment by mcalestino** [comment]
Maybe we should add this to the YAML file.


apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-egress
spec:
  podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  policyTypes:
  - Egress

**Comment by mcalestino** [comment]
Maybe we should add something like this to the YAML file. 

> #`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-egress
spec:
  podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  policyTypes:
  - Egress `
