### ISSUE TITLE
Failed to create watch error on pod startup

### ISSUE THREAD

**Issue by crosbymichael1** [emissary-ingress/emissary#3111]
**Describe the bug**
When my AES pod starts up I see the below 2 errors in the logs. I don't see a performance impact from this but I am curious as to what they mean. I also tried navigating to the mentioned github file and I get a 404 page doesnt exist error. I wanted to see if anyone else has experienced this error before, what does it mean, and how can I resolve it?

time="2020-12-09 21:33:22" level=error msg="Failed to create watch on /home/ambassador/.config/ambassador/: Changes might require a restart: no such file or directory" func=github.com/datawire/apro/cmd/amb-sidecar/runner.triggerOnChange file="github.com/datawire/apro/cmd/amb-sidecar/runner/files.go:54"

time="2020-12-09 21:33:23" level=error msg="0 filters configured" func="github.com/datawire/apro/cmd/amb-sidecar/filters/controller.(*Controller).Watch.func1" file="github.com/datawire/apro/cmd/amb-sidecar/filters/controller/controller.go:150" MAIN=auth_controller

**To Reproduce**

The errors are logged on startup on an AES pod.

**Expected behavior**
Not expecting these errors to occur.

**Versions (please complete the following information):**
    - helm chart  = "datawire/ambassador"
    - chart_version = "6.5.12"
    - EKS v1.18

**Comment by kflynn** [comment]
I believe that both of those are not actually errors -- I'll see if I can shut them up. 🙂

**Comment by crosbymichael1** [comment]
Awesome thats good to know! @kflynn and thanks if your able to do that

**Comment by cindymullins-dw** [comment]
With v2.0.1 logs were quieted down significantly, if not before.  Please reopen if issue persists on 2.x.
