### ISSUE TITLE
ambassador log question

### ISSUE THREAD

**Issue by clguo-tw** [emissary-ingress/emissary#3149]
I use ambassador on gke, when i use ambassador filter, i got log like this , but in gcp log, it's severity is ERROR, i'm not sure if the response code is right ? you can refer this page https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry
```
time="2021-01-13T09:33:10Z" level=info msg="HTTP CLIENT: NET: \"GET\" \"http://example:80/authsvc/token-verification/v1/clients/895d0dab-5fc5-4800-ac63-21635edde6ff/locations\" => HTTP 200 (123.002211ms)" FILTER=authentication-filter.example REQUEST_ID=14163483256788479142 SUB=http-server/handler
```

**Comment by cindymullins-dw** [comment]
There may be an error following this line showing 200 for a successful request but we can't determine that error status from just the line above.  Please reopen this issue if you find it persists on v2.x, including any log lines immediately following this one if possible.
