### ISSUE TITLE
How to use Ambassador to support GRPC protobuf field based ingress load balance

### ISSUE THREAD

**Issue by jackyh** [emissary-ingress/emissary#3175]
**If I have a route.proto like this:**

syntax = "proto3";
package routing;
message CopyImageRequest {
int32 camera_id = 1;
}
message CopyImageResponse {
string result = 1;
}
service RoutingService {
rpc service_A_hello(CopyImageRequest) returns (CopyImageResponse) {};
rpc service_B_hello(CopyImageRequest) returns (CopyImageResponse) {};
rpc service_C_hello(CopyImageRequest) returns (CopyImageResponse) {};
}

**how can I use Ambassador to achieve ingress load balance by "camera_id"?**

**Comment by cindymullins-dw** [comment]
Please let us know and reopen if this issue persists on Ambassador v2.x.  Attaching our [gRPC docs here](https://www.getambassador.io/docs/edge-stack/latest/howtos/grpc/#grpc-connections) for reference.
