### ISSUE TITLE
Headers added in mapping are not passed to auth service

### ISSUE THREAD

**Issue by TRWalters** [emissary-ingress/emissary#3189]
**Describe the bug**
When a header is added to a mapping using add_request_headers and the corresponding value is added to allowed_request_headers in the AuthService entry the new header is not passed to the auth service.

If an external request with the header already present is received then this header is correctly passed to the auth service.

**To Reproduce**
1. Create a mapping and add a new header with add_request_header
2. Configure the auth service to allow the new request header
3. Tigger the mapping

**Expected behavior**
It is expected that a request header added in a mapping should be made available to all upstream calls, rather than just the final target service

**Versions (please complete the following information):**
 - Ambassador: 1.6.0 and 1.11.1
 - Kubernetes environment AKS
 - Version 1.17.9, 1.18.14, 1.19.6

**Additional context**

**Comment by jcwilson** [comment]
Hi, fellow auth-service implementer here!

My interpretation (and expectation) was that the header would only be added after authentication. My use case is pretty simple: use the header to indicate to upstream services that the request came through the ambassador gateway. Conceptually, I treat the auth service as part of the gateway so the header is immaterial there anyway (only the gateway would be calling to the auth service anyway). It sounds like you might have a different use case, though.

Tangentially related, this header is not enough to indicate that the request was verified by the auth service as mappings that specify `bypass_auth` will still receive the header. For that I'd recommend returning a response header from the auth service on success which will be added to the upstream request.

**Comment by TRWalters** [comment]
Hi,

I think our use case is slightly different as we have implemented a single external auth service that allows us to call different IDPs based on the entry point. I am currently controlling this within the auth service, however this obviously requires me to know in advance what paths will be used for each IDP. My expectation was that I can add the header to the inbound traffic and use this within my auth service to control which IDP is called for authentication. Unfortunately, as the header is not passed I cannot dynamically assign new routes to IDPs.

**Comment by asetty** [comment]
I also expected that headers added to a Mapping's `add_request_headers` attribute would be available in the AuthService. I'd be interested to hear what others think here. The header would help enable AuthServices to have dynamic, per Mapping functionality.
I could also imagine adding a new attribute `add_auth_headers` instead if there was reasoning to not forward the header in the first place. 

For my use case, I wish to be able to configure custom authorization headers per Mapping in order to require different group memberships.

**Comment by cindymullins-dw** [comment]
Headers are indeed added after authentication so this would require a significant change to flow that we think is unlikely.  The workaround would be to employ a Lua script.
Example of a functioning Lua script in a Module:
---
apiVersion: getambassador.io/v3alpha1
kind:  Module
metadata:
  name:  ambassador
  namespace: ambassador
spec:
  config:
  # Use the items below for config fields
    lua_scripts: |
      function envoy_on_request(request_handle)
        local authority = request_handle:headers():get(":authority")
        if(string.find(authority, ":") ~= nil)
        then
          local authority_index = string.find(authority, ":")
          local stripped_authority = string.sub(authority, 1, authority_index - 1)
          request_handle:headers():replace(":authority", stripped_authority)
        end
      end

Additional examples on this page:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter
