### ISSUE TITLE
Sudden spikes in requests failures (504) towards K8S API Servers

### ISSUE THREAD

**Issue by lorenzo-biava** [emissary-ingress/emissary#3206]
**Describe the bug**

Every now and then we are observing sudden spikes in requests failures (504) towards K8S API Servers.
Those are LIST requests made by Ambassador to the various getambassador.io Custom Resources.

It's not clear if the behavior is a cause or a consequence of something else going on with the API Servers.

**Need some help to find a good process to drill down this issue (there are other workloads that watch/list CRs in the cluster - e.g. several Operators - but none ends up with this kind of issue).**

**To Reproduce**

Not easy to do; this seems to happen when a K8S API Server replica gets restarted, and then the issue persists for minutes or hours, and can be fixed either by restarting all the Ambassador instances or all the K8S API Server replicas.

**Expected behavior**
The issue should not appear at all or at least Ambassador should be able to stop the surge of requests/failures, perhaps with some exponential back-off retry.

**Versions (please complete the following information):**
 - Ambassador: v1.8.1
 - Kubernetes environment: AKS 
 - Version: v1.18.10

**Additional context**

These logs start appearing in Ambassador:
```
ambassador-asraas-prod-6785c7f54c-fxz45 ambassador E0205 13:50:13.665588     149 reflector.go:178] k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list <unspecified>: Timeout: Too large resource version: 334349183, current: 334349003
ambassador-asraas-prod-6785c7f54c-fxz45 ambassador E0205 13:50:18.750223     149 reflector.go:178] k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list <unspecified>: Timeout: Too large resource version: 334354505, current: 334354350
ambassador-asraas-prod-6785c7f54c-fxz45 ambassador E0205 13:51:19.942671     149 reflector.go:178] k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list <unspecified>: Timeout: Too large resource version: 334363446, current: 334349003
ambassador-asraas-prod-6785c7f54c-fxz45 ambassador E0205 13:51:23.638412     149 reflector.go:178] k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list <unspecified>: Timeout: Too large resource version: 334354350, current: 334349183
```

While the API Servers show:

```
I0205 13:40:58.539481 1 trace.go:116] Trace[2046292194]: "List" url:/apis/getambassador.io/v2/hosts,user-agent:watt/v0.0.0 (linux/amd64) kubernetes/$Format,client:52.246.112.163 (started: 2021-02-05 13:40:55.538773088 +0000 UTC m=+64852.599956418) (total time: 3.000688896s):
I0205 13:40:58.539191 1 trace.go:116] Trace[642698929]: "cacher list" type:*unstructured.Unstructured (started: 2021-02-05 13:40:55.538824889 +0000 UTC m=+64852.600008219) (total time: 3.000342993s):
```

And a sudden spike of 504 is also visible in the metrics.
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/5684713/107052500-06351c80-67ce-11eb-8ea9-afd237f38ca7.png)

Example of failing requests:

![image](https://user-images.githubusercontent.com/5684713/107053194-d8040c80-67ce-11eb-9164-d6b7a4fc2c4c.png)

**Comment by lorenzo-biava** [comment]
Adding some info to this: it seems that Ambassador suddenly starts making an awful lot of requests (see the spike in the screenshots), overloading the API servers, and causing the timeouts that appear as a result.

Anybody can help us out with this problematic behavior?

![3](https://user-images.githubusercontent.com/5684713/122429623-328a5200-cf93-11eb-8d2d-0cc55e574186.png)
![1](https://user-images.githubusercontent.com/5684713/122429942-77ae8400-cf93-11eb-88da-d034feb4516c.png)
![2](https://user-images.githubusercontent.com/5684713/122429575-29998080-cf93-11eb-86bb-cdf9065a9bbc.png)

**Comment by cindymullins-dw** [comment]
We'd suggest implementing a [retry policy with circuit breaker.](https://www.getambassador.io/docs/emissary/latest/topics/using/retries/#automatic-retries). If that doesn't resolve and the issue persists on 2.x please reopen this issue.
