### ISSUE TITLE
Support exposing ratelimit response headers

### ISSUE THREAD

**Issue by kphelps** [emissary-ingress/emissary#3223]
**Please describe your use case / problem.**
Users of our API would like to understand their current standing regarding our imposed ratelimits. 

**Describe the solution you'd like**
I would like to be able to expose headers that describe the current ratelimit. For example, I'd like to be able to answer questions like: how many requests do I have remaining? what is the current limit? when does the limit reset?

**Describe alternatives you've considered**
I've looked into supporting [enable_x_ratelimit_headers](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto#envoy-v3-api-msg-extensions-filters-http-ratelimit-v3-ratelimit) but ambassador seems to rely on the v2 API, so that doesn't seem to be possible today. Additionally [returning headers from the ratelimit service directly](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ratelimit/v3/rate_limit.proto#envoy-v3-api-msg-extensions-filters-http-ratelimit-v3-ratelimit) was added in the v3  RLS api, but that also doesn't look to be supported either. I don't have another way to instrument this logic within ambassador as far as I can tell. If I missed something please let me know!

**Additional context**
N/A

**Comment by cindymullins-dw** [comment]
We made an enhancement -[ can you check if this helps](https://www.getambassador.io/docs/emissary/latest/topics/running/services/rate-limit-service/#external-rate-limit-service) and reopen if the issue persists on v2.x?
