### ISSUE TITLE
Add opencensus tracing driver

### ISSUE THREAD

**Issue by pavolloffay** [emissary-ingress/emissary#3256]
**Please describe your use case / problem.**

I would like to use OpenCensus tracing driver https://www.getambassador.io/docs/latest/topics/running/services/tracing-service/. The Zipkin driver reports incorrect data - all spans are marked as client - per OpenTracing and OpenTelemetry spec these spans should have `span.kind=server`.

This incorrect modeling breaks aggregation capabilities in tracing systems.

**Describe the solution you'd like**

Add opencensus as tracing driver to https://www.getambassador.io/docs/latest/topics/running/services/tracing-service/

**Describe alternatives you've considered**
Build own version with opencensus.

**Additional context**

**Comment by jcchavezs** [comment]
Can't we fix the zipkin driver?

**Comment by asetty** [comment]
+1 @jcchavezs 

If a new driver was added, it should probably be an OpenTelemetry driver

**Comment by cindymullins-dw** [comment]
@jcchavezs we [fixed support for Zipkin API-v1 with Envoy xDS-v3](https://github.com/emissary-ingress/emissary/issues/3771) in v2.3, if you could check whether that's working for you now or if not please open a new issue.  Closing this issue as OpenCensus is deprecated.
