### ISSUE TITLE
Enabling gRPC Web breaks AuthService

### ISSUE THREAD

**Issue by blhagadorn** [emissary-ingress/emissary#3258]
**Describe the bug**
We enabled grpc web, and then the authservice broke

**To Reproduce**
1. In the Ambassador Module we enabled gRPC web with this
```
spec:
  config:
    enable_grpc_web: true
```

2. This then (not immediately) breaks the AuthService and sets the protocol for the AuthService like so:
```
spec:
  auth_service: 127.0.0.1:8500
  proto: grpc
```
This breaks the entire AuthService (nothing load) and anything backed by it doesn't load.

**Expected behavior**
Enabling gRPC web doesn't change the protocol for the AuthService and break AuthService

I have yet to recover logs but will when it happens again.

**Versions (please complete the following information):**
 - Ambassador: 1.8.1
 - Kubernetes environment: 1.18

**Additional context**
This happens randomly, is is expected?

**Comment by cindymullins-dw** [comment]
Do you see this persisting on 2.x?  Further updates won't be made to v1, but we'll leave this open if persisting.

**Comment by blhagadorn** [comment]
Looking back, I think this is the intended functionality, the auth service speaks through gRPC. I'll go ahead and close this out
