### ISSUE TITLE
helm test fails when redirecting http to https

### ISSUE THREAD

**Issue by zaroman** [emissary-ingress/emissary#3292]
Running helm test when using the redirect_cleartext_from config in TLS module to redirect from http to https fails due to the redirect status code.

Output of the ambassador-test-ready pod shows:

`wget: server returned error: HTTP/1.1 307 Temporary Redirect`

It seems like the helm test always uses the http port by default as defined in the ambassador.servicePort template.

**Comment by cindymullins-dw** [comment]
In 2.x this has been removed from the TLSContext and [isn’t used anymore](https://www.getambassador.io/docs/edge-stack/latest/about/changes-2.x#tlscontext-redirect_cleartext_from-and-host-insecureadditionalport). redirect_cleartext_from was removed in favor of adding Listeners
