### ISSUE TITLE
Can't install Ambassador chart

### ISSUE THREAD

**Issue by m0nhawk** [emissary-ingress/emissary#3294]
```
❯ helm install ambassador --namespace ambassador datawire/ambassador
...
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "AuthService" in version "getambassador.io/v2", unable to recognize "": no matches for kind "Mapping" in version "getambassador.io/v2", unable to recognize "": no matches for kind "RateLimitService" in version "getambassador.io/v2"]
```

I'm trying to setup Ambassador on DigitalOcean Kubernetes (using 1.17 there).

**Comment by mlushpenko** [comment]
Same here, installing manually helped, but chart isn't good right now to handle crd installation automatically

**Comment by d-lopes** [comment]
is there maybe a way to get these CRDs matching to the version that we have installed? E. g. if i installed EdgeStack v1.13.* I also need to fitting CRDs for that version (otherwise I might break something with my automated installation via pipeline)

**Comment by cindymullins-dw** [comment]
Confirmed - the CRDs need to be installed first.
