### ISSUE TITLE
AuthService: Custom Resource Definition: additionalProperties cannot be set to false

### ISSUE THREAD

**Issue by anderfsilva** [emissary-ingress/emissary#3296]
I removed an old version of ambassador from my K8s env. Now I am trying to install the latest version of the chart, but it's not working.

`
$ helm install --name ambassador datawire/ambassador
`

Error:
`
Release "ambassador" does not exist. Installing it now.
Error: CustomResourceDefinition.apiextensions.k8s.io "authservices.getambassador.io" is invalid: [spec.version: Required value, spec.validation.openAPIV3Schema.properties[spec].properties[add_auth_headers].additionalProperties: Forbidden: additionalProperties cannot be set to false]
`

**Comment by cindymullins-dw** [comment]
Hi @anderfsilva , this is likely due to CRDs not being updated.  Can you test on the latest version and reopen if the error persists?
