### ISSUE TITLE
terraform apply failing

### ISSUE THREAD

**Issue by katlimruiz** [emissary-ingress/emissary#3298]
Hi

I was trying to install the helm chart `6.5.12` using terraform `helm_release` resource, and it kept failing.

My syntax is:
```
provider "helm" {
  kubernetes {
    load_config_file = false
    host = var.kubapi_host
    username = var.kubapi_username
    password = var.kubapi_password
    client_certificate = base64decode(var.kubapi_client_certificate)
    client_key = base64decode(var.kubapi_client_key)
    cluster_ca_certificate = base64decode(var.kubapi_cluster_ca_certificate)
  }
}

resource "helm_release" "ambassador" {
  name       = "ambassador-api-gateway"
  chart     = "https://getambassador.io/helm/ambassador-6.5.12.tgz"
  # version = 6.5.12 = v1.9.0 2020/11/17
  namespace = "ambassador"
  create_namespace = true
}
```
And it kept failing similar to this issue: https://github.com/hashicorp/terraform-provider-helm/issues/537, yet as it says in it, the real error is not exactly that, so I had to investigate further.

Then I set two envs:
SET HELM_DEBUG=1
SET TF_LOG=DEBUG
And ran again `terraform apply`, then it finally gave me the exact error (sorry I lost the exact log output)

```
cannot find the file C:\Users\____\AppData\Local\Temp\helm\repository\datawire-index.yml
```

The only file that I found was `ambassador-index.yaml`.

I copied and renamed to `datawire-index.yml`, and it finally installed the chart.

I'm not sure why the confusion but it seems is a bug in the chart definition.

Conclusion: I am no longer blocked by this bug, however it is worth fixing since future versions should have this fixed.

**Comment by cindymullins-dw** [comment]
Thanks for reporting this issue.  As the ambassador-index.yaml is no longer in use, we can't address this directly but please reopen if you find a similar issue persists on 2.x
