### ISSUE TITLE
Feature Request - Allow adding a namespace option in initializer

### ISSUE THREAD

**Issue by vikas027** [emissary-ingress/emissary#3312]
**Please describe your use case / problem.**
Some organizations have a mandate to install apps in a particular namespace, it would be great to have an option to specify a namespace in [k8s initializer](https://app.getambassador.io/initializer/)

**Describe the solution you'd like**
May be just ask a user to override the default namespace which is `ambassador`

**Describe alternatives you've considered**
This one liner :) 
```
$ sed -n 's/namespace: ambassador/namespace: new_namespace/' *.yaml
```

**Comment by cindymullins-dw** [comment]
Closing as with version 2.x (and now 3.x) the initializer is deprecated, but the suggestion and support for the Initializer is much appreciated.
