### ISSUE TITLE
Update Envoy to newer versions, or allow custom Envoy Version to be set.

### ISSUE THREAD

**Issue by buehler** [emissary-ingress/emissary#3375]
**Describe the bug**
When using GRPC with mobile applications (namely ionic ios), webkit encounters an internal error due to a bug in webkit and envoy (https://github.com/envoyproxy/envoy/pull/12178). This issue was fixed in envoy 1.16.
I found an issue in this repository where it is stated, that the current version of envoy in ambassador edge stack is 1.15.1.

I'd like to be able to change the underlying version of envoy or I'd encourage you to upgrade the version not only because of this safari bug, but also because various security related things were fixed in envoy.

**Expected behavior**
Either AES needs to update the newer envoy versions to enable people to use gRPC with mobile apps (in browsers), or the envoy version should be configurable (with a working default of course) such that people who want to try out other versions may be able to do so.

**Versions (please complete the following information):**
 - Ambassador: AES 1.13.2
 - Kubernetes environment: GKE

**Comment by buehler** [comment]
This is related to #3278

**Comment by lawliet89** [comment]
Just to chime in on this, I am trying to work around https://github.com/envoyproxy/envoy/issues/6767 which involves using a Lua script that uses a feature only introduced in Envoy 118.0.

**Comment by cindymullins-dw** [comment]
Envoy was upgraded to 1.17.3 with Ambassador v 1.14.0 released August 19, 2021.
Envoy was upgraded to 1.22 with Ambassador v3 released Jun 30, 2022.
