### ISSUE TITLE
Reconfigure the service in mapping does not immediately reflect to envoy 

### ISSUE THREAD

**Issue by masingh-19** [emissary-ingress/emissary#3416]
Starting from Ambassador server 1.12.x, we are facing some delay in reflecting changes in service mapping.   

**To Reproduce**
1. Provision the server. Everything is working fine. All services can be accessible
2. Add or changes service routing in mapping.
3. Try to access the service.
4. Getting the error - Upstream connect error or disconnect/reset before headers. reset reason: local reset
5. It starts working after some delay.

**Expected behavior**
After changes has been deployed, all services should able access without any delay. 

**Versions (please complete the following information):**
 - Ambassador: Starting from 1.12.x 
 - Kubernetes environment : AKS
 - Version : 1.18.14

**Additional context**
For service switch in  B|G deployment, changed the mapping file - switching service endpoint from blue to green. It was working fine till 1.11. But after the upgrading ambassador version, finding some delay to reflect the switch.

**Comment by mlushpenko** [comment]
I think I've noticed the same even when deploying a new version of the application. I was doing it with helm and using --wait option to make sure service is up and healthy before calling it from frontend, but on the first call, I would often get Upstream timeout. Evene tried changing timeout settings to a high value, but still first request would often fail and after refresh it would work. Not sure what to make of it, eventually my workaround was to just making requests in the background until I get 200 response and only then display the page.

**Comment by esmet** [comment]
Can you try 1.13.X and let us know if this still persists?

**Comment by masingh-19** [comment]
Tried with 1.13.1. It is the same issue.

**Comment by mlushpenko** [comment]
I haven't tried, but there is fast reconfigure environment variable, maybe that would help.

**Comment by esmet** [comment]
What are the CPU and memory limits for the Ambassador pod? I'd like to rule out CPU throttling, and I'd also like to rule out Ambassador's self throttling when it notices that memory usage is high compared to the memory limit.

**Comment by cindymullins-dw** [comment]
Has anyone encountered this issue on Emissary-ingress 2.x?  If so please comment to reopen the issue.
