### ISSUE TITLE
allow Plugin filters to see POST body

### ISSUE THREAD

**Issue by pguedes** [emissary-ingress/emissary#3419]
**Please describe your use case / problem.**
I have inherited some legacy routing service that I am trying to migrate into a Plugin Filter inside ambassador. 
It uses POST body (JSON payload) to decide where to route some legacy system's traffic
In order to get rid of it and just use ambassador my plugin needs to be able to read the POST body which seems to be a missing feature (or not well documented at least)

**Describe the solution you'd like**
Something like the `include_body` configuration that exists for External plugins
```
    include_body:
      max_bytes: 4096
      allow_partial: true
```

**Comment by cindymullins-dw** [comment]
The challenge with plugin filters is they need to be recompiled with every release so we tend to not recommend them.  That said, if this request comes up again we would welcome community contributions.
