### ISSUE TITLE
Question: How to switch from Ambassador to Emissary Helm repo ?

### ISSUE THREAD

**Issue by Nosmoht** [emissary-ingress/emissary#3543]
Hi All,

i'm using the Ambassador API gateway installed by Helm and the Helm chart repository as documented [here](https://www.getambassador.io/docs/edge-stack/latest/topics/install/install-ambassador-oss/#helm). As written [here](https://github.com/datawire/ambassador-chart) the Helm repo has moved to [here](https://github.com/emissary-ingress/emissary/tree/master/charts/emissary-ingress). 

My questions:
How can i safely, without downtime, switch the Helm repository from `https://www.getambassador.io` to `https://s3.amazonaws.com/datawire-static-files/emissary-charts` ?

The reason why i'm asking:
Looking at both install instructions it seems like i would install a second API Gateway which i guess wouldn't work.

Install from Ambassador API Gateway docs:
```shell
$ helm repo add datawire https://www.getambassador.io
$ helm repo update
$ helm install ambassador datawire/ambassador -f values.yaml
```

Install from emissary ingress docs:
```shell
$ helm repo add emissary-ingress https://s3.amazonaws.com/datawire-static-files/emissary-charts
$ helm repo update
$ helm install emissary-ingress emissary-ingress/emissary-ingress -n ambassador
```  

Note: I'm using only the API Gateway without Ambassador Edge stack.

Maybe i'm totally wrong and there is no need to switch the repo at all or i'm missing something.

Thanks

**Comment by EvertonSA** [comment]
for me, deploy using pure yaml files seems the best approach to dealing with emissary/ambassador migration version

**Comment by cindymullins-dw** [comment]
Thanks for this question.  We've since updated the [migration path and matrix](https://www.getambassador.io/docs/emissary/latest/topics/install/migration-matrix/) with an agent that translates the CRDs and allows for side-by-side install, eliminating the need for downtime as you can test the 2.x install before switching over.  It is recommended to update to v1.14 before beginning migration to 2.x.
