### ISSUE TITLE
Docker image datawire/ambassador:1.13.8 contains incorrect Ambassador version

### ISSUE THREAD

**Issue by van-vliet** [emissary-ingress/emissary#3557]
**Describe the bug**
I upgraded to emissary (ambassador API gateway) 1.13.8. On the diagnostics page, the running version shows a dev version number.
![image](https://user-images.githubusercontent.com/11989400/122567725-455f5e00-d049-11eb-8cff-2a8e2853714d.png)
Furthermore, the diagnostics page informs me that I can upgrade to Ambassador 1.13.8.
![image](https://user-images.githubusercontent.com/11989400/122567822-62942c80-d049-11eb-8be1-4dd3834d2412.png)

**To Reproduce**
1. Install Ambassador in any way that uses the docker image datawire/ambassador:1.13.8 and has the diagnostics page enabled.
2. Open the diagnostics page: /ambassador/v0/diag/ 
3. At the top of the page, note that the Ambassador version is "Ambassador version 1.13.8-dev.19+g1e27abd9f"
4. A bit futher down on the page, note the message "INFO: Upgrade available! to Ambassador version 1.13.8".

**Expected behavior**
I expected the version shown to match the docker image tag used: 1.13.18. 
I expect that there is no "upgrade available" message, since I have installed the latest version.

**Versions (please complete the following information):**
 - Ambassador: datawire/ambassador:1.13.8
 - Kubernetes environment: EKS
 - Version: 1.19

**Comment by cindymullins-dw** [comment]
Thanks for raising this error but as this is now an older version the issue will be closed.
