### ISSUE TITLE
Implementing strict HTTP/2 at the ambassador level

### ISSUE THREAD

**Issue by vivek-narang** [emissary-ingress/emissary#3575]
**Describe the bug**
We need to configure strict HTTP/2 at the ambassador level  and none of the HTTP protocol with http/1.0 and http/1.1 should pass the system but when set the below yaml it still take http/1. request 

---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
 name: xxxxxxxxxxxx
spec:
 hosts:
 - xxxxxxxxxxxxxxxxxx
 secret: xxxxxxxxxxxxxxxxxxxxxxxxx
 alpn_protocols: h2

**Comment by cindymullins-dw** [comment]
The` alpn_protocols: h2` should restrict traffic to h2 traffic.  I wonder if its an issue with the formatting here.  Attaching an example below.
apiVersion: getambassador.io/v3alpha1
kind:  TLSContext
metadata:
  name:  tls
spec:
  secret: ambassador-certs
  hosts: ["*"]
  alpn_protocols: h2
