### ISSUE TITLE
Feature Request: Enabling CSP header in Dev-Portal demo Mapping

### ISSUE THREAD

**Issue by thangarajbluescape** [emissary-ingress/emissary#3576]
**Please describe your use case / problem.**
Development Portal comes with some default mapping where we need to add_response_header to the spec of helm-chart: https://github.com/datawire/ambassador-chart/blob/f298ad5b3eba83ca0acebcc1c900e1628fa53205/templates/aes-internal.yaml#L64-L89
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "ambassador.fullname" . }}-devportal-demo
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    app.kubernetes.io/component: {{ include "ambassador.name" . }}-devportal-demo
    product: aes
spec:
  {{- if .Values.env }}
  {{- if hasKey .Values.env "AMBASSADOR_ID" }}
  ambassador_id: {{ .Values.env.AMBASSADOR_ID | quote }}
  {{- end }}
  {{- end }}
  prefix: /docs/
  rewrite: "/docs/"
  service: "127.0.0.1:8500"

**Describe the solution you'd like**
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "ambassador.fullname" . }}-devportal-demo
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    app.kubernetes.io/component: {{ include "ambassador.name" . }}-devportal-demo
    product: aes
spec:
  {{- if .Values.env }}
  {{- if hasKey .Values.env "AMBASSADOR_ID" }}
  ambassador_id: {{ .Values.env.AMBASSADOR_ID | quote }}
  {{- end }}
  {{- end }}
  prefix: /docs/
  **add_response_headers:
    Content-Security-Policy: default-src 'self';**
  rewrite: "/docs/"
  service: "127.0.0.1:8500"

**Additional context**
https://www.getambassador.io/docs/edge-stack/latest/topics/using/headers/add_response_headers/#add-response-headers
https://content-security-policy.com/#:~:text=The%20Content%2DSecurity%2DPolicy%20header,is%20often%20abbreviated%20as%20CSP%20

**Comment by cindymullins-dw** [comment]
Thanks for this suggestion.  On review, we feel the response header is not a standard or required configuration for the majority of use cases, so is preferable to configure via Mappings rather than set as a Helm value.
