### ISSUE TITLE
Users want first-class gRPC mappings in Ambassador

### ISSUE THREAD

**Issue by kflynn** [emissary-ingress/emissary#358]
Right now, to fully support gRPC you have to manually translate from gRPC service & method names to Ambassador `prefix` and `rewrite` rules, and then you need a separate mapping to support gRPC reflection. That's a little difficult to maintain: we should just allow e.g.

```
kind: Mapping
grpc: helloWorld.Greeter
reflection: true
```

or the like.

**Comment by cbenien** [comment]
I agree. Also if you want to expose multiple GRPC services behind a single Ambassador instance, you can't just set prefix/rewrite rules for the reflection endpoint, because that would only know about one service and not the others.

So +1 for native GRPC server reflection support in Ambassador.

**Comment by jekirl** [comment]
This would be a great feature. We have many endpoints exposed over grpc so this has been a big pain point for us.

**Comment by triplewy** [comment]
Currently right now it seems that ambassador can handle only 1 grpc mapping. Is this a problem with my configuration or a limitation of the OSS version of ambassador?

**Comment by cindymullins-dw** [comment]
Closing as this is now [available](https://www.getambassador.io/docs/edge-stack/latest/howtos/grpc#grpc-connections
).

**Comment by antoniogomezalvarado** [comment]
@cindymullins-dw that link doesn't provide information about GRPC reflection with ambassador do you mind giving an example here for future references?

**Comment by thameezb** [comment]
> @cindymullins-dw that link doesn't provide information about GRPC reflection with ambassador do you mind giving an example here for future references?

++ how is reflection handled?

**Comment by yalattas** [comment]
++ how is reflection handled?
