### ISSUE TITLE
DNS-1123 subdomain error with acmeclient-AES-default value - but unknown origin

### ISSUE THREAD

**Issue by guongle-ssense** [emissary-ingress/emissary#3599]
**Describe the bug**

Receiving the following error:

```
E0712 21:46:29.836400      34 leaderelection.go:324] error initially creating leader election record: Endpoints "acmeclient-AES-default" is invalid: metadata.name: Invalid value: "acmeclient-AES-default": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**To Reproduce**
1. Deploy `datawire/aes:1.12.2` inside k8s
2. Click on a running pod
3. Wait a few moments: See error

**Expected behavior**
No errors

**Versions (please complete the following information):**
 - Ambassador: 1.12.2
 - Kubernetes environment: aws ec2 
 - Version 1.13.10

**Additional context**
- Sometimes it is `kale-AES-default` instead of Acme.
- ambassador_id is set to default

**Comment by cindymullins-dw** [comment]
We think the reason for this error is the use of capital letter characters which doesn't seem to be allowed.  If you test and find the error persists, please comment to reopen the issue.
