### ISSUE TITLE
kates watcher doesn't correctly silence klog, resulting in very noisy logs in the agent and ambassador

### ISSUE THREAD

**Issue by acookin** [emissary-ingress/emissary#3603]
Since upgrading certain k8s golang packages, the way that we silence the klog logger no longer works, so the logs are now super noisy, even when logging at an info level. Specifically in the agent, you'll now see many log lines like:
```
E0712 16:12:54.073707       1 reflector.go:138] pkg/kates/client.go:436: Failed to watch *unstructured.Unstructured: can't watch secrets.: forbidden
```
that didn't appear in previous versions.

I think we might be able to take advantage of klog.SetLogger now that we're at newer versions of these packages.

**Comment by bartsqueezy** [comment]
@acookin I noticed this exact issue during a fresh install of `v6.7.13` of the Helm chart. So is this not an issue in the chart? I figured the `agent-confg` Role was missing read access to `secrets`?
