### ISSUE TITLE
Chart repo is returning 403

### ISSUE THREAD

**Issue by kyschouv** [emissary-ingress/emissary#3687]
**Describe the bug**
Today when I tried to use the emissary-ingress helm chart, I received a 403 from the repo at `https://s3.amazonaws.com/datawire-static-files/emissary-charts`. It was working fine yesterday.

**Comment by kflynn** [comment]
@kyschouv and I talked on [Slack](https://a8r.io/slack) and figured out that https://github.com/emissary-ingress/emissary/tree/master/charts/emissary-ingress/README.md is wrong: it should say 

```
helm repo add emissary-ingress https://s3.amazonaws.com/datawire-static-files/emissary-ingress
```

(note that the URL ends in `-ingress`, not `-charts`). I'll leave this open until we get the `README` updated. Thanks for the catch!!

**Comment by acookin** [comment]
fixed, thanks for reporting @kyschouv
