### ISSUE TITLE
Resolve dependabot security vulnerabilities

### ISSUE THREAD

**Issue by efunk** [emissary-ingress/emissary#3708]
Dependabot identified some security vulnerabilities that we need to resolve. None of the critical/high ones identified are applicable to our code base, but, we should resolve these to remove any false positives and keep our code clean.

The recently identified issues are here: https://github.com/emissary-ingress/emissary/security/dependabot

**Comment by khussey** [comment]
This has been addressed in Emissary-ingress 2.2, which is now available.
