### ISSUE TITLE
SDK For Emissary

### ISSUE THREAD

**Issue by liyongxian** [emissary-ingress/emissary#3760]
**Please describe your use case / problem.**
A clear and concise description of your use case / problem. The "why" is really valuable to us. For example, "I have a set of services whose clients have long-lived connections."
Want to manage configurate of emissary by API.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by cindymullins-dw** [comment]
Closing as lacking sufficient information.
