### ISSUE TITLE
Ambassador tracing issue with zipkin

### ISSUE THREAD

**Issue by fourtimes** [emissary-ingress/emissary#3771]
we try to implement tracing with zipkin on Ambassador

it's returns only empty pages

![image](https://user-images.githubusercontent.com/57703276/132401422-9d7b032f-ad3d-44f8-b7fa-c85ccb98aac1.png)

Reference => https://www.getambassador.io/docs/edge-stack/latest/topics/running/services/tracing-service/

**Comment by cindymullins-dw** [comment]
Another user found these links helpful and noted the TracingService configuration should be on root, not in spec node. https://blog.getambassador.io/distributed-tracing-with-java-microdonuts-kubernetes-and-the-ambassador-api-gateway-ace15b62a89e
https://itnext.io/extending-the-ambassador-java-distributed-tracing-with-lightstep-40b7fc574c7
