### ISSUE TITLE
access deny/allow certain mapping paths

### ISSUE THREAD

**Issue by thinzaung** [emissary-ingress/emissary#3794]
We have an ambassador controller which have different mappings to different services. We would like to prevent users from directly accessing certain mappings and if there is a way we can do it in Ambassador? I tried to dug up in the  documentation and couldn't find a way. 

Something like in apache httpd configuration - 
<Location /foo>
Order Deny,Allow
Deny from all
Allow from webserver1
Allow from webserver2
</Location>

**Comment by cindymullins-dw** [comment]
You can use [ip_allow or ip_deny](https://www.getambassador.io/docs/emissary/latest/topics/running/ambassador#ip-allow-and-deny) (only one option may be applied).  This spec is on the global Module so would apply to all your mappings.
