### ISSUE TITLE
Emissary should verify that TLS secrets contain valid PEM

### ISSUE THREAD

**Issue by kflynn** [emissary-ingress/emissary#3821]
If you point a `TLSContext` at a secret containing bogus junk, Emissary will happily try to use it, but Envoy validation will fail. There's no real point in allowing Emissary to pass such a broken secret to Envoy -- we can, and should, validate it syntactically before attempting to use it at all.

**Comment by khussey** [comment]
This has been addressed in Emissary-ingress 2.2, which is now available.
