### ISSUE TITLE
Emissary should properly report its version number

### ISSUE THREAD

**Issue by kflynn** [emissary-ingress/emissary#3854]
In the diagnostic console, Emissary shows its running version – but recently it's been reporting an internal build tag, rather than e.g. "2.0.1-ea". While the version displayed is _correct_ in that it will indeed let us recover the exact sources used to build that running version of Emissary, it's confusing and it doesn't need to be.

Emissary should instead consistently report its version number in the form that matches the GitHub release for that version.

**Comment by khussey** [comment]
This has been fixed in the Emissary-ingress 2.0.4 GA release, which is now available.
