### ISSUE TITLE
About emissary-ingress installation

### ISSUE THREAD

**Issue by xuhuajie** [emissary-ingress/emissary#3899]
Environmental information：

1. eks-1.18

2. Ambassador-1.9.5 has been running on our production environment；

Now we plan to upgrade or deploy emissary-ingress

We refer to the document:： https://www.getambassador.io/docs/emissary/2.0/topics/install/yaml-install/

The result output is wrong, see attachment

Our question:

1. Can ambassador-1.9.5 and emissary-ingress run in an EKS cluster at the same time?

2. We can't find a suitable upgrade or upgrade plan？

[upgrade1.x-2.0.4.log.docx](https://github.com/emissary-ingress/emissary/files/7430766/upgrade1.x-2.0.4.log.docx)

Hope to get your help！

**Comment by kflynn** [comment]
Hey, we've just updated the migration documentation at https://www.getambassador.io/docs/emissary/2.0/topics/install/migrate-to-version-2/ -- hopefully that'll help.

At this moment, it should be straightforward to run Ambassador 1.9.5 and Emissary-ingress 1.14.2 in the same cluster. Emissary 2.0 is a different story – we're working on that.

**Comment by xuhuajie** [comment]
We want to achieve request compression

That can be supported in that version？

**Comment by kflynn** [comment]
@xuhuajie We're working on a much smoother migration path for Emissary 2.1.0, if that's something you might be interested in helping us test?

**Comment by xuhuajie** [comment]
Hope it will be resolved in version 2.1.0
Achieve smooth migration

We can help test

**Comment by cindymullins-dw** [comment]
[Upgrade path has been improved](https://www.getambassador.io/docs/emissary/latest/release-notes/) on 2.x to allow v3alpha1 resources to run alongside a 1.14.x install using v2 resources.  Version 2.2.2 is recommended.  Please see [migration matrix here](https://www.getambassador.io/docs/emissary/latest/topics/install/migration-matrix/).
