### ISSUE TITLE
SSH SNI Based Routing with Emissary

### ISSUE THREAD

**Issue by MarkSpencerTan** [emissary-ingress/emissary#3920]
Hello!

Not sure if it's a bug, or a configuration I'm missing, or not possible at all with Emissary, but here's my use case below. I would definitely appreciate any help or advice on this:

We want to be able to route ssh traffic from our users to the appropriate pod's ssh service using Emissary Ingress. Right now we have multiple ELBs in AWS for each ssh service in our EKS cluster but that is currently draining a lot of costs so we wanted to optimize it and see if we can use a single LB for the whole cluster and have the traffic be routed internally using an ingress controller. For our use case, we also wanted our users to just be able to ssh just using the **same port**, so all routing will be done dependent on the hostname they provided. 

**Expected behavior**
something like this:
`ssh user@mark.ssh.mydomain.com` -> route to k8s service called mark-ssh.namespace
`ssh user@joe.ssh.mydomain.com` -> route to k8s service called joe-ssh.namespace

I wasn't sure if this was possible, but I noticed in the TCPMapping documentation there was a section about TCP SNI based routing using the hostname/domain name and so I followed the steps in order to set that up:

**To Reproduce**
1. Setup Cert-Manager to be able to verify domain with Route53 and create secret certs needed for Emissary
2. Load Balancer configuration side on AWS regarding Proxy Protocol was done. 
3. Created `Listener`, `Host`, `TLSContext`, `TCPMapping` resources to route the ssh traffic to the appropriate service
4. Created a module for proxy protocol (wasn't sure if this was needed):
```yaml
apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  name: ambassador
  namespace: emissary
spec:
  config:
    use_proxy_proto: true
```
4. ssh to myuser@{service-name}.mydomain.com

**Results after**
```bash
# ssh user@mark.ssh.mydomain.com
Bad packet length 1231976033.
ssh_dispatch_run_fatal: Connection to 10.1.6.9 port 22: message authentication code incorrect
```

**Versions (please complete the following information):**
 - Emissary Ingress: Emissary Ingress Chart 7.1.9, 2.0.4 (App Version)
 - Kubernetes environment 1.21.0
 
**Additional context**
Logs of Emissary Pods:
```
2021-11-05 18:29:50 diagd 2.0.4 [P18TMainThread] INFO: WILL NOT update Mapping status
2021-11-05 18:29:50 diagd 2.0.4 [P18TMainThread] INFO: thread count 9, listening on 127.0.0.1:8004
2021-11-05 18:29:50 diagd 2.0.4 [P18TMainThread] INFO: Ambassador 2.0.4 booted
[2021-11-05 18:29:50 +0000] [18] [INFO] Starting gunicorn 20.0.4
[2021-11-05 18:29:50 +0000] [18] [INFO] Listening at: http://127.0.0.1:8004 (18)
[2021-11-05 18:29:50 +0000] [18] [INFO] Using worker: threads
[2021-11-05 18:29:50 +0000] [23] [INFO] Booting worker with pid: 23
2021-11-05 18:29:50 diagd 2.0.4 [P23TAEW] INFO: starting Scout checker and timer logger
2021-11-05 18:29:50 diagd 2.0.4 [P23TAEW] INFO: starting event watcher
2021-11-05 18:29:51 diagd 2.0.4 [P23TAEW] INFO: EnvoyConfig: Generating V3
2021-11-05 18:29:51 diagd 2.0.4 [P23TAEW] INFO: V3Listener: ==== GENERATED <V3Listener HTTP listener-8080 on 0.0.0.0:8080 [XFP]>
2021-11-05 18:29:51 diagd 2.0.4 [P23TAEW] INFO: V3Listener: ==== GENERATED <V3Listener TCP mark-listener on 0.0.0.0:8022 [XFP]>
time="2021-11-05 18:29:51.0775" level=info msg="started command [\"envoy\" \"-c\" \"/ambassador/bootstrap-ads.json\" \"--base-id\" \"0\" \"--drain-time-s\" \"600\" \"-l\" \"e
time="2021-11-05 18:29:51.0778" level=info msg="not logging input read from file \"/dev/stdin\"" func="github.com/datawire/dlib/dexec.(*Cmd).Start" file="/go/vendor/github.co
time="2021-11-05 18:29:51.0780" level=info msg="not logging output written to file \"/dev/stdout\"" func="github.com/datawire/dlib/dexec.(*Cmd).Start" file="/go/vendor/github
time="2021-11-05 18:29:51.0781" level=info msg="not logging output written to file \"/dev/stderr\"" func="github.com/datawire/dlib/dexec.(*Cmd).Start" file="/go/vendor/github
2021-11-05 18:29:51 diagd 2.0.4 [P23TAEW] INFO: configuration updated (incremental) from snapshot snapshot (S30 L2 G5 C3)
time="2021-11-05 18:29:51.0841" level=info msg="Loaded file /ambassador/envoy/envoy.json" func=github.com/datawire/ambassador/v2/cmd/ambex.Decode file="/go/cmd/ambex/main.go:
time="2021-11-05 18:29:51.0872" level=info msg="Saved snapshot v1" func=github.com/datawire/ambassador/v2/cmd/ambex.csDump file="/go/cmd/ambex/main.go:369" CMD=entrypoint PID
time="2021-11-05 18:29:51.0876" level=info msg="Pushing snapshot v1" func=github.com/datawire/ambassador/v2/cmd/ambex.updaterWithTicker file="/go/cmd/ambex/ratelimit.go:159"
time="2021-11-05 18:29:58.3041" level=info msg="Memory Usage 0.17Gi (28%)\n    PID 1, 0.17Gi: busyambassador entrypoint \n    PID 18, 0.04Gi: /usr/bin/python /usr/bin/diagd /
ACCESS [2021-11-05T18:30:22.929Z] "- - HTTP/1.1" 400 DPE 0 11 0 - "-" "-" "-" "-" "-"
```
Resources for TcpMapping:

```yaml
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: mark.ssh.mydomain.com
spec:
  hostname: mark.ssh.mydomain.com
  tlsSecret:
    name: ambassador-certs
---
apiVersion: getambassador.io/v3alpha1
kind:  TLSContext
metadata:
  name:  mark-tlscontext
spec:
  hosts:
  - mark.ssh.mydomain.com
  secret: ambassador-certs
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: mark-listener
spec:
  port: 8022
  protocol: TCP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name:  mark-tcpmapping
spec:
  port: 8022
  service: mark-ssh-svc.mark:22
```

**Comment by MarkSpencerTan** [comment]
Just to add as a note, I've setup Emissary & AWS NLB prior to the TCPMapping test with just the regular HTTP Mapping initially to test if my setup was correct and that part was working with the sample 'quote of the day' service in the docs. It was just the TCPMapping portion that was giving me a hard time... I'm not sure if there are any logs within the emissary pod that can give me more visibility on what's going wrong or if this whole TCPMapping with SNI routing doesn't work with ssh traffic at all?

Thanks,

Mark

**Comment by chris-echoz** [comment]
SSH does not use TLS and as such doesn't have SNI, nor does it otherwise transmit the host name. One way to achieve this would be to tunnel SSH over TLS, but this would require additional configuration on the clients as well.

**Comment by bemipefe** [comment]
@chris-echoz SSH does use TLS. In fact encrypt the communication channel with TLS so provide its own encryption mechanism to the channel. Maybe you mean that it should not be used on an ambassador port configured for TLS Termination nor TLS origination. 

Anyway the configuration posted by is perfectly legal and is also present in the official doc:

https://www.getambassador.io/docs/edge-stack/latest/topics/using/tcpmappings/#host-is-not-set-and-the-service-does-not-state-https

@MarkSpencerTan 

Are you sure that you are accessing the service port which is then mapped to 8022 ?
I suppose you are using an external load balancer or service with a public ip which exposes a port. Is this port mapped to 8022 ?

Also with TCP you need to set either `securityModel: SECURE` or `securityModel: INSECURE`. I believe that the last one is the correct one but let's give it a shot to both just in case.

**Comment by chris-echoz** [comment]
@bemipefe SSH is its own transport protocol that in no way, shape or form uses TLS. You can read more about the SSH transport layer protocol in RFC 4253. SSH is on the other hand most commonly used over TCP, if that's what you meant.

**Comment by bemipefe** [comment]
@chris-echoz 

I always wrongly assumed that also SSH was secured with TLS as the majority of the protocols nowadays.
Anyway yes it is build on top of TCP and it doesn't support TLS out of the box.

**Comment by chris-echoz** [comment]
@bemipefe Yeah, it'd be perfectly possible to tunnel it over TLS, though in order to forward it further, it just requires clients setting up the tunnel, which I suppose adds some unwanted friction. (one line in the ssh client config + openssl s_client or an equivalent IIRC)

**Comment by cindymullins-dw** [comment]
Checking in on this issue - is there a feature request or a bug we should address here?  Or perhaps more of a configuration issue on the client side?  Also, if there was any discovery or progress made since this was posted please let us know.

**Comment by MarkSpencerTan** [comment]
Thank you everyone for all the replies! It really helped me to move in the right direction!  @cindymullins-dw  i had to deal with it on the user or client side as @chris-echoz mentioned with openssl and the ssh config. Without that part it wasn't really possible to get the SNI information to route the traffic.

**Comment by sliu2200899** [comment]
@MarkSpencerTan I'm pretty interested in your idea. I'm wondering how did you do the Load Balancer configuration side in AWS.

**Comment by MarkSpencerTan** [comment]
Hey @sliu2200899 we decided to not rely on a LoadBalancer in AWS for our every namespace. We decided to have an ssh reverse proxy or tunnel using nginx that will convert the host information that is sent from the client side to the proxy so it's able to route that traffic internally properly in the cluster.

On the client end you would need them to have an ssh config in ~/.ssh/config with something like this:

```bash
Host *.mydomain
  ServerAliveInterval 60
  UserKnownHostsFile=/dev/null
  StrictHostKeyChecking no
  ProxyCommand openssl s_client -quiet  -servername %h -connect {MY_SSH_PROXY_URL_HERE}:443
```
So when user does something like

ssh user@namespace-svc.namespace.mydomain

namespace-svc.namespace.mydomain gets sent to your ssh reverse proxy and you can send that traffic to the appropriate service in the cluster.

**Comment by sliu2200899** [comment]
@MarkSpencerTan thanks for you information! It's really useful!
