### ISSUE TITLE
gotestsum neither automatically installed nor checked by make preflight

### ISSUE THREAD

**Issue by rbtcollins** [emissary-ingress/emissary#3923]
**Describe the bug**

From a clean checkout of main today:

```
make preflight # all looks good
make test # fails on gotestsum not being installed
...

/home/robertc/src/cognitedata/emissary/builder/builder.sh: line 745: gotestsum: command not found
make: *** [/home/robertc/src/cognitedata/emissary/builder/builder.mk:609: gotest] Error 1
```

**Comment by cindymullins-dw** [comment]
Some info on [gotestsum here](https://circleci.com/blog/level-up-go-test-with-gotestsum/).  If you are using a Golang CircleCI Docker Convenience Image ( circleci/golang ) then gotestsum is pre-installed. If not, users can following installing locally instructions and apply that to your CircleCI config. yml file or, for a custom image, within a Dockerfile.  Closing this issue as there is a viable workaround.

**Comment by rbtcollins** [comment]
I think this is a poor decision, though it is yours to make so this will be my one comment (find me on slack if you'd like a discussion).

New contributors pay the steepest tax in developer friction, since they don't know all the workarounds and accommodations needed. "There is a workaround" when talking about DX is a statement that only super persistent folk that keep on past any number of unnecessary obstacles are welcome as developers.

That works (poorly, but it does) inside a paid environment where folk stay on the same project for months or longer at a time. But if you want to grow a community where the work being done is community driven, then it doesn't work: volunteers* have much lower patience for friction and roadblocks.

At the very minimum I would have thought documenting this in `DEVELOPING.md` would be a step in the right direction; automating it or degrading gracefully better still (e.g. set a variable if the tool is present and fallback to the native go test runner).

*: Everyone paid to work full time on a given project is effectively volunteering when they contribute to a different project, even if its their orgs time they are volunteering, not their personal time
