### ISSUE TITLE
Mapping.weight should not be modified by weight normalization

### ISSUE THREAD

**Issue by kflynn** [emissary-ingress/emissary#3945]
When normalizing the weights of the `Mapping`s in a `MappingGroup` (so that every `Mapping` has a weight, and all the weights in the `Group` sum to 100), the code currently modifies `Mapping.weight`. This can cause mis-weighted `Mapping`s when the `Group` is reconfigured with the cache active.

This should, instead, do calculations in a different attribute, so that the user's original assigned `weight` isn't altered in the cache.

**Comment by kflynn** [comment]
Fixed by https://github.com/emissary-ingress/emissary/pull/3949.

**Comment by khussey** [comment]
This was fixed in Emissary-ingress 2.1.0, which is now available.
