### ISSUE TITLE
1.14.2 contains outdated references in aes-abi.txt

### ISSUE THREAD

**Issue by michalschott** [emissary-ingress/emissary#3955]
Release 1.14.2 contains outdated references `aes-abi.txt` thus unable to build custom modules.

Dirty fix for us is to add replies to go.mod:
```
  go mod edit -replace github.com/envoyproxy/ratelimit@v1.4.0-merged-4=github.com/envoyproxy/ratelimit@v1.4.0
  go mod edit -replace github.com/lyft/ratelimit@v1.3.0-local-vendored-copy=github.com/lyft/ratelimit@v1.3.0
  go mod edit -replace github.com/docker/distribution=github.com/docker/distribution@v0.0.0-20191216044856-a8371794149d
  go mod edit -replace github.com/docker/docker=github.com/moby/moby@v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible
```

**Comment by cindymullins-dw** [comment]
Issues like this are one of the challenges of using plug-ins.  Generally we recommend using an [external filter ](https://www.getambassador.io/docs/edge-stack/latest/topics/using/filters/external#external-filter)which doesn't have to be compiled at each new release like a plug-in does.  Feel free to reopen if this remains an issue on newer releases.
