### ISSUE TITLE
CVE: 70 security issues in v1.13.10

### ISSUE THREAD

**Issue by muhanator** [emissary-ingress/emissary#3977]
**Describe the bug**
Emissary currently has a total of 70 CVE security issues as detected by artifactory xray.
- 7 critical
- 30 high
- 27 medium
- 6 low
_Note: there are 27 Components with no fix version (4 critical, 12 high, 7 medium, 4 low)_

**Context**
We need to update all components with fix versions to their corresponding fix version to fix these security issues.
These need to be resolved ASAP as everyone using ambassador/emissary (Enterprises, Students etc.) are ALL AT RISK.
Attached below are all the security issues (in csv or excel workbook) with details on the infected components and their fix versions.
[Ambassador_v1.13.10_security_issues.xlsx](https://github.com/emissary-ingress/emissary/files/7705797/Ambassador_v1.13.10_security_issues.xlsx)
[Ambassador_v1.13.10_security_issues.csv](https://github.com/emissary-ingress/emissary/files/7705799/Ambassador_v1.13.10_security_issues.csv)

**Versions:**
 - Ambassador: v1.13.10

**Comment by cindymullins-dw** [comment]
[v1.14.3](https://www.getambassador.io/docs/emissary/latest/release-notes/) has addressed these security issues.  Upgrading is recommended.
