### ISSUE TITLE
Rewrite string empty validation error

### ISSUE THREAD

**Issue by LZorglub** [emissary-ingress/emissary#3983]
**Describe the bug**
To prevent Emissary-ingress rewrite the matched prefix we use rewrite : ""
spec:
  hostname: "*"
  prefix: /[a-z\-]*/api/v[0-9]*/qotm[/]*.*
  prefix_regex: true
  service: qotm
  rewrite: ""

When started the emissary pods signals rewrite as error
validation error: Mapping tuto/qotm-mapping -- spec.rewrite in body must be of type string: "null"

**Expected behavior**
An empty string must be valid

**Versions (please complete the following information):**
 - Ambassador: Emissary 2.1.0, v3alpha1
 - Kubernetes environment AKS 1.20.5
 - Version 2.1.0

**Comment by cindymullins-dw** [comment]
Fixed in 2.1.2, [release notes here](https://www.getambassador.io/docs/emissary/latest/release-notes/).
