### ISSUE TITLE
BUG!BUG! tls-context found no validation certificate in secret client-ca-cert in namespace emi

### ISSUE THREAD

**Issue by winkee01** [emissary-ingress/emissary#3994]
#### Symptom
I deployed a demo HTTPS service after applying listner, host, tls-context, mapping and deployment.yaml stuff, all in namespace `emi`, but I failed to connect to it via `curl -v https://<demo.com>` with this error:
```
...
SSL routines:ssl3_get_record:wrong version number
```

checking pod's log, it shows:

```
error tls-context.emi.1 TLSContext tls-context found no validation certificate in secret client-cacert in namespace emi
```

#### Reproduce
(1)
Freshly install Emissary-ingress via [Official tutoral](https://www.getambassador.io/docs/emissary/latest/topics/install/helm/), 

(2)
I created two secrets in namespace `emi`, one for TLS termination (`emissary.key`, `emissary.crt`), the other for client's CA cert. all certs are issued using a common root CA cert.
```
k create -n emi secret generic client-ca-cert --from-file=/usr/local/share/ca-certificates/ca.crt 
k create -n emi secret tls emissary-cert --key=emissary.key --cert=emissary.crt
```
(3)
Simple apply the TLSContext as instructed with this file `tls-context.yaml`:

```
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: tls-context
  namespace: emi
spec:
  hosts: [ "demo.emissary.io" ]
  secret: emissary-cert
  alpn_protocols: h2
  ca_secret: client-ca-cert.emi
  cert_required: true
  secret_namespacing: true
```

(4) check pod's logs
```
k logs emissary-ingress-dffc6b988-4t9cz -n emissary
```

log results

```
2022-01-01 07:11:02 diagd 2.1.0 [P23TAEW] ERROR: Secret client-ca-cert.emi unknown
2022-01-01 07:11:02 diagd 2.1.0 [P23TAEW] INFO: tls-context.emi.1: <RichStatus BAD error='TLSContext tls-context found no validation certificate in secret client-ca-cert in namespace emi' hostname='emissary-ingress-dffc6b988-4t9cz' version='2.1.0'>
2022-01-01 07:11:02 diagd 2.1.0 [P23TAEW] INFO: EnvoyConfig: Generating V3
2022-01-01 07:11:02 diagd 2.1.0 [P23TAEW] INFO: V3Listener: ==== GENERATED <V3Listener HTTP listener on 0.0.0.0:8080 [XFP]>
2022-01-01 07:11:02 diagd 2.1.0 [P23TAEW] INFO: configuration updated (incremental) from snapshot snapshot (S23 L1 G4 C2)
2022-01-01 07:11:02 diagd 2.1.0 [P23TAEW] INFO: error tls-context.emi.1 TLSContext tls-context found no validation certificate in secret client-ca-cert in namespace emi
time="2022-01-01 07:11:02.3964" level=info msg="Loaded file /ambassador/envoy/envoy.json" func=github.com/datawire/ambassador/v2/cmd/ambex.Decode file="/go/cmd/ambex/main.go:279" CMD=entrypoint PID=1 THREAD=/ambex
time="2022-01-01 07:11:02.3971" level=info msg="Saved snapshot v16" func=github.com/datawire/ambassador/v2/cmd/ambex.csDump file="/go/cmd/ambex/main.go:369" CMD=entrypoint PID=1 THREAD=/ambex
time="2022-01-01 07:11:02.3976" level=info msg="Pushing snapshot v16" func=github.com/datawire/ambassador/v2/cmd/ambex.updaterWithTicker file="/go/cmd/ambex/ratelimit.go:159" CMD=entrypoint PID=1 THREAD=/ambex
...
```

#### Note:
This is a clean installation of Emissary-Ingress, and it simply can not read out the secret? the sure things here are secrets and namespaces are all correct, no clue what could be the problem.

**Comment by cindymullins-dw** [comment]
We don't see anything wrong here but perhaps worth noting that Ambassador doesn’t detect a change done the paths defined in cert_chain_file and/or private_key_file and reload the TLSContext cert.  There's a difference in reloading mechanisms between secret-based vs file-based certs.  This is a new cert?
There were a couple bugs with 2.1 - have you tried upgrading to the latest version?

**Comment by cindymullins-dw** [comment]
If these are Kubernetes secrets rather than file-based certs and the issue persists on Emissary-ingress 2.x or 3.x please reopen.
