### ISSUE TITLE
host_redirect doesn't work with v2.1.0

### ISSUE THREAD

**Issue by gferon** [emissary-ingress/emissary#4005]
**Describe the bug**
`Mapping` resources with `host_redirect: true` do not end up in the Envoy configuration file.

**To Reproduce**
1. Install `emissary-ingress` Helm chart with default parameters
2. Create a wildcard `Host` resource
3. Create a `Mapping` object like [from the example](https://www.getambassador.io/docs/edge-stack/latest/topics/using/redirects/#basic-redirect)
4. Try to access the resource: you get "404 Not Found"

**Expected behavior**
"301: Moved Permanently"

**Versions (please complete the following information):**
 - Ambassador: 2.1.0
 - Kubernetes environment: doesn't matter

**Comment by gferon** [comment]
Probably a duplicate of #3709 but describes the actual problem.

**Comment by khussey** [comment]
This was fixed in Emissary-ingresss 2.1.2, which is now available.
