### ISSUE TITLE
Chart 7.2.2 default image repository causing ErrImagePull

### ISSUE THREAD

**Issue by wobo-ryan** [emissary-ingress/emissary#4051]
**Describe the bug**
The 7.2.2 chart release has a new default image repository of `dwflynn/emissary`. This fails with
```
Failed to pull image "dwflynn/emissary:2.1.2": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/dwflynn/emissary:2.1.2": failed to resolve reference "docker.io/dwflynn/emissary:2.1.2": docker.io/dwflynn/emissary:2.1.2: not found
```

**To Reproduce**
Follow the Helm documentation to install Emissary with Helm: https://www.getambassador.io/docs/emissary/2.1/topics/install/helm/
```
kubectl apply -f https://app.getambassador.io/yaml/emissary/2.1.2/emissary-crds.yaml
helm repo add datawire https://app.getambassador.io
helm repo update
helm install -n emissary --create-namespace emissary-ingress datawire/emissary-ingress
```

**Expected behavior**
The image would pull successfully.

**Versions (please complete the following information):**
 - Ambassador: 2.1.2
 - Kubernetes environment: Microk8s
 - Version: v1.22.5

**Additional context**

**Comment by kflynn** [comment]
I've fixed the charts -- my apologies!! 🙁  and many many thanks for the report!
