### ISSUE TITLE
Docs: Host resource not actually required?

### ISSUE THREAD

**Issue by wmcnamee-tunein** [emissary-ingress/emissary#4069]
**Describe the bug**
I think I found an inconsistency in the documentation:

https://www.getambassador.io/docs/edge-stack/latest/howtos/configure-communications/
> Remember that Listener and Host resources are required for a functioning Ambassador Edge Stack installation that can route traffic!

During the Getting-Started: https://www.getambassador.io/docs/edge-stack/latest/tutorials/getting-started/

I never end up deploying a Host object.
Is it NOT true that a Host resource is actually required?

**Comment by hickert33** [comment]
I found this in the docs:

https://www.getambassador.io/docs/edge-stack/latest/topics/running/tls/#host

Stating host is synthesized up if no host resources are present.

I would like to know how to see them as synthesized....

**Comment by antonu17** [comment]
This is not valid for v2+

**Comment by cindymullins-dw** [comment]
If you don't specify a host resource Ambassador will assume one and use a self-signed cert so you don’t have to specify your own, synthesizing a pseudo host, as in our QuickStart.  But this is not the same as creating an actual Host resource and can't be queried.  While you can technically get started with Ambassador without specifying a Host resource, it will be needed for most real-world applications involving TLS and routing, as that callout suggests.
