### ISSUE TITLE
Kubectl Explain doesn't list properties of `mapping.spec`

### ISSUE THREAD

**Issue by ghostsquad** [emissary-ingress/emissary#4071]
**Please describe your use case / problem.**
I'd like to get some useful information from Kubernetes about the CRD using `kubectl explain`.

```
at 16:30:11 ❯ k explain mapping.spec
KIND:     Mapping
VERSION:  getambassador.io/v2

DESCRIPTION:
     MappingSpec defines the desired state of Mapping
```

**Describe the solution you'd like**
This command can return useful information that I'm used to with other CRDs like ArgoRollouts.

Additionally, it would be very nice if the API spec was published similar to how K8s publishes all resources here:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/

**Describe alternatives you've considered**
Trying to glean the object structure, fields, valid values, defaults, etc from this page:
https://www.getambassador.io/docs/edge-stack/latest/topics/using/mappings/

**Additional context**
N/A

**Comment by kflynn** [comment]
(Closing given the workaround.)
