### ISSUE TITLE
Emissary Ingress drops all but one set-cookie

### ISSUE THREAD

**Issue by seunggs** [emissary-ingress/emissary#4096]
**Describe the bug**
Using Ory Kratos service that sends back 3 `set-cookie` headers - emissary ingress mapping drops all but one `se-cookie` header.

**To Reproduce**
1. Launch Ory Kratos (or any server really) and creating a mapping for `https://my-domain.com/kratos`
2. Hit the server endpoint which sends back 3 `set-cookie` headers - works fine in local env where no emissary ingress is used
3. In the Response header, only 1 `set-cookie` is sent back

**Expected behavior**
Expect to receive all 3 `set-cookie` headers

**Versions (please complete the following information):**
 - Ambassador: 2.1.2
 - Kubernetes environment AWS EKS
 - Version: Kubernetes 1.21

**Comment by cindymullins-dw** [comment]
Is it always dropping the same cookie headers and is it the first one that is returned?  Can you post your Mapping config?  In the mapping you can configure sticky sessions - we wonder if you're using that for session affinity?

**Comment by cindymullins-dw** [comment]
Closing issue for lack of response/ability to assess further.
