### ISSUE TITLE
Is it supported to upgrade from 1.13.x to 2.2.2 ？

### ISSUE THREAD

**Issue by zhangyihong** [emissary-ingress/emissary#4165]
currently, I am running version 1.13.x due to [issues with 1.14](https://github.com/emissary-ingress/emissary/issues/3818) 

I haven't seen the documentation for upgrading from 1.13.x to 2.2.2 from the [official documentation](https://www.getambassador.io/docs/emissary/latest/topics/install/migration-matrix/#if-you-installed-ossproductname-manually-by-applying-yaml)

Is there any way to solve my problem please?

**Comment by alexgervais** [comment]
As per the documentation you pointed to, it is not possible to upgrade from 1.13.x to 2.x without downtime.

**Comment by irl-segfault** [comment]
@alexgervais is it possible if you set up a second LB, then switch DNS?  Or is there an issue with clashing API versions?

**Comment by alexgervais** [comment]
It might work given your setup, or apiext might somehow implode because of CRD differences. We don't officially support migrating from 1.13, but @kflynn might have attempted this migration path and might have suggestions.

**Comment by cindymullins-dw** [comment]
Supported [migration paths are noted here](https://www.getambassador.io/docs/emissary/latest/topics/install/migration-matrix/).  If you'd be interested in a live session on migration, please [sign up here.](https://www.getambassador.io/about-us/events/emissary-ingress-edge-stack2.1-migration-office-hours/)
