### ISSUE TITLE
Emissary 1.14.2 - Preserving Client IP

### ISSUE THREAD

**Issue by mreddimasi** [emissary-ingress/emissary#4176]
**Describe the bug**
Issue with Preserving Client IP.

**To Reproduce**
1. helm repo list   has - datawire	https://www.getambassador.io
2. create namespace test-ambassador (There is an existing ambassador installation in the cluster, called ambassdor.)
3. helm upgrade -f 8-values-ambassador.yaml --install --set enableAES=false test-ambassador-release datawire/ambassador -n test-ambassador (contents of 8-values-ambassador.yaml listed below)
4. kubectl apply -f mappings-dev2.yaml (contents of mappings-dev2.yaml listed below)
5. Use loadbalancer IP to try ping a service like for ex: http://a82b125f5e557467581c86350c9aa891-197548772.ap-south-1.elb.amazonaws.com/xcheckout/ping ... This gives a 504 Gateway timeout error

**Expected behavior**
Response from the backend service should work and should log the client ip address instead of loadbalancer ip address.

**Versions (please complete the following information):**
 - Ambassador: [Emissary-Ingress 1.14.2]
 - Kubernetes environment [AWS - EKS]
 - Version [ 1.20]

**Additional context**

[values-mappings.zip](https://github.com/emissary-ingress/emissary/files/8391549/values-mappings.zip)

**Comment by mreddimasi** [comment]
Curl output from inside a pod in the cluster

`/app $ curl -v http://a82b125f5e557467581c86350c9aa891-197548772.ap-south-1.elb.amazonaws.com/xcheckout/ping
*   Trying 15.207.9.101:80...
* Connected to a82b125f5e557467581c86350c9aa891-197548772.ap-south-1.elb.amazonaws.com (15.207.9.101) port 80 (#0)
> GET /xcheckout/ping HTTP/1.1
> Host: a82b125f5e557467581c86350c9aa891-197548772.ap-south-1.elb.amazonaws.com
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 504 GATEWAY_TIMEOUT
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host a82b125f5e557467581c86350c9aa891-197548772.ap-south-1.elb.amazonaws.com left intact
/app $ 

`

**Comment by mreddimasi** [comment]
Emissary logs
[emissary.zip](https://github.com/emissary-ingress/emissary/files/8394990/emissary.zip)

**Comment by mreddimasi** [comment]
To recap, here's the setup in our development environment, there are 2 installations of Emissary Ingress in out development servers 

- ambassador (in namespace ambassador, without ambassador_id)
- ambassador2 (in namespace test-ambassador, was created to debug the IP issue, with ambassador_id = test_ambassador)

### Host resource for **ambassador** is as below
```
apiVersion: getambassador.io/v2
kind: Host
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"getambassador.io/v2","kind":"Host","metadata":{"annotations":{},"generation":1,"name":"test-host","namespace":"ambassador"},"spec":{"acmeProvider":{"authority":"none"},"hostname":"*","requestPolicy":{"insecure":{"action":"Redirect","additionalPort":8080}},"tls":{"min_tls_version":"v1.2"},"tlsSecret":{"name":"ambassador-certs"}}}
  creationTimestamp: "2021-07-22T17:33:42Z"
  generation: 3
  name: test-host
  namespace: ambassador
  resourceVersion: "21280547"
  uid: 286b1d4d-3d5f-477d-98c2-a84f02964ef6
spec:
  acmeProvider:
    authority: none
  hostname: '*'
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080
  tls:
    min_tls_version: v1.2
  tlsSecret:
    name: ambassador-certs
```

If you notice, the TLS termination is happening at the Emissary Ingress level at and the hostname is mentioned as '*'. I think that due to this configuration we are seeing the timeout error.

I've now, tried configuring **ambassador2** with 

`service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"`
and
the target port as 8080 with Module config of use_remote_address: false and xff_num_trusted_hops: 1

After this change, the LB would be L7 without any TLS termination, when we do this, In the **amssador2 pod logs I'm able to see the remote IP address correctly**. However, now I'm getting a 404 error as **ambassador2** is not able to find the mapping for the backend service xcheckout.

I tried creating a mapping for ambassador2 using the following, but still getting the 404 error.

```
---
apiVersion:  getambassador.io/v2
kind:  Mapping
metadata:
  name:  xcheckout-dev2-mapping
  namespace:  test-ambassador
spec:
  ambassador_id: ["test-ambassdor"]
  prefix:  /xcheckout/
  host: api.dev2.xpresslane.in
  rewrite:  /
  service:  xcheckout.dev:8888
  timeout_ms: 50000
```

**Comment by cindymullins-dw** [comment]
We do support client IP so might be something is misconfigured.  One thing to check would be the module config where you'd need to set [num_trusted_hops](https://www.getambassador.io/docs/edge-stack/latest/topics/running/ambassador-with-aws/#preserving-the-client-ip-address).  (Not relevant to you atm, but pls note with 2.0, this setting [moved from the Module] to the Listener resource (https://www.getambassador.io/docs/edge-stack/latest/topics/install/convert-to-v3alpha1/#10-some-module-settings-have-moved-or-changed).) Also, can you confirm [all of your resources](https://www.getambassador.io/docs/edge-stack/latest/topics/running/running/#ambassador_id) are tagged with the correct Ambassador_ID?

**Comment by cindymullins-dw** [comment]
If this issue is persisting on newer versions please let us know.
