### ISSUE TITLE
Md. Abdul Alim Talukder

### ISSUE THREAD

**Issue by italukder** [emissary-ingress/emissary#4193]
**Please describe your use case / problem.**
A clear and concise description of your use case / problem. The "why" is really valuable to us. For example, "I have a set of services whose clients have long-lived connections."

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by italukder** [comment]
people is not freedoms in my all sites and all people of world normal working in my  sites. and http/2 and http/3 new certified services in next year and http/2 android services certification and http/3 computer certification. and https website working certificate services next years

**Comment by italukder** [comment]
https://surma.dep.
setting up http/2 . Mr. surma is normal setting works http/2 protocol

Thank you

**Comment by kflynn** [comment]
This doesn't actually look like an Emissary-ingress issue. Please let me know if I'm somehow wrong there...
