### ISSUE TITLE
Resolver in module not honored when ambassador_id is set

### ISSUE THREAD

**Issue by karthik-vijayaraju** [emissary-ingress/emissary#4200]
**Describe the bug**
We run two Ambassador deployments in our environment, one for external and one for internal traffic.
On both of these we set the resolver to KubernetesEndpointResolver in the Module object (we have two module objects in different namespaces).

While on the external Ambassador, the resolver config is honored and envoy is configured to use EDS on each mapping, on the internal Ambassador which has an ambassador_id set, the resolver config is not present in the envoy.json.
When we added the resolver config to the Mapping object for a specific app, it was honored though and the EDS config was generated for that app.
The default DNS resolver is causing skewed request distribution, so we need to use KubernetesEndpointResolver.

**To Reproduce**
1. Deploy two Ambassador stacks. One without ambassdor_id and another with an ambassador_id in different namespaces.
2. Apply mapping configs for each. Make sure the internal Ambassador's mapping objects have ambassador_id set.
3. Create a KubernetesEndpointResolver object, one in each namespace and set resolver: endpoint in respective modules.
4. Exec in one of the Ambassador pods for each deployment and check envoy.json. OR generate load to find that the Ambassador stack with ambassador_id setup in module does not load balance properly.

**Expected behavior**
envoy should be configured to use EDS for Kubernetes for both stacks of Ambassador.

**Versions (please complete the following information):**
 - Ambassador: 1.13.1
 - Kubernetes environment EKS 1.21

**Comment by cindymullins-dw** [comment]
Did you set the ambassador_id on your endpoint resolver?  The KubernetesEndpointResolver is an Ambassador resource - so would require an ambassador_id on whichever one applies to your internal Ambassador.  Can you share the config with us for both of the KubernetesEndpointResolvers and for your Modules as well?

**Comment by cindymullins-dw** [comment]
Please let us know if you need further assistance or if this issue persists on Emissary 2.x or 3.x.
