### ISSUE TITLE
[1.14] Backport k8s 1.22 changes into ambassador

### ISSUE THREAD

**Issue by eanveden** [emissary-ingress/emissary#4225]
Hi, I was wondering if there is any chance we could backport 1.22 (v1beta -> v1) [updates ](https://github.com/emissary-ingress/emissary/pull/3833) and release 6.9.5 of the chart? I don't mind doing it myself if you need someone to contribute.

We have a lot of developers using the chart and migrating to envoy-ingress before our target k8s 1.22 upgrade is not really an option

**Comment by orendain** [comment]
FYI according to https://github.com/emissary-ingress/emissary/issues/4031#issuecomment-1018564706, Datawire does not plan on providing resource updates to the Ambassador v1 chart.

We, too, are looking to deploy onto K8s 1.22 and haven't been able to consider migration to emissary-ingress.

**Comment by cindymullins-dw** [comment]
We've outlined our reasoning for not backporting support for k8s 1.22 into 1.14 in this [blog post ](https://blog.getambassador.io/ambassador-edge-stack-1-y-series-and-kubernetes-1-22-what-you-need-to-know-f2817b2b409e)
As it is open source, an option would be to fork it and make a custom build fit to your requirements.
