### ISSUE TITLE
RBAC Documentation

### ISSUE THREAD

**Issue by robd003** [emissary-ingress/emissary#4233]
Does anyone know where I could find docs on the RBAC roles for emissary?

I'd like to create a Kubernetes user that only has the ability to create `Hosts` and `Mappings` and then modify a Listener to add the new Host to the `hostBinding`  without the ability to modify or delete anything else. I've looked through the emissary docs but couldn't find anything showing a list of available RBAC permissions.

**Comment by cindymullins-dw** [comment]
The Helm chart lets you specify whether you're using RBAC roles but while Ambassador respects RBAC in terms of authenticating users, it doesn't limit permissions down to which CRDs you apply within Ambassador itself.  The assumption with an API gateway is that an admin has cluster-level permissions.  We suggest looking thru the RBAC that is generated to see how those permissions work across the cluster (ie read/write/list) for each of the resources by running get cluster roles - o yaml and tailor your RBAC as much as you can to the desired outcome.
