### ISSUE TITLE
Option to build envoy in FIPS mode.

### ISSUE THREAD

**Issue by bathina2** [emissary-ingress/emissary#4277]
**Please describe your use case / problem.**
There are some clients that would like emissary ingress to support FIPS approved encryption algorithms. 

**Describe the solution you'd like**
Since there is already a way to build envoy, some additional flags to build it in FIPS mode would be a nice addition.

**Describe alternatives you've considered**
Using envoy by itself.

**Comment by bathina2** [comment]
I have a reasonable enhancement to support this. I would like to work on this issue and contribute if I can.

Thanks,
Sirish

**Comment by ddymko** [comment]
Closing since this is resolved
