### ISSUE TITLE
Improvements to Helm Chart Autoscaling (HPA)

### ISSUE THREAD

**Issue by aztechian** [emissary-ingress/emissary#4289]
**Describe the bug**
The default autoscaling settings are not terribly useful. I understand that autoscaling is disabled by default, but it would be more user-friendly to have valid HPA settings by just changing `autoscaling.enabled: true`.

There's two (sub) issues here:
1. When using Emissary with ArgoCD, the order of the HPA metrics is reversed from what the Kubernetes API returns, causing ArgoCD to always show the HPA resource as out-of-sync.
2. By only setting `autoscaling.enabled: true` the HPA defaults of 60% utilization of CPU and Memory cause the HPA to immediately scale up to max pods because HPA bases its decisions off of requests (not limits) and the requests are tuned pretty well to the cpu/ram needed for an empty emissary to run.

**To Reproduce**
1. Deploy with the helm chart, and `--set autoscaling.enabled=true`
2. Observe HPA scaling up to 5 pods
<img width="705" alt="image" src="https://user-images.githubusercontent.com/1534350/174170650-2892560c-4c5f-4b72-a465-2ceed328b69e.png">
3. No load is on the emissary pods, as there are no mappings yet provided to handle.

**Expected behavior**
The HPA has values that keep emissary at the minimum number of pods until actual load is introduced.

Interaction with ArgoCD does not cause continuous out-of-sync status.

**Versions (please complete the following information):**
 - Ambassador: [2.3.1], 
 - Emissary Chart: [7.4.1]
 - Kubernetes environment [EKS v1.22.6]

**Additional context**

**Comment by LanceEa** [comment]
@aztechian - As we discussed during the Contributors Meeting:

1. We are comfortable with reordering the metrics to help out with ArgoCD syncing. 
2. We are comfortable with adjusting the default CPU as you proposed
3. For the memory, we suggest bumping the default to 100 for now

**Comment by aztechian** [comment]
PR has been rebased to master and memory threshold changed to 100%.
