### ISSUE TITLE
HTTP request to a mapping with `allow_upgrade` option set to `websocket` causes `upstream connect error or disconnect/reset before headers. reset reason: connection termination` error

### ISSUE THREAD

**Issue by seunggs** [emissary-ingress/emissary#4368]
**Describe the bug**
Sending HTTP request to a mapping with `allow_upgrade` option set to `websocket` causes `upstream connect error or disconnect/reset before headers. reset reason: connection termination` error

**To Reproduce**
1. Create a mapping with `allow_upgrade` option set to `websocket` to a service running a node ExpressJs server (and socket.io)
2. Wait until socket connection is made successfully
3. Try to send a HTTP GET request to one of the ExpressJs endpoints and it'll return 503 with `upstream connect error or disconnect/reset before headers. reset reason: connection termination` error and also disconnect the socket. After a few seconds, the socket will connect again, but sending another HTTP GET request will return 503 again and disconnect the socket.

**Expected behavior**
Sending HTTP request should work and not disconnect the socket

**Versions (please complete the following information):**
 - Ambassador: App Version: 2.1.2
 - Kubernetes environment: EKS 1.22

**Comment by kumud-oa** [comment]
@seunggs I am facing a similar issue on emissary 3.8.1. What is the fix that worked for you?
