### ISSUE TITLE
Documentation incorrect when assigning IP addresses?

### ISSUE THREAD

**Issue by TCBroad** [emissary-ingress/emissary#4372]
Hi,

I've recently been updating my ambassador installation to edge-stack/emissary-ingress on Azure and have had some issues getting the new installation to accept any traffic.

Looking at the values on the helm chart would imply that you set service.externalIPs as your public inbound IP address but this isn't the case. I got no response from any service, nothing in logs, etc, until I'd set service.loadBalancerIP. This property is not documented anywhere on the helm chart that I could see, and seems important for getting any traffic into a cluster!

Is the documentation incorrect or is it listed somewhere that I have missed?

Thanks,
Tom

**Comment by cindymullins-dw** [comment]
There's limited information that can be included or explained in detail with the helm chart (although if you found it misleading please let us know).  In general we'd suggest referring to resources like this for details on using [externalIP](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips) and [loadBalancerIP](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer).
