### ISSUE TITLE
Invalid Envoy Config Generated From Emissary GZIP Filter

### ISSUE THREAD

**Issue by BenGatewood** [emissary-ingress/emissary#4461]
**Describe the bug**
Enabling gzip compression as described on the docs page here: https://www.getambassador.io/docs/edge-stack/latest/topics/running/gzip/ appears to cause emissary to generate invalid envoy configuration. Specifically seems to be related to the `compression_level: BEST` line as excluding that line avoids the issue 

**To Reproduce**
1. Apply ambassador module config with the `compression_level: BEST` line present

**Expected behavior**
Valid envoy configuration to be generated enabling the gzip feature

**Versions (please complete the following information):**
Ambassador: [e.g. 3.1.0]
Kubernetes environment: GKE
Version: 1.23.7-gke.1400

**Comment by mrnonz** [comment]
Can you try with `BEST_SPEED`?

**Comment by bothra90** [comment]
We are seeing an issue with gzip as well, but instead of generating an invalid envoy config, it simply gets ignored. In the emissary logs, we don't see a snapshot update. Restarting the pods does not reflect the change either.

Config applied:
```
gzip:
    compression_level: "BEST_SPEED"
```

Emissary version: 3.0.0
k8s version: 1.22 EKS

cc: @cindymullins-dw

**Comment by cindymullins-dw** [comment]
Hi @BenGatewood , some users have had success using BEST_COMPRESSION as noted [here](https://github.com/emissary-ingress/emissary/issues/5278#issuecomment-1746850741).  Could you try that and let us know?

**Comment by cindymullins-dw** [comment]
Please feel free to reopen if not resolved.
