### ISSUE TITLE
Figure out what to do about gold tests

### ISSUE THREAD

**Issue by LukeShu** [emissary-ingress/emissary#4515]
From the discussion on https://github.com/emissary-ingress/emissary/pull/4477:

@LanceEa wrote:
> @LukeShu - General question on the Gold Tests...I thought we dropped those in v3, correct? What was the reason for dropping these? Did we not feel they were beneficial, duplicates of other tests, or some other reason? I see these are still available in v2 so we at least kept them around for that.

@LukeShu wrote:
> > General question on the Gold Tests...I thought we dropped those in v3, correct? What was the reason for dropping these? Did we not feel they were beneficial, duplicates of other tests, or some other reason?
> 
> The annotation fixes in 2.1.2 (https://github.com/emissary-ingress/emissary/pull/4016) willfully broke our ability to run the gold tests; as the mechanisms it uses to run those tests need substantially reworked to work with the fixes.
> 
> That said, in the months since then, I have come to believe that we don't get value from the gold tests.  The gold tests were an hacky optimization; avoiding CI-billing, dev-wait-time, and CI-flakes associated with running the full `KAT_RUN_MODE=envoy` tests.
> - However, we had previously (in the 1.x timeframe) had several incidents where we were bitten by a developer mistakenly checking in bad gold files and a regression getting shipped; as a corrective action, we started running the `KAT_RUN_MODE=envoy` tests in CI (you should be able to find postmortems in Notion).  In my opinion; at that point the gold tests are redundant; but potentially still useful for saying "oh, the envoy failed but the gold didn't change; this is almost certainly a CI flake".  I'm not sure anyone intended for "have CI always run both gold and envoy" to be a long term situation; but a temporary CI bloat while we figure out how to safely trim CI back down.
> - The value that we'd get by switching back to running the tests with gold is minimal:
>   - We have migrated from CircleCI to GitHub Actions; GHA is free for Emissary, so there's no costs to cut there; though there is in Edge Stack.
>   - We have split the envoy tests across multiple jobs; this has both cut time dev-wait-time and reduced flakes.  The "slow" envoy tests now run faster than the "fast" gold tests ever did.
>   - As we've been forced to live with the Envoy tests in CI, we've dramatically improved their flakiness.
> 
> That said, I never managed to convince @kflynn that the gold tests aren't worth bringing back; so the scripts related to them haven't been deleted. Flynn, would you care to weigh in on why you believe that the gold tests are worth bringing back?
> 
> > I see these are still available in v2 so we at least kept them around for that.
> 
> No? The gold directory does not exist in `release/v2.4`.  Some of the machinery around gold is still there; but because it's not getting run, the gold files are dead weight, so we deleted them.  If we start running them again, all that it would take to bring them back is `make pytest-gold`.

We should either do what is necessary to bring them back, or delete all of the dead-weight machinery related to them.

**Comment by kflynn** [comment]
> - We have split the envoy tests across multiple jobs; this has both cut time dev-wait-time and reduced flakes. The "slow" envoy tests now run faster than the "fast" gold tests ever did.
> - As we've been forced to live with the Envoy tests in CI, we've dramatically improved their flakiness.

If memory serves, the reason @LukeShu never convinced me is that the last time we talked about it, these two things hadn't happened, and I was really frustrated with KAT taking a long time, then having to be restarted due to a flake. 😐 (Or maybe the split had happened, but we hadn't finished the antiflakification. It was awhile ago, anyway.)

At this point, we clearly have an existence proof that we don't need the gold tests, and I'm OK with removing the machinery. (If we really need to revive it, we can go look back in the Git history anyway.)
