### ISSUE TITLE
release: add ability to publish manifest and helm chart fixes independent of container

### ISSUE THREAD

**Issue by LanceEa** [emissary-ingress/emissary#4583]
## Summary

The current release process ties the releasing of the emissary image to the release of the charts and manifests. We should have the ability release these two independently so that we can do z patches when we find bugs rather than having to wait for an Emissary-ingress image release. 
## Goals

- allow chart/manifest changes to be released independently from container image release
- no manual steps should be required beyond tagging a branch or something similar

**Comment by haq204** [comment]
So one challenge is the potential for drift between manifests and the chart. i.e we make updates in the chart but not in the raw manifests. Currently manifests are tied to the emissary version and generated when promoting to RC or GA. Furthermore the download link uses the Emissary version:
```
https://app.getambassador.io/yaml/edge-stack/3.2.0/aes.yaml
```

The way I see it we have two options:

1. Accept that the raw manifests are tied to the Emissary version and Chart is versioned separately. This means we have to accept the potential for drift and that chart changes won't make it into the raw manifests until the next Emissary Release 

2. Publish new manifests when we publish a new chart. We should NOT overwrite the manifests pushed when an Emissary version was released. Therefore for this, I propose we modify the url to be:
```
https://app.getambassador.io/yaml/edge-stack/[Emissary X.Y.Z]-[Chart X.Y.Z]/aes.yaml
```
This would require update getambassador.io to refer to the new url format

**Comment by haq204** [comment]
As for how to do chart versioning I propose the following guidlines:
- minor chart version bump require an Emissary version bump. so `8.3.0 -> 3.3.0` etc.
- chart patch versions can be independent so `8.3.1` could still use Emissary `3.3.0`.

With this in mind, I propose the following workflow when doing an independent chart release :
1. checkout a new branch `rel/chart/vx.y.z` from `master` or `release/vx.y.z`

2. update chart Changelog as necessary and commit. This step might not be needed depending if changelogs get autogenerated.

3. Wait for CI to pass. Ideally we shouldn't run the full gauntlet of tests. chart updates shouldn't require running KAT tests. The only tests need running should be the generate check, build check, and helm check. This should cut down on CI time significantly. 

If changelogs are autogenerated then steps 1-3 becomes unnecessary. Just make sure the latest commit has CI green.

4. tag with new chart version `chart/vx.y.z` and push that up. this should trigger the publish-chart GH actions workflow to publish the new chart using the latest tagged emissary version (can include RCs). i.e if I push up `charts/v8.3.1` it will use Emissary `v3.3.0`. If I did tag `v3.3.1-rc.0` to mark a new Emissary RC, then it will use that instead etc. There could be a check here to make sure minor versions match i.e `charts/v8.4.0` should find `v3.4.0` if it finds `v3.3.z` that's no bueno.

There is a question whether we should prepare chart RC candidates. That would be only useful for smoke testing but the only smokes tests we would run is the helm install check and manual install check. helm changes already are tested using the helm-check in CI so not sure if this is entirely necessary.

[5.] If we did do chart RC releases and assuming those look good, then tag for chart GA and push that up. This would trigger the publish chart workflow again to push the GA chart.

**Comment by LanceEa** [comment]
> We should NOT overwrite the manifests pushed when an Emissary version was released. Therefore for this, I propose we modify the url to be

Playing devil's advocate...what is the risk to a 3rd option that is overwriting the manifest for a version? It simplifies things that need to change and would accomplish what we want. I guess the downside his missing history, no way for users or us to know if they have the right versions...Not necessarily advocating but more or less thinking out loud.

> If change log are autogenerated then steps 1-3 becomes unnecessary. Just make sure the latest commit has CI green.

I don't think we need to complicate processes with automating the generation of this change log. It rarely changes and only small changes are typically made so I don't think it is going to be a source of merge conflicts like the overall change log.

But, I do think the statement is true that these steps in most cases are not necessary because the current process is make your change and include a change log so once that is merged and CI is green then is already free to be released.

> publish the new chart using the latest tagged emissary version (can include RCs)

I'm not sure I agree with the "include RC's". I think we should keep it simple at first and only add additional features if we find ourselves wanting these. The rule should be:

- `chart/vx.y.z` looks for `vx.y.z` tags
- `chart/vx.y.z-rc.n` looks for `vx.y.z-rc.n` tags

This ensures we do not accidentally ship a GA version with an rc tag. We can also add more advanced checks as you mentioned to ensure that the matrix of versions match correctly `8->3` and `7->2`, etc...

**Comment by haq204** [comment]
> I'm not sure I agree with the "include RC's". I think we should keep it simple at first and only add additional features if we find ourselves wanting these. The rule should be:

chart/vx.y.z looks for vx.y.z tags
chart/vx.y.z-rc.n looks for vx.y.z-rc.n tags

I mention that only if we don't bother creating chart rcs. if we do then yea chart GA versions should only reference Emissary GA versions.

**Comment by haq204** [comment]
> One other question I thought of...is manually pushing of tags the appropriate mechanism. I mean it is 
> easy and I really like it because it is easy but the big downside is there is no review process.

Counter argument why should creating an RC require a review process?

**Comment by AliceProxy** [comment]
I don't think a review should necessarily be required either, and I like the idea of just pushing a tag and then perhaps having a workflow that required manual approval for the final publishing steps.

**Comment by ddymko** [comment]
Going through this now.

> https://app.getambassador.io/yaml/edge-stack/[Emissary X.Y.Z]-[Chart X.Y.Z]/emissaryns.yaml

Not sure how I feel about this. As a user, if I am not using helm I don't really find much used to have the chart name included there and might consider it noise and/or confusing. 


> checkout a new branch rel/chart/vx.y.z from master or release/vx.y.z

Would we then merge `re/chart/Vx.y.z` back into `master` or `release/Vx.y.z`?

Bit of a side note. I think we should always have `release/Vx.y.z` branches even for `v3` that is a different topic/discussion but just wanted to drop a line about it.


> As for how to do chart versioning I propose the following guidelines:
> minor chart version bump require an Emissary version bump. so 8.3.0 -> 3.3.0 etc.
> chart patch versions can be independent so 8.3.1 could still use Emissary 3.3.0.

Agreed, this is the standard I had followed in the past. Then if we had emissry 3.3.1 I would bump helm to 8.3.2 (if it was on 8.3.1)


> There is a question whether we should prepare chart RC candidates.

I think for this initial setup we should keep it simple. As we use it, we'll quickly discover what is missing and add it in. This is the approach I am taking with the subtree changes (which I have to write up in the GH issue). Just make it "bare bones" and iterate over it.


> One other question I thought of...is manually pushing of tags the appropriate mechanism. 

It works, however, I am always triple checking myself right before I push the tag. In the past, I automated the tag process based on PR releases. Once a "release PR" became approved and merged, that would have triggered the tag creation and push. We already have "release PRs" so it would extend that behavior of those.

**Comment by ddymko** [comment]
Going through this now.

> https://app.getambassador.io/yaml/edge-stack/[Emissary X.Y.Z]-[Chart X.Y.Z]/emissaryns.yaml

Not sure how I feel about this. As a user, if I am not using helm I don't really find much used to have the chart name included there and might consider it noise and/or confusing. 


> checkout a new branch rel/chart/vx.y.z from master or release/vx.y.z

Would we then merge `re/chart/Vx.y.z` back into `master` or `release/Vx.y.z`?

Bit of a side note. I think we should always have `release/Vx.y.z` branches even for `v3` that is a different topic/discussion but just wanted to drop a line about it.


> As for how to do chart versioning I propose the following guidelines:
> minor chart version bump require an Emissary version bump. so 8.3.0 -> 3.3.0 etc.
> chart patch versions can be independent so 8.3.1 could still use Emissary 3.3.0.

Agreed, this is the standard I had followed in the past. Then if we had emissry 3.3.1 I would bump helm to 8.3.2 (if it was on 8.3.1)


> There is a question whether we should prepare chart RC candidates.

I think for this initial setup we should keep it simple. As we use it, we'll quickly discover what is missing and add it in. This is the approach I am taking with the subtree changes (which I have to write up in the GH issue). Just make it "bare bones" and iterate over it.


> One other question I thought of...is manually pushing of tags the appropriate mechanism. 

It works, however, I am always triple checking myself right before I push the tag. In the past, I automated the tag process based on PR releases. Once a "release PR" became approved and merged, that would have triggered the tag creation and push. We already have "release PRs" so it would extend that behavior of those.

**Comment by LanceEa** [comment]
> Not sure how I feel about this. As a user, if I am not using helm I don't really find much used to have the chart name included there and might consider it noise and/or confusing.

@ddymko Yeah, I think that is fair. Would you say then that you are in-favor of option 1 which is to allow helm releases independent but manifests should stay tied to emissary releases? 

I guess a third option, that I was just thinking about is that the release process is smooth already on Emissary with a few PR friction items and the discussion about release branches but overall it is smooth. So, does it hurt to just do a z patch release across all three even if it is just to incorporate a simple helm fix? 

The whole reason for proposing the goal of making them independent is to improve our responsiveness in providing fixes. If the normal release process is already fast (_which it is excluding smoke testing and doc updates_) then I don't think hurts to just cut a release across the board. This would accomplish our goal of being able to be responsive, would address the drift question and would have no impact to the naming convention. 

That would mean no changes on emissary side for this but instead would mean spending time on reducing the smoke testing time and also addressing our velocity problem on the Edge Stack side so that it can adopt these changes faster as well.

**Comment by haq204** [comment]
After some discussion it was decided to keep chart releases in lockstep with emissary releases to maintain operational simplicity.

**Comment by LanceEa** [comment]
> After some discussion it was decided to keep chart releases in lockstep with emissary releases to maintain operational simplicity.

Adding a little additional context.

The raw YAML manifest are tied to the container release version. Where as the Helm Chart is only partially dependent on the container release version. I say partially because CRD's are tied to the container version but exposing another field within the values.yaml is only specific to the helm chart. Therefore, we are left with two main options:

1. Keep as-is which means cutting a full release so that chart, raw manifest, and container release are in lock-step
2. Allow charts to be released independently but accept that there is the potential for Skew between the raw yamls tied to the container release and the Helm releases

Although, we have seen other projects follow the latter approach, we felt that at this time the team has other bigger ticket items that they could spend their time on and that the current process is sufficient for number of releases we do. We may revisit it in the future if it becomes a major friction point.
