### ISSUE TITLE
requests timeout after upstream pod moves from one node to another

### ISSUE THREAD

**Issue by fernbach** [emissary-ingress/emissary#4702]
**Describe the bug**
When ever a pod terminated and restart on another node, we are getting timeouts for between 30 - 120 seconds.
We've tried both the default resolver and endpoint resolver, the issue is reproduced in both cases.

We've noticed in the aconf.json file. that for some reason, it takes quite a lot of time for the endpoints to update to the relevant ip address.

**To Reproduce**
1. Send requests to a services (through emissary ingress) - deployed with more than 1 pod
2. Cordon the node
3. Kill a pod
4. The pod is up and running on another node, but traffic is still routed to the previous node.

**Expected behavior**
requests should work without any errors

**Versions (please complete the following information):**
 - Ambassador: 1.13.3, 2.3.1, 3.2.0
 - Kubernetes environment: EKS
 - Version: 1.21 / 1.22 / 1.23

**Additional context**

**Comment by fernbach** [comment]
The issue is still happening.
With mapping, the issue can now be mitigated by configuration active health checks. but it's not possible for AuthService.

**Comment by cindymullins-dw** [comment]
Thanks for reporting @fernbach.  We typically suggest:
* 	checking that fast_reconfigure is on: in newer versions (2.0+) this is on by default.  If you are serving more than 2000 routes behind Ambassador it is recommended that you set [AMBASSADOR_FAST_RECONFIGURE: “true” and AMBASSADOR_FAST_VALIDATION: “true”.](https://www.getambassador.io/docs/emissary/latest/topics/running/scaling#ambassador_fast_reconfigure-and-ambassador_legacy_mode-flags)
* 	lower [AMBASSADOR_DRAIN_TIME](https://www.getambassador.io/docs/emissary/latest/topics/running/scaling/#ambassador_drain_time) to help speed reconfiguration by reducing the time Ambassador retains old configuration
* 	avoiding using regular expressions in the host field of your mappings: there is an ambassador module option named prune_unreachable_routes that if enabled may result in significantly more efficient envoy configurations for your situation.
Sorry for the long delay in responding.  Feel free to reopen if still having issues with this.
