### ISSUE TITLE
feat(tracing): introduce OpenTelemetry driver

### ISSUE THREAD

**Issue by LanceEa** [emissary-ingress/emissary#4707]
## Summary

With Envoy now supporting OpenTelemetry, LightStep has chosen to no longer support the LightStep Tracing driver. This driver and its config has been removed in Envoy 1.24.0. This is a blocker for upgrading Emissary-ingress to Envoy 1.24.

- [OpenTelemetry Introduced](https://github.com/envoyproxy/envoy/pull/20281/commits)
- [LightStep Support Removed]()https://github.com/envoyproxy/envoy/pull/21370
- [OpenTelemetry Tracing Config](https://www.envoyproxy.io/docs/envoy/v1.24.0/api-v3/config/trace/v3/opentelemetry.proto#envoy-v3-api-msg-config-trace-v3-opentelemetryconfig)

## Plan
- [x] Introduce OpenTelemetry Driver
- [x] Deprecate LightStep with deprecation notices that it will be removed in the next minor version of Emissary-ingress
- [x] Provide upgrade documentation for moving from LightStep to OtelCollector - <https://github.com/lightstep/opentelemetry-demo>

## Other

I just want to call out the fact that we will also need to start considering and planning for the deprecation of Global Tracing as outlined here: https://github.com/emissary-ingress/emissary/issues/4709. That way it will not be a blocker like this issue is for future upgrades.

**Comment by LanceEa** [comment]
@psalaberria002 - FYI in case you hadn't seen the removal.

**Comment by psalaberria002** [comment]
> @psalaberria002 - FYI in case you hadn't seen the removal.

Yes, I was aware of the changes. The otel exporters can send data directly to the Lightstep satellites 👍
