### ISSUE TITLE
Is there a memory leak in version 3.3.1?

### ISSUE THREAD

**Issue by chalut01** [emissary-ingress/emissary#4778]
**Describe the bug**
Memory leak in version 3.3.1
![Screenshot 2566-01-04 at 13 24 26](https://user-images.githubusercontent.com/22786179/210497558-6b3f17d5-cbf7-4af5-b96b-cd61e86d29c1.png)

**Versions :**
 - emissaryingress/emissary:3.3.1

[heaps.zip](https://github.com/emissary-ingress/emissary/files/10341933/heaps.zip)

**Comment by cindymullins-dw** [comment]
@chalut01 , could you check this previous issue and see if any details are similar in your case?  From our docs (as noted in linked issue (https://github.com/emissary-ingress/emissary/issues/3414#issuecomment-896437505) we do recommend [in our docs](https://www.getambassador.io/docs/emissary/latest/topics/running/scaling#memory-limits) that _"In general you should try to keep Emissary-ingress's memory usage below 50% of the pod's limit. This may seem like a generous safety margin, but when reconfiguration occurs, Emissary-ingress requires additional memory to avoid disrupting active connections. At each reconfiguration, Emissary-ingress keeps around the old version for the duration of the configured drain time. See [AMBASSADOR_DRAIN_TIME](https://www.getambassador.io/docs/emi_ssary/latest/topics/running/scaling#ambassador_drain_time) for more details on how to tune this behavior."
