### ISSUE TITLE
Kubernetes Service sessionAffinity does not work well with emissary

### ISSUE THREAD

**Issue by imredobos** [emissary-ingress/emissary#4793]
**Describe the bug**
I have an emissary-ingress listening on port 80, it forwards the traffic to a Service with the use of KubernetesServiceResolver, the Service 's sessionAffinity is set to ClientIP, but in practice, it seems like there's no session affinity. It distributes the traffic across many pods besides the affinity config. Also when I remove the sessionAffinity config from the Service, there are cases when all of the traffic goes to one pod. So it seems like sessionAffinity config does not have effect either it is set or not. When I change my service settings to NodePort, meaning emissary-ingress is not involved in the request, sessionAffinity works well for both cases (None and ClientIP).

**To Reproduce**
The whole configuration can be found here: https://github.com/imredobos/emissary-ingress-example
The cluster is hosted on AWS EC2, with the help of Rancher.

**Expected behavior**
Traffic should be rotated between pods in case sessionAffinity: None, and sticked to a pod in case of sessionAffinity: ClientIP

**Versions (please complete the following information):**
 - Helm  chart: emissary-ingress:8.4.0
 - Kubernetes environment [EC2 but not EKS managed, Rancher:  v1.24.8+rke2r1

**Additional context**
- emissary-ingress is used with hostPort to direct the traffic into the pod

**Comment by cindymullins-dw** [comment]
Hi @imredobos , I noticed you have SessionAffinity: ClientIP, and I'm not sure if that is meant to work.  Checking [our docs](https://www.getambassador.io/docs/emissary/latest/topics/running/load-balancer#sticky-sessions--session-affinity), you can use source_ip as a boolean, but the yaml doesn't really match.

**Comment by imredobos** [comment]
hi @cindymullins-dw, I want to use Kubernetes' SessionAffinity feature, not emissary's. Also, for this example I created HTTP service, but in real world I want TCP, and L4 load balancing is not supported by emissary.
