### ISSUE TITLE
Question about 'ip allow/deny'

### ISSUE THREAD

**Issue by lewgun** [emissary-ingress/emissary#4798]
Hi all:
The doc: [ ip allow/deny]( https://www.getambassador.io/docs/edge-stack/latest/topics/running/ambassador#ip-allow-and-deny) says:
> The keyword peer specifies that the match should happen using the IP address of the other end of the network connection carrying the request: X-Forwarded-For and the PROXY protocol are both ignored. Here, our example specifies that connections originating from the Ambassador Edge Stack pod itself should always be allowed.
>
> The keyword remote specifies that the match should happen using the IP address of the HTTP client, taking into account X-Forwarded-For and the PROXY protocol if they are allowed (if they are not allowed, or not present, the peer address will be used instead). This permits matches to behave correctly when, for example, Ambassador Edge Stack is behind a layer 7 load balancer. Here, our example specifies that HTTP clients from the IP address range 99.99.0.0 - 99.99.255.255 will be allowed.
>
> You may specify as many ranges for each kind of keyword as desired.

but after I dig into the source code, I can't find the place to do the special action for `peer` & `remote`, so anybody pls do a favor for me to show where it is, thx

**Comment by cindymullins-dw** [comment]
Hi @lewgun, just to confirm, can you let us know what special action is required on the source code?   I believe you can just set those range values directly to the IP address range needed.

**Comment by lewgun** [comment]
Nothing, I just want to learn how to implement it
