### ISSUE TITLE
emissary-ingress-webhook-ca is not renewed

### ISSUE THREAD

**Issue by arturas-komponent** [emissary-ingress/emissary#4812]
**Describe the bug**
Internal CA `emissary-ingress-webhook-ca` is valid for 1y and it expired, it wasn't automatically renewed. Emissary stopped working inside the cluster, with errors that the TLS certificate expired, and emissary ingress pods couldn't start due to errors and failing readiness checks.

**To Reproduce**
Impossible to reproduce, unless you manually generate a short-lived CA and swap it in the `emissary-ingress-webhook-ca` secret

**Expected behaviour**
Internal CA is renewed and will not expire

**Versions (please complete the following information):**
 - Ambassador: emissary-ingress Helm chart 7.2.0, emissary CRD 2.1.0
 - Kubernetes environment: GKE
 - Version 1.24.7

**Additional context**
Using the latest Helm chart 8.4.0 with CRD 3.4.0 didn't automatically renew the `emissary-ingress-webhook-ca` secret and expired cert inside

A fix was to just delete the secret `emissary-ingress-webhook-ca` and restart the pod `emissary-apiext`, after it started, the secret was missing and a new secret with a valid certificate was created

**Comment by arturas-komponent** [comment]
Found this information [in the docs](https://www.getambassador.io/docs/emissary/latest/topics/install/yaml-install#install-with-yaml), probably it could be added in FAQ, or Known Issues

> There is a known issue with the `emissary-apiext` service that impacts all Emissary-ingress 2.x and 3.x users. Specifically, the TLS certificate used by apiext expires one year after creation and does not auto-renew. All users who are running Emissary-ingress/Ambassador Edge Stack 2.x or 3.x with the apiext service should proactively renew their certificate as soon as practical by running `kubectl delete --all secrets --namespace=emissary-system` to delete the existing certificate, and then restart the `emissary-apiext` deployment with `kubectl rollout restart deploy/emissary-apiext -n emissary-system`. This will create a new certificate with a one year expiration. We will issue a software patch to address this issue well before the one year expiration. Note that certificate renewal will not cause any downtime.

**Comment by SergeBakharev** [comment]
For Ambassador Edge stack it is not safe to delete all secrets in the namespace as the edge-stack secret (which contains the license key) is mounted into the edge-stack deployment. If it's not present the pod will not start.

Instead it's best to specifically delete the cert secrets then restart the edge-stack

```bash
kubectl delete -n <ambassador ns> secret ambassador-internal
kubectl delete -n <ambassador ns> secret fallback-self-signed-cert
kubectl rollout restart -n <ambassador ns> deployment edge-stack
```
