### ISSUE TITLE
When replacing Nginx Ingress with Emissary mapping, is there an app-root feature?

### ISSUE THREAD

**Issue by ericlinz** [emissary-ingress/emissary#4818]
Hi I am trying to move from nginx to emissary. Here is my nginx ingress. I defined some annotation to rewrite URLs:
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: default-my-namespace
    nginx.ingress.kubernetes.io/app-root: /index.html
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/rewrite-target: /A-sample-url/$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: my-ingress
  namespace: my-namespace
spec:
  rules:
  - host: my-host-1
    http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              number: 443
        path: /(.*)
        pathType: ImplementationSpecific

My expected behaviour is: https://ambassador.io is routed to https://my-service/index.html, and any subsequent javascripts such as https://ambassador.io/sample.js is routed to https://my-service/sample.js. To replace it with emissary mapping, I have the following:

apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: my-mapping
  namespace: my-namespace
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
  hosts:
  - my-host-1
  prefix: /.*
  prefix_regex: true
  regex_rewrite:
    pattern: '/(.*)'
    substitution: '/A-sample-url/\1'
  service: https://my-service:443

Can someone please check if my mapping definition file is correct? How can I do an app-root annotation like Nginx in Emissary? I want https://my-service to open https://my-service/index.html.

**Comment by cindymullins-dw** [comment]
Hi @ericlinz , if you're on Emissary version 2.x or later, can you check that your Listener is set up correctly?  If you installed with our QuickStart it opens up ports 443 for HTTPS and 80 for HTTP.  To rewrite paths you can follow the [examples here](https://www.getambassador.io/docs/emissary/latest/topics/using/rewrites#rewrite), and [regex here](https://www.getambassador.io/docs/emissary/latest/topics/using/prefix-regex).  One correction is that prefix: / doesn't work as a catch-all, but prefix: "/.*" with prefix_regex: true does
Also, if you're using ambassador_id pls make sure all your CRDs (Service, Mapping, Listener) are tagged with that same ambassador_id.  Lastly could you join our Slack at a8r.io/slack and we can help further there.

**Comment by cindymullins-dw** [comment]
If I understand app-root correctly, I think that can be accomplished with a [redirect.](https://www.getambassador.io/docs/emissary/latest/topics/using/redirects#examples)
