### ISSUE TITLE
 getambassador.io/v3alpha1, Kind=Module failed: Post "https://emissary-apiext.emissary-system.svc:443/webhooks/crd-convert?timeout=30s

### ISSUE THREAD

**Issue by imoisharma** [emissary-ingress/emissary#4856]
**Describe the bug**

I am trying to deploy the Emissary Ingress inside my Minikube Cluster. It keeps failing on this step

```sh
helm install emissary-ingress --namespace emissary datawire/emissary-ingress
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a local minikube cluster
2. Install Emissary Ingress via Helm: https://www.getambassador.io/docs/emissary/latest/tutorials/getting-started#1-installation

**Expected behaviour**
We should be able to deploy the emissary ingress fine without any issues.

**Versions (please complete the following information):**
 - Emissary Ingress: `3.2.0` - `3.5.0`
 - Kubernetes environment: `Minikube`
 - Version: `v1.26.0`

**Additional context**

**Comment by cindymullins-dw** [comment]
Hi @imoisharma , this apiext error is essentially a CRD conversation error.  Is this is a fresh install?  Did you have a previous lower version installed on this cluster which was deleted or is this is a new cluster entirely?  One thought is some old CRDs might still exist and are conflicting with the instance you’re spinning up.
