### ISSUE TITLE
Helm chart uses deprecated API autoscaling/v2beta2

### ISSUE THREAD

**Issue by eevdev** [emissary-ingress/emissary#4857]
**Describe the bug**
The Kubernetes API autoscaling/v2beta2 has been deprecated in k8s 1.23 and removed from 1.26, and is replaced by autoscaling/v2, which is a simple name change. See k8s deprecation guide: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126

**To Reproduce**
1. Install Helm chart on k8s >= 1.23 and see error message: `autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler`

**Expected behavior**
Supported API versions should be used on each version of k8s.

**Versions (please complete the following information):**
 - Emissary chart version 8.3.1
 - Kubernetes environment kOps
 - Version 1.24.10

**Additional context**

**Comment by haq204** [comment]
closing issue as it is resolved by https://github.com/emissary-ingress/emissary/pull/4859
