### ISSUE TITLE
How to build datawire/aes image

### ISSUE THREAD

**Issue by NeferpitouS3** [emissary-ingress/emissary#4878]
I want to rebuild docker.io/datawire/aes:1.14.2 image, but some steps are missing in builder/Dockerfile of project emissary-1.14.2 ,  
**such as the last steps are missing in Dockerfile :**
- /bin/sh -c #(nop) COPY file:880b110d55146460f003f325aef03f97e3b1d82af94bf80b82605d245ce3e126 in install-ssh
- /bin/sh -c sh install-ssh
- /bin/sh -c #(nop) COPY dir:6222e79e3c380587996705fe312ad868475e8e6213ee0a0b3db7121d656d9995 in /ambassador
- /bin/sh -c #(nop) COPY file:ac671ccd2c2bf2591ed1734a0a6962e5cc6de0334034ff4102cc4037dd0ea499 in /usr/local/bin
- /bin/sh -c ln -s /usr/local/bin/busyambassador-edge-stack /ambassador/sidecars/amb-sidecar &&         ln -s - 
- /usr/local/bin/busyambassador-edge-stack /usr/local/bin/app-sidecar &&         ln -s /usr/local/bin/busyambassador-edge-stack - /usr/local/bin/aes-plugin-runner &&         ln -s /usr/local/bin/busyambassador-edge-stack /usr/local/bin/aes-injector &&         ln -s /usr/local/bin/busyambassador-edge-stack /usr/local/bin/consul_connect_integration &&         ln -s /usr/local/bin/busyambassador-edge-stack /usr/local/bin/traffic-manager &&         ln -s /usr/local/bin/busyambassador-edge-stack /usr/local/bin/local-devportal &&     touch /ambassador/.edge_stack

**And how to compile the "busyambassador-edge-stack" file ?**

**Comment by cindymullins-dw** [comment]
Hi @NeferpitouS3 , just to confirm are you using [this image here](https://hub.docker.com/r/datawire/aes/tags?page=1&name=1.14.2)?

**Comment by NeferpitouS3** [comment]
yes, is the "busyambassador-edge-stack" file of this image compiled by the current project?

**Comment by cindymullins-dw** [comment]
Yes, apologies for the delay.  That's correct.
