### ISSUE TITLE
Purpose of emissary-ingress-agent deployment

### ISSUE THREAD

**Issue by akashsethiya** [emissary-ingress/emissary#4901]
An additional deployment is added now to the newer versions named `emissary-ingress-agent`. I couldnt find any documentation around the purpose for this. Is it only required for Edge Stack or for open source emissary-ingress also.

Can somebody please help?

**Comment by haq204** [comment]
Hi @akashsethiya 

The Agent is an optional component that reports snapshots Ambassador Cloud which it uses to populate the service catalog giving you a birds-eye-view of your cluster and its services. 

For Emissary specifically you don't really need it if you are not using Ambassador Cloud can be disabled in the Helm chart.
