### ISSUE TITLE
Which is the right way to install Filter and Filter Policy CRDs?

### ISSUE THREAD

**Issue by robsonandradev** [emissary-ingress/emissary#4940]
**Describe the bug**
Hello guys,
I have an edge-stack installation using helm chart, and I'm trying to use a filter:
```yaml
---
apiVersion: getambassador.io/v3alpha1
kind: Filter
metadata:
  name: "filter"
  namespace: "ambassador"
spec:
  External:
    auth_service: "http://kratos:80"
    proto: http
```
but when I applied this manifest I got this error:
`Error from server (NotFound): error when creating "auth-svc.yaml": the server could not find the requested resource (post filters.getambassador.io)`

**To Reproduce**
1. Install edge-stack using helm chart
2. Create a simple filter
3. apply it
4. `Error from server (NotFound): error when creating "auth-svc.yaml": the server could not find the requested resource (post filters.getambassador.io)`

**Expected behavior**
It was expected that the filter was created

**Versions (please complete the following information):**
 - Edge-stack chart: 8.1.1
 - Kubernetes environment minikube
 - minikube version: v1.26.0
 - kubectl version -o json:
```json
{
  "clientVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.0",
    "gitCommit": "ab69524f795c42094a6630298ff53f3c3ebab7f4",
    "gitTreeState": "clean",
    "buildDate": "2021-12-07T18:16:20Z",
    "goVersion": "go1.17.3",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "24",
    "gitVersion": "v1.24.1",
    "gitCommit": "3ddd0f45aa91e2f30c70734b175631bec5b5825a",
    "gitTreeState": "clean",
    "buildDate": "2022-05-24T12:18:48Z",
    "goVersion": "go1.18.2",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

**Additional context**
Looking for the Filter and Filter Policy CRDs, I only found the old version 2 or 3 years ago.
Which is the right way to install these CRDs now?

**Comment by cindymullins-dw** [comment]
Hi @robsonandradev , I think you can use the [Edge Stack QuickStart ](https://www.getambassador.io/docs/edge-stack/latest/tutorials/getting-started)to install CRDs for the latest version.  Have you tried that?

**Comment by robsonandradev** [comment]
Hi @cindymullins-dw thank you for your reply, it works here.
We already had an ambassador CRDs, however it seems to be not complete.

Thank you!
