### ISSUE TITLE
emissary-ingress TLS not working in AWS ELB NLB

### ISSUE THREAD

**Issue by robd003** [emissary-ingress/emissary#4968]
If you're using ```protocol: HTTPSPROXY``` it will always fail.

Solution: ```protocolStack: [ "PROXY", "TLS", "HTTP", "TCP" ]```

**Comment by robd003** [comment]
@cindymullins-dw It seems kind of silly to not support the largest cloud provider in the world.

Can we at least document how to use emissary-ingress when running on AWS and using a Network Loadbalancer with proxy v2 support for native HTTP and TLS?

**Comment by blacksd** [comment]
@cindymullins-dw for the records, it breaks the default VPCgen2 Load Balancer in IBM Cloud too, I just experienced it first-hand.
At the very least, this should be explicitly stated in the documentation - from that PoV, as of today `protocol` is preferred against `protocolStack`.
