### ISSUE TITLE
envoy communication is not working

### ISSUE THREAD

**Issue by rmyadarapu** [emissary-ingress/emissary#5054]
We are trying to install edge-stack 3.6 and integrate with Cognito authorization for our product. 
the communication from edge-stack to the cognito is failing and unable to reach grpc.

**Comment by mlassi** [comment]
{"user_agent.name":"-","http":{"request":{"headers":{"x_forwarded_proto":"-","content-length":"-","correlation-id":"-","accept":"-","x_forwarded_for":"-","x_envoy_decorator_operation":"-","id":"-","session-id":"-","x_b3_parentspanid":"-","x_b3_traceid":"-","content-type":"-","authority":"-","x_envoy_internal":"-","x_envoy_expected_rq_timeout_ms":"-","host":"-","x_b3_spanid":"-","x_b3_sampled":"-"},"duration_req":"-","duration":"0","body":{"bytes":"0"},"path":"-","method":"-"},"version":"HTTP/1.1","response":{"headers":{"access-control-allow-origin":"-","date":"Thu, 18 May 2023 18:35:51 GMT","server":"envoy","content-length":"11","content-type":"text/plain"},"body":{"bytes":"11"},"status_code_details":"http1.codec_error","flags":"DPE","duration_tx":"-","duration_resp":"-","status_code":"400"}},"@timestamp":"2023-05-18T18:35:51.897Z","network":{"direction":"inbound"},"client":{"remote":{"address_no_port":"10.40.169.144"},"address":"11.20.169.144:65113","sni":"mydomain.com","tls":{"cipher":"-","version":"-","session_id":"-"},"local":{"address":"11.20.170.37:8443"},"direct":{"remote":{"address":"10.40.169.144:65113"}},"certificate":{"peer":{"cert_v_start":"-","serial":"-","cert_v_end":"-","issuer":"-","uri_san":"-","certificate":"-"},"local":{"uri_san":"-","subject":"-"}}},"host":{"hostname":"edge-stack-84cdb998b4-9tmf6"},"server":{"address":"-"},"log":{"level":"info"},"envoy":{"upstream":{"transport_failure_reason":"-","cluster":"-","localaddress":"-"},"route":{"name":"-"}}}

**Comment by mlassi** [comment]
TLSContext
Name:         mydomain.com
Namespace:    ambassador
Labels:       <none>
Annotations:  <none>
API Version:  getambassador.io/v2
Kind:         TLSContext
Metadata:
  Creation Timestamp:  2023-05-15T22:11:37Z
  Generation:          4
  Managed Fields:
    API Version:  getambassador.io/v3alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
      f:spec:
        .:
        f:hosts:
        f:min_tls_version:
        f:secret:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-05-15T22:11:37Z
    API Version:  getambassador.io/v2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        f:alpn_protocols:
    Manager:         kubectl-edit
    Operation:       Update
    Time:            2023-05-16T20:27:13Z
  Resource Version:  481783395
  UID:               dee4ffb1-b381-4bdd-b282-5882f8247f2e
Spec:
  alpn_protocols:  h2[, http/1.1]
  ambassador_id:
    --apiVersion-v3alpha1-only--default
  Hosts:
    mycorp.com
  min_tls_version:  v1.2
  Secret:           ambassador-certs
Events:             <none>

**Comment by rmyadarapu** [comment]
```
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: hostkkk.zzz.com
  namespace: ambassador
spec:
  alpn_protocols: h2[, http/1.1]
  ambassador_id:
    - '--apiVersion-v3alpha1-only--default'
  hosts:
    - hostkkk.zzz.com
  min_tls_version: v1.2
  secret: ambassador-certs
```

**Comment by mlassi** [comment]
Name:         ambassador
Namespace:    ambassador
Labels:       app.kubernetes.io/component=edge-stack-ratelimit
              app.kubernetes.io/instance=edge-stack
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=edge-stack
              app.kubernetes.io/part-of=edge-stack
              helm.sh/chart=emissary-ingress-8.6.0
              product=aes
Annotations:  meta.helm.sh/release-name: edge-stack
              meta.helm.sh/release-namespace: ambassador
API Version:  getambassador.io/v2
Kind:         Module
Metadata:
  Creation Timestamp:  2023-05-12T18:47:15Z
  Generation:          4
  Managed Fields:
    API Version:  getambassador.io/v3alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:app.kubernetes.io/part-of:
          f:helm.sh/chart:
          f:product:
      f:spec:
        .:
        f:config:
    Manager:      helm
    Operation:    Update
    Time:         2023-05-12T18:47:15Z
    API Version:  getambassador.io/v2
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:config:
          f:admin_port:
          f:diagnostics:
            f:enabled:
          f:envoy_log_format:
            .:
            f:@timestamp:
            f:client:
              .:
              f:address:
              f:certificate:
                .:
                f:local:
                  .:
                  f:subject:
                  f:uri_san:
                f:peer:
                  .:
                  f:cert_v_end:
                  f:cert_v_start:
                  f:certificate:
                  f:issuer:
                  f:serial:
                  f:uri_san:
              f:direct:
                .:
                f:remote:
                  .:
                  f:address:
              f:local:
                .:
                f:address:
              f:remote:
                .:
                f:address_no_port:
              f:sni:
              f:tls:
                .:
                f:cipher:
                f:session_id:
                f:version:
            f:envoy:
              .:
              f:route:
                .:
                f:name:
              f:upstream:
                .:
                f:cluster:
                f:localaddress:
                f:transport_failure_reason:
            f:host:
              .:
              f:hostname:
            f:http:
              .:
              f:request:
                .:
                f:body:
                  .:
                  f:bytes:
                f:duration:
                f:duration_req:
                f:headers:
                  .:
                  f:accept:
                  f:authority:
                  f:content-length:
                  f:content-type:
                  f:correlation-id:
                  f:host:
                  f:id:
                  f:session-id:
                  f:x_b3_parentspanid:
                  f:x_b3_sampled:
                  f:x_b3_spanid:
                  f:x_b3_traceid:
                  f:x_envoy_decorator_operation:
                  f:x_envoy_expected_rq_timeout_ms:
                  f:x_envoy_internal:
                  f:x_forwarded_for:
                  f:x_forwarded_proto:
                f:method:
                f:path:
              f:response:
                .:
                f:body:
                  .:
                  f:bytes:
                f:duration_resp:
                f:duration_tx:
                f:flags:
                f:headers:
                  .:
                  f:access-control-allow-origin:
                  f:content-length:
                  f:content-type:
                  f:date:
                  f:server:
                f:status_code:
                f:status_code_details:
              f:version:
            f:log:
              .:
              f:level:
            f:network:
              .:
              f:direction:
            f:server:
              .:
              f:address:
            f:user_agent.name:
          f:envoy_log_type:
          f:lua_scripts:
    Manager:         kubectl-edit
    Operation:       Update
    Time:            2023-05-18T18:28:04Z
  Resource Version:  482880666
  UID:               f9405bc7-a102-4b43-b418-d1cb76816039
Spec:
  ambassador_id:
    --apiVersion-v3alpha1-only--default
  Config:
    admin_port:  8001
    Diagnostics:
      allow_non_local:  true
      Enabled:          true
    envoy_log_format:
      @timestamp:  %START_TIME%
      Client:
        Address:  %DOWNSTREAM_REMOTE_ADDRESS%
        Certificate:
          Local:
            Subject:  %DOWNSTREAM_LOCAL_SUBJECT%
            uri_san:  %DOWNSTREAM_LOCAL_URI_SAN%
          Peer:
            cert_v_end:    %DOWNSTREAM_PEER_CERT_V_END%
            cert_v_start:  %DOWNSTREAM_PEER_CERT_V_START%
            Certificate:   %DOWNSTREAM_PEER_CERT%
            Issuer:        %DOWNSTREAM_PEER_ISSUER%
            Serial:        %DOWNSTREAM_PEER_SERIAL%
            uri_san:       %DOWNSTREAM_PEER_URI_SAN%
        Direct:
          Remote:
            Address:  %DOWNSTREAM_DIRECT_REMOTE_ADDRESS%
        Local:
          Address:  %DOWNSTREAM_LOCAL_ADDRESS%
        Remote:
          address_no_port:  %DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%
        Sni:                %REQUESTED_SERVER_NAME%
        Tls:
          Cipher:      %DOWNSTREAM_TLS_CIPHER%
          session_id:  %DOWNSTREAM_TLS_SESSION_ID%
          Version:     %DOWNSTREAM_TLS_VERSION%
      Envoy:
        Route:
          Name:  %ROUTE_NAME%
        Upstream:
          Cluster:                   %UPSTREAM_CLUSTER%
          Localaddress:              %UPSTREAM_LOCAL_ADDRESS%
          transport_failure_reason:  %UPSTREAM_TRANSPORT_FAILURE_REASON%
      Host:
        Hostname:  %HOSTNAME%
      Http:
        Request:
          Body:
            Bytes:       %BYTES_RECEIVED%
          Duration:      %DURATION%
          duration_req:  %REQUEST_DURATION%
          Headers:
            Accept:                          %REQ(ACCEPT)%
            Authority:                       %REQ(:AUTHORITY)%
            Content - Length:                %REQ(CONTENT-LENGTH)%
            Content - Type:                  %REQ(CONTENT-TYPE)%
            Correlation - Id:                %REQ(CORRELATION-ID)%
            Host:                            %REQ(HOST)%
            Id:                              %REQ(X-REQUEST-ID)%
            Session - Id:                    %REQ(SESSION-ID)%
            x_b3_parentspanid:               %REQ(X-B3-PARENTSPANID)%
            x_b3_sampled:                    %REQ(X-B3-SAMPLED)%
            x_b3_spanid:                     %REQ(X-B3-SPANID)%
            x_b3_traceid:                    %REQ(X-B3-TRACEID)%
            x_envoy_decorator_operation:     %REQ(X-ENVOY-DECORATOR-OPERATION)%
            x_envoy_expected_rq_timeout_ms:  %REQ(X-ENVOY-EXPECTED-RQ-TIMEOUT-MS)%
            x_envoy_internal:                %REQ(X-ENVOY-INTERNAL)%
            x_forwarded_for:                 %REQ(X-FORWARDED-FOR)%
            x_forwarded_proto:               %REQ(X-FORWARDED-PROTO)%
          Method:                            %REQ(:METHOD)%
          Path:                              %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
        Response:
          Body:
            Bytes:        %BYTES_SENT%
          duration_resp:  %RESPONSE_DURATION%
          duration_tx:    %RESPONSE_TX_DURATION%
          Flags:          %RESPONSE_FLAGS%
          Headers:
            Access - Control - Allow - Origin:  %RESP(ACCESS-CONTROL-ALLOW-ORIGIN)%
            Content - Length:                   %RESP(CONTENT-LENGTH)%
            Content - Type:                     %RESP(CONTENT-TYPE)%
            Date:                               %RESP(DATE)%
            Server:                             %RESP(SERVER)%
          status_code:                          %RESPONSE_CODE%
          status_code_details:                  %RESPONSE_CODE_DETAILS%
        Version:                                %PROTOCOL%
      Log:
        Level:  info
      Network:
        Direction:  inbound
      Server:
        Address:        %UPSTREAM_HOST%
      user_agent.name:  %REQ(USER-AGENT)%
    envoy_log_type:     json
    lua_scripts:        function envoy_on_request(request_handle)
  local authority = request_handle:headers():get(":authority")
  if(string.find(authority, ":") ~= nil)
  then
    local authority_index = string.find(authority, ":")
    local stripped_authority = string.sub(authority, 1, authority_index - 1)
    request_handle:headers():replace(":authority", stripped_authority)
  end
end

**Comment by mlassi** [comment]
previous version of module:
apiVersion: getambassador.io/v2
kind: Module
metadata:
  annotations:
    meta.helm.sh/release-name: edge-stack
    meta.helm.sh/release-namespace: ambassador
  creationTimestamp: "2023-05-12T18:47:15Z"
  generation: 4
  labels:
    app.kubernetes.io/component: edge-stack-ratelimit
    app.kubernetes.io/instance: edge-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: edge-stack
    app.kubernetes.io/part-of: edge-stack
    helm.sh/chart: emissary-ingress-8.6.0
    product: aes
  name: ambassador
  namespace: ambassador
  resourceVersion: "482880666"
  uid: e9405bc7-a102-4b43-b418-d1cb76816039
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
  config:
    diagnostics:
      allow_non_local: true
      enabled: true

**Comment by rob-r** [comment]
`apiVersion: getambassador.io/v2
kind: Module
metadata:
  annotations:
    meta.helm.sh/release-name: edge-stack
    meta.helm.sh/release-namespace: ambassador
  creationTimestamp: "2023-05-12T18:47:15Z"
  generation: 4
  labels:
    app.kubernetes.io/component: edge-stack-ratelimit
    app.kubernetes.io/instance: edge-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: edge-stack
    app.kubernetes.io/part-of: edge-stack
    helm.sh/chart: emissary-ingress-8.6.0
    product: aes
  name: ambassador
  namespace: ambassador
  resourceVersion: "482880666"
  uid: e9405bc7-a102-4b43-b418-d1cb76816039
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
  config:
    diagnostics:
      allow_non_local: true
      enabled: true`

**Comment by rob-r** [comment]
apiVersion: getambassador.io/v2
kind: Module
metadata:
  annotations:
    meta.helm.sh/release-name: edge-stack
    meta.helm.sh/release-namespace: ambassador
  creationTimestamp: '2023-05-12T18:47:15Z'
  generation: 4
  labels:
    app.kubernetes.io/component: edge-stack-ratelimit
    app.kubernetes.io/instance: edge-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: edge-stack
    app.kubernetes.io/part-of: edge-stack
    helm.sh/chart: emissary-ingress-8.6.0
    product: aes
  name: ambassador
  namespace: ambassador
spec:
  ambassador_id:
    - '--apiVersion-v3alpha1-only--default'
  config:
    admin_port: 8001
    diagnostics:
      allow_non_local: true
      enabled: true

**Comment by rob-r** [comment]
```apiVersion: getambassador.io/v2
kind: Module
metadata:
  annotations:
    meta.helm.sh/release-name: edge-stack
    meta.helm.sh/release-namespace: ambassador
  creationTimestamp: '2023-05-12T18:47:15Z'
  generation: 4
  labels:
    app.kubernetes.io/component: edge-stack-ratelimit
    app.kubernetes.io/instance: edge-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: edge-stack
    app.kubernetes.io/part-of: edge-stack
    helm.sh/chart: emissary-ingress-8.6.0
    product: aes
  name: ambassador
  namespace: ambassador
spec:
  ambassador_id:
    - '--apiVersion-v3alpha1-only--default'
  config:
    admin_port: 8001
    diagnostics:
      allow_non_local: true
      enabled: true```

**Comment by cindymullins-dw** [comment]
Thanks for attending our help session.  As noted we are more strict about mapping gRPC calls than before.  gRPC clients may add the ports to the host header, as noted [here (https://www.getambassador.io/docs/emissary/latest/howtos/grpc#working-with-host-headers-that-include-the-port).

There is a Lua script noted there you can use in the Module to make headers align.  Also suggest using Linkerd with dashboard inspection which lets you inspect the request as it travels between ambassador and the Cognito device and any services acting as filters, to investigate further.

**Comment by cindymullins-dw** [comment]
Hi @rmyadarapu , did these suggestions help at all?  Would you like to meet again in another help session to try them out?

**Comment by cindymullins-dw** [comment]
Closing for lack of response.
