### ISSUE TITLE
Build command failing

### ISSUE THREAD

**Issue by rahulyadav170923** [emissary-ingress/emissary#5076]
**Describe the bug**
I was trying to build the emissary docker image from tag v.3.4.0. the build was failing with the below error message.
**To Reproduce**
1. checkout into tag v3.4.0
2. run `make images`
`build-aux/prelude.mk:105: The 'lazyonce' function is known to trigger a memory corruption bug in GNU Make 3.81
build-aux/prelude.mk:105: Disabling the 'lazyonce' function; upgrade your copy of GNU Make for faster builds
[make] VERSION=v3.4.2-0.20230207223145-7a152baba498-dirty.1685430727
[make] CHART_VERSION=v8.4.2-0.20230207223145-7a152baba498-dirty.1685430727
tools/bin/crane pull docker.io/frolvlad/alpine-glibc:alpine-3.15_glibc-2.34 docker/.base.img.tar.stamp || test -e docker/.base.img.tar.stamp
tools/bin/copy-ifchanged docker/.base.img.tar.stamp docker/base.img.tar
printf '%s\n' $(cat docker/base.docker) emissary.local/base | tools/bin/write-dockertagfile docker/base.docker.tag.local
==> Pulling base Envoy image
envoy-0.5a4aed880cb9b76df21448e75d42fe95a77c3893.opt: Pulling from emissaryingress/base-envoy
1b7ca6aea1dd: Already exists
eff7fe6cd73a: Already exists
24f565845f78: Pull complete
d1979f30103a: Pull complete
Digest: sha256:6045ad01169e02d44899d4b3a85fceb45290443f2d6a3dfb24b7177ce74b2cf4
Status: Downloaded newer image for emissaryingress/base-envoy:envoy-0.5a4aed880cb9b76df21448e75d42fe95a77c3893.opt
docker.io/emissaryingress/base-envoy:envoy-0.5a4aed880cb9b76df21448e75d42fe95a77c3893.opt
     (docker pull took 11.0 seconds)
tools/bin/copy-ifchanged docker/.base-envoy.docker.stamp docker/base-envoy.docker
printf '%s\n' $(cat docker/base-envoy.docker) emissary.local/base-envoy | tools/bin/write-dockertagfile docker/base-envoy.docker.tag.local
Untagged: emissaryingress/base-envoy:envoy-0.dcc3afef1680c1c4f932c73e0c9bca8b0b5db484.opt
Untagged: emissaryingress/base-envoy@sha256:97afae6a845d88b55d16225c1fc73cdd2bfc9a1d17de2326a8de6dd629bdf489
Deleted: sha256:fa52022da238eabf76c57be167eaf3f1d5d5bbc28c7d04d0037c84051edc5d90
Deleted: sha256:5b44c29c4cf36ae8a56cfa3590c7ec1ef8821aa535ff82668645cb9e7468447b
Deleted: sha256:96b27568171579b543245a8b09c7cee1651191144d0fb28a0954c1a50905766a
set -o pipefail; tools/bin/py-list-deps --no-include-dev python/ | tools/bin/write-ifchanged python/requirements.in
docker/base-python.docker.gen >docker/.base-python.docker.stamp
 => [base-python.docker.gen] Checking if docker.io/emissaryingress/base-python:20230528x7-5eec68e7b32c4652 exists locally... no
 => [base-python.docker.gen] Checking if docker.io/emissaryingress/base-python:20230528x7-5eec68e7b32c4652 can be pulled... no
 => [base-python.docker.gen] Building base-python:20230528x7-5eec68e7b32c4652 locally...
[+] Building 84.7s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                             0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                                                                                  0.0s
 => [internal] load metadata for docker.io/frolvlad/alpine-glibc:alpine-3.15_glibc-2.34                                                                                                                          2.3s
 => [1/8] FROM docker.io/frolvlad/alpine-glibc:alpine-3.15_glibc-2.34@sha256:a3f8eccb0bb259007f6f84e35e7faac276414c255f12891976e5d2da2141526a                                                                    0.0s
 => CACHED [2/8] WORKDIR /buildroot                                                                                                                                                                              0.0s
 => CACHED [3/8] RUN apk --no-cache add   bash   gcc   make   musl-dev   curl   cython   docker-cli   git   iptables   jq   libcap   libcap-dev   libffi-dev   ncurses   openssl-dev   py3-pip=~20.3   python3=  0.0s
 => CACHED [4/8] RUN pip3 install pip-tools==6.3.1                                                                                                                                                               0.0s
 => CACHED [5/8] RUN curl --fail -L https://dl.google.com/go/go1.19.4.linux-amd64.tar.gz | tar -C /usr/local -xzf -                                                                                              0.0s
 => CACHED [6/8] RUN curl --fail -L https://storage.googleapis.com/kubernetes-release/release/v1.23.3/bin/linux/amd64/kubectl -o /usr/bin/kubectl &&   chmod a+x /usr/bin/kubectl                                0.0s
 => CACHED [7/8] RUN mkdir /tmp/pyyaml &&   cd /tmp/pyyaml &&   curl -o pyyaml-5.4.1.1.tar.gz -L https://github.com/yaml/pyyaml/archive/refs/tags/5.4.1.1.tar.gz &&   tar xzf pyyaml-5.4.1.1.tar.gz &&   cd pyy  0.0s
 => ERROR [8/8] RUN pip3 install orjson==3.6.6                                                                                                                                                                  82.3s
------
 > [8/8] RUN pip3 install orjson==3.6.6:
#11 8.002 Collecting orjson==3.6.6
#11 8.134   Downloading orjson-3.6.6.tar.gz (550 kB)
#11 8.827   Installing build dependencies: started
#11 80.27   Installing build dependencies: still running...
#11 81.22   Installing build dependencies: finished with status 'error'
#11 81.24   ERROR: Command errored out with exit status 1:
#11 81.24    command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-843rt4c3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.12.6,<0.13'
#11 81.24        cwd: None
#11 81.24   Complete output (84 lines):
#11 81.24   Collecting maturin<0.13,>=0.12.6
#11 81.24     Downloading maturin-0.12.20.tar.gz (156 kB)
#11 81.24     Installing build dependencies: started
#11 81.24     Installing build dependencies: finished with status 'done'
#11 81.24     Getting requirements to build wheel: started
#11 81.24     Getting requirements to build wheel: finished with status 'done'
#11 81.24       Preparing wheel metadata: started
#11 81.24       Preparing wheel metadata: finished with status 'done'
#11 81.24   Collecting tomli>=1.1.0
#11 81.24     Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
#11 81.24   Building wheels for collected packages: maturin
#11 81.24     Building wheel for maturin (PEP 517): started
#11 81.24     Building wheel for maturin (PEP 517): finished with status 'error'
#11 81.24     ERROR: Command errored out with exit status 1:
#11 81.24      command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp229lxgjj
#11 81.24          cwd: /tmp/pip-install-ohe3v450/maturin_8d5bd86c91ab4095aa00ee96e0151f70
#11 81.24     Complete output (63 lines):
#11 81.24     running bdist_wheel
#11 81.24     running build
#11 81.24     running build_py
#11 81.24     creating build
#11 81.24     creating build/lib.linux-x86_64-3.9
#11 81.24     creating build/lib.linux-x86_64-3.9/maturin
#11 81.24     copying maturin/import_hook.py -> build/lib.linux-x86_64-3.9/maturin
#11 81.24     copying maturin/__init__.py -> build/lib.linux-x86_64-3.9/maturin
#11 81.24     running build_ext
#11 81.24     running build_rust
#11 81.24         Updating crates.io index
#11 81.24     Traceback (most recent call last):
#11 81.24       File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
#11 81.24         main()
#11 81.24       File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
#11 81.24         json_out['return_val'] = hook(**hook_input['kwargs'])
#11 81.24       File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
#11 81.24         return _build_backend().build_wheel(wheel_directory, config_settings,
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 216, in build_wheel
#11 81.24         return self._build_with_temp_dir(['bdist_wheel'], '.whl',
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
#11 81.24         self.run_setup()
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
#11 81.24         exec(compile(code, __file__, 'exec'), locals())
#11 81.24       File "setup.py", line 57, in <module>
#11 81.24         setup(
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
#11 81.24         return distutils.core.setup(**attrs)
#11 81.24       File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
#11 81.24         dist.run_commands()
#11 81.24       File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
#11 81.24         self.run_command(cmd)
#11 81.24       File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
#11 81.24         cmd_obj.run()
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
#11 81.24         self.run_command('build')
#11 81.24       File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
#11 81.24         self.distribution.run_command(command)
#11 81.24       File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
#11 81.24         cmd_obj.run()
#11 81.24       File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
#11 81.24         self.run_command(cmd_name)
#11 81.24       File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
#11 81.24         self.distribution.run_command(command)
#11 81.24       File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
#11 81.24         cmd_obj.run()
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools_rust/setuptools_ext.py", line 132, in run
#11 81.24         build_rust.run()
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools_rust/command.py", line 101, in run
#11 81.24         self.run_for_extension(ext)
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 112, in run_for_extension
#11 81.24         dylib_paths = self.build_extension(ext, self.target)
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 143, in build_extension
#11 81.24         target_dir = _base_cargo_target_dir(ext)
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 690, in _base_cargo_target_dir
#11 81.24         target_directory = ext._metadata()["target_directory"]
#11 81.24       File "/tmp/pip-build-env-pe8bhr_5/overlay/lib/python3.9/site-packages/setuptools_rust/extension.py", line 225, in _metadata
#11 81.24         self._cargo_metadata = json.loads(subprocess.check_output(metadata_command))
#11 81.24       File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
#11 81.24         return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#11 81.24       File "/usr/lib/python3.9/subprocess.py", line 528, in run
#11 81.24         raise CalledProcessError(retcode, process.args,
#11 81.24     subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' died with <Signals.SIGKILL: 9>.
#11 81.24     ----------------------------------------
#11 81.24     ERROR: Failed building wheel for maturin
#11 81.24   Failed to build maturin
#11 81.24   ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
#11 81.24   ----------------------------------------
#11 81.27 WARNING: Discarding https://files.pythonhosted.org/packages/99/6c/cb0dcbc2500c004764cfadb63a51701c328f45f8689ffecbc8906df0f0de/orjson-3.6.6.tar.gz#sha256=55dd988400fa7fbe0e31407c683f5aaab013b5bd967167b8fe058186773c4d6c (from https://pypi.org/simple/orjson/) (requires-python:>=3.7). Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-843rt4c3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.12.6,<0.13' Check the logs for full command output.
#11 81.29 ERROR: Could not find a version that satisfies the requirement orjson==3.6.6
#11 81.30 ERROR: No matching distribution found for orjson==3.6.6
------
executor failed running [/bin/sh -c pip3 install orjson==3.6.6]: exit code: 1
make: *** [docker/.base-python.docker.stamp] Error 1
make: *** Deleting file `docker/.base-python.docker.stamp'`

**Expected behavior**
I built the current master present and the build was passing successfully.

**Versions (please complete the following information):**
 - Ambassador: 3.4.0
 - docker 

`Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true
Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`

**Additional context**
Im trying to build the emissary image from source since im trying to implement slow start in ambassador which is needed at our organisation . i was experimenting to see if it works and then to implement it according to community guidelines. Any help would be appreciated. I understand the error but im unsure why it's failing for a released version

**Comment by tenshinhigashi** [comment]
Hello, thanks for reaching out regarding this issue. 

I ran a few quick tests locally and was unable to recreate the same errors that you are running into. Out of curiosity, what version of Python are you running?

**Comment by rahulyadav170923** [comment]
i have multiple python installations. "python" refers to 2.7 version. but from what i could see , the setup is dockerised right , python versions are fixed in the images ?

**Comment by cindymullins-dw** [comment]
Hi @rahulyadav170923 , it is dockerized however its not uncommon that having multiple python versions can cause issues, or that python and pip are out of sync.  Suggest updating pip with this command: python -m pip install --upgrade pip

**Comment by cindymullins-dw** [comment]
Closing as we don't believe this is an issue with Emissary but rather with the install environment.  Pls let us know if any further developments.
