### ISSUE TITLE
HTTP 500 Could not parse id_token jwt

### ISSUE THREAD

**Issue by sipatha** [emissary-ingress/emissary#5102]
**Issue**
We recently started getting this error on ambassador edge stack pod;

time="2023-06-12 12:55:58.9663" level=error msg="HTTP 500 Could not parse id_token jwt `eyJ0eXAiOiJKV1QiLCJraWQiOiJuYnRBc1duR3VVZURUdlM1YTlU-long-jwt-token`\ngithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/resourceserver.(*OAuth2ResourceServer).Filter\n\tgithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/resourceserver/resourceserver.go:141\ngithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/client.HandleAuthenticatedProxyRequest\n\tgithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/client/common.go:116\ngithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/client/authorizationcode.(*SessionInfo).handleAuthenticatedProxyRequest\n\tgithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/client/authorizationcode/session.go:47\ngithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/client/authorizationcode.(*OAuth2Client).filter\n\tgithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/client/authorizationcode/client.go:711\ngithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/client/authorizationcode.(*OAuth2Client).Filter\n\tgithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/client/authorizationcode/client.go:98\ngithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler.(*OAuth2Filter).Filter\n\tgithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/oauth2handler/oauth2handler.go:167\ngithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler.(*FilterMux).runFilterRef\n\tgithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/handler.go:349\ngithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler.(*FilterMux).runFilterRefs\n\tgithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/handler.go:290\ngithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler.(*FilterMux).Filter\n\tgithub.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/handler.go:154\ngithub.com/datawire/apro/v3/lib/filterapi.authorizationService.Check\n\tgithub.com/datawire/apro/v3/lib/filterapi/filterapi.go:30\ngithub.com/emissary-ingress/emissary/v3/pkg/api/envoy/service/auth/v3._Authorization_Check_Handler\n\tgithub.com/emissary-ingress/emissary/v3@v3.3.0-rc.0/pkg/api/envoy/service/auth/v3/external_auth.pb.go:692\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\tgoogle.golang.org/grpc@v1.44.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\tgoogle.golang.org/grpc@v1.44.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\tgoogle.golang.org/grpc@v1.44.0/server.go:921\nruntime.goexit\n\truntime/asm_amd64.s:1594" func=github.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/middleware.errorResponse file="github.com/datawire/apro/v3/cmd/amb-sidecar/filters/handler/middleware/errors.go:82" CMD=amb-sidecar FILTER=our-namespace-filter.our-namespace PID=41 REQUEST_ID=16314671444900794410 THREAD="/http/conn=4"

This error is intermittent, i.e. sometimes it works sometimes not.

**Stack**
Azure Kubernetes Service: 1.24.6
datawire/aes: 3.3.0
emissaryingress/emissary: 3.1.0
redis: 5.0.1

**Comment by sipatha** [comment]
Thanks, closing this as not related to ambassador/emissary.

**Comment by sipatha** [comment]
Some more context:
Our 3rd party OAuth provider was not returning the sig key when ambassador called ‘jwk_uri’ to validate the token.

**Comment by cindymullins-dw** [comment]
Thanks for the discover - much appreciated!
