### ISSUE TITLE
failed to isolate traffic between two environments in same cluster-Failed to watch *unstructured.Unstructured: can't watch configmaps.v1.: forbidden

### ISSUE THREAD

**Issue by MOUM02** [emissary-ingress/emissary#5122]
**Please describe your use case / problem.**
We have migrated our ambassador to emissary ingress 3.5.1. The installation and upgrade is successful.
We are facing an issue in emissary ingress to handle traffic for two different namespaces installed in same cluster?
Our Dev and TEST environment is deployed in same k8s cluster. We have also created two different ambassador id via emissaryyns.yml file and associated this ambassador id with the resoureces related to this i.e- Host,Mapping. But still we are getting 
below error:
E0620 13:18:13.187653      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch configmaps.v1.: forbidden
 E0620 13:18:14.709696      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [tcpmappings.v3alpha1.getambassador.io](http://tcpmappings.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:16.415064      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [kubernetesendpointresolvers.v3alpha1.getambassador.io](http://kubernetesendpointresolvers.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:17.183580      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [devportals.v3alpha1.getambassador.io](http://devportals.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:17.371023      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch endpoints.v1.: forbidden
 E0620 13:18:22.402303      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [ratelimitservices.v3alpha1.getambassador.io](http://ratelimitservices.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:25.015539      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [modules.v3alpha1.getambassador.io](http://modules.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:25.338950      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [mappings.v3alpha1.getambassador.io](http://mappings.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:28.107542      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [ingresses.v1.networking.k8s.io](http://ingresses.v1.networking.k8s.io/): forbidden
 E0620 13:18:31.418093      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [kubernetesserviceresolvers.v3alpha1.getambassador.io](http://kubernetesserviceresolvers.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:34.725394      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [authservices.v3alpha1.getambassador.io](http://authservices.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:35.489461      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [ingressclasses.v1.networking.k8s.io](http://ingressclasses.v1.networking.k8s.io/): forbidden
 E0620 13:18:40.297993      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [logservices.v3alpha1.getambassador.io](http://logservices.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:41.353277      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [consulresolvers.v3alpha1.getambassador.io](http://consulresolvers.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:43.445850      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [tlscontexts.v3alpha1.getambassador.io](http://tlscontexts.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:43.791595      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch services.v1.: forbidden
 E0620 13:18:46.688648      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [listeners.v3alpha1.getambassador.io](http://listeners.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:48.875253      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [tcpmappings.v3alpha1.getambassador.io](http://tcpmappings.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:51.229065      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch [hosts.v3alpha1.getambassador.io](http://hosts.v3alpha1.getambassador.io/): forbidden
 E0620 13:18:52.702868      1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: can't watch endpoints.v1.: forbidden
has context menuComposeParagraph

**Describe the solution you'd like**
We want to run two different emissary for our DEV and TEST environment to serve the traffic in same cluster.

**Describe alternatives you've considered**
Please provide the steps

**Additional context**
not required

**Comment by MOUM02** [comment]
Team,
any update on this?

**Comment by cindymullins-dw** [comment]
@MOUM02 , can you check your annotations and stored version to make sure there's no v1 resources there, as in [this issue](https://github.com/emissary-ingress/emissary/issues/4240)?  Testing with just one deployment in the cluster does it work without these errors?

**Comment by MOUM02** [comment]
Its working with one deployment. Whenever we deployed same service in test with providing the ambassador-id previous one got failed new one works fine

**Comment by MOUM02** [comment]
any update team

**Comment by cindymullins-dw** [comment]
I see that in a previous issue the problem was with RoleBinding. In that case the ClusterRole was defined using an aggregator, and the name of the Role referenced in the binding didn't contain the actual RBAC rules. Fixing this binding to reference the -watch Role made it work.  Can you check your permissions for this cluster?  I think you can do something like `kubectl cluster-info dump | grep authorization-mode`

**Comment by cindymullins-dw** [comment]
Hi @MOUM02 , are you still having issues with this?  We do have a weekly live help session for Emissary on Thursdays at 2:30pm ET.  Please let me know if you'd like to join sometime.
