### ISSUE TITLE
emissary-ingress with istio - sidecar containers cannot communicate with services in the istio service mesh with mtls mode: STRICT

### ISSUE THREAD

**Issue by fstreet920** [emissary-ingress/emissary#5130]
I've followed the Istio Integration instructions and enabled strict mtls using the TLSContext, and Global PeerAuthentication.  Mapped services and able to access in the browser and if I remove the tls requirement from the spec of the mapping then I can't access the services and if I add back the tls entry to the mappings I can access the services.  All good so far.  One note I have issues with some pods init containers in the namespace so istio injection is being done by pod labels only for the pods without init container issues. Emissary-ingress pod, opa-bundle-service pod, and busybox pod have istio-injection enabled.

The problem: there is an opa sidecar on the emissiary-ingress pod that needs to download a file from a service, opa-bundle-service, and it fails with 'connection reset by peer' when the Global PeerAuthentication is present.

`{"level":"error","msg":"Bundle load failed: request failed: Get \"http://opa-bundle-service:80/api/bundle/bundle.tar.gz\": read tcp 10.42.0.61:46530-\u003e10.43.22.163:80: read: connection reset by peer","name":"authz","plugin":"bundle","time":"2023-06-26T16:31:54Z"}`

If I remove the Global PeerAuthentication or change the PeerAuthentication mtls mode to PERMISSIVE then the opa sidecar can download the file from the opa-bundle-service.

Note: if I exec onto the busybox pod in the istio-mesh I can download the file from the opa-bundle-service.

Work-around:
Added pod annotation to emissary-ingress pod -
[traffic.sidecar.istio.io/includeOutboundPorts](http://traffic.sidecar.istio.io/includeOutboundPorts)
for the port of our opa-bundle-service

Added an istio sidecar resource to restrict egress from emissary-ingress to the default namespace
https://istio.io/latest/docs/reference/config/networking/sidecar/

Added an AuthorizationPolicy so that only the emissary-ingress service can do a GET on the opa-bundle service.

**Comment by cindymullins-dw** [comment]
Thanks, @fstreet920 for opening this issue.  Our [docs](https://www.getambassador.io/docs/edgre-stack/latest/howtos/istio#enable-strict-mtls) note that Istio defaults to permissive mTLS (but there's an option to apply a PeerAuthentication resource in each namespace to operate in strict mode).  Appreciate the workaround.  I'm wondering if permissive is the expected behavior here.
