### ISSUE TITLE
502 gateway response when configured with reverse-proxy

### ISSUE THREAD

**Issue by Anthony-A-K** [emissary-ingress/emissary#5149]
Here is the configuration files used.

---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener
spec:
  port: 8080
  protocol: HTTP 
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL 
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: https-listener
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL  
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: stage-host
spec:
  hostname: "*.dummy-domain.com"
  tlsSecret:
    name: tls-cert
  requestPolicy:         
    insecure:            
      action: Redirect    
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: stage-tls-apln
spec:
  secret: tls-cert
  hosts: ['*']
  alpn_protocols: h2[, http/1.1]
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: backend-ambassador-mapping
  namespace: default
spec:
  docs:
    path: /.ambassador-internal/openapi-docs
  host: dev.dummy-domain.com
  prefix: /backend/
  service: quote

**Comment by cindymullins-dw** [comment]
I'm not sure if your Host is referencing your TLSContext correctly.  Have you specified the TLSContext name?

_Next, link it to the Host via the tlsContext field as shown:_

yamlcopied
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: example-host
spec:
  hostname: host.example.com
  tlsSecret:
    name: min-secret
  tlsContext:
    name: min-tls-context

**Comment by cindymullins-dw** [comment]
Hi @Anthony-A-K , the tweak to httpProxy with NLB, if you find that you need that, is to use `protocolStack: [ "PROXY", "TLS", "HTTP", "TCP" ]`.  You can't use `protocol: HTTPSPROXY` with AWS.

**Comment by cindymullins-dw** [comment]
Still having issues with this - any luck with the above?
