### ISSUE TITLE
Request without certificates goes through even when mTLS is configured

### ISSUE THREAD

**Issue by aakashjhawar** [emissary-ingress/emissary#5379]
**Describe the bug**
I have configured mTLS for one of the hosts. But when I make a request without passing the certificates, it still allows it to go to the backend service.

Current setup: The ambassador is deployed behind the GKE Ingress. When the request first hits GKE Ingress, it forwards it to the Ambassador. I've also set up TLSContext to check client certificates. But still, it allows the request to pass through without validating client certificates.

**To Reproduce**
1. Deploy GKE Ingress
2. Deploy Emissary Ingress / Ambassador
3. Configure Host, TLSContext and Mapping
4. Send the request

**Expected behavior**
It should only allow the requests that contain correct client certificates and reject all other requests.

**Versions (please complete the following information):**
 - Ambassador: 1.14
 - Kubernetes environment: Google Kubernetes Engine
 - Version: 1.23

**Comment by cindymullins-dw** [comment]
Hi @aakashjhawar , can you try setting strict mTLS as noted [here](https://www.getambassador.io/docs/emissary/latest/howtos/istio#enable-strict-mtls)?  Also I noticed you're on 1.14 of Emissary.  We do have a [migration guide here](https://www.getambassador.io/docs/emissary/latest/topics/install/migration-matrix) to help you and we'd encourage you to upgrade to troubleshoot this further.  Please note that you should upgrade your Ambassador version (and see notes on [what's changed in 2.x](https://www.getambassador.io/docs/emissary/latest/about/changes-2.x) as well as [3.x](https://www.getambassador.io/docs/emissary/latest/about/changes-3.y)) BEFORE upgrading Kubernetes versions.  In this case we'd suggest upgrading to 2.5 (side-by-side install) and then once that's working you can go straight to the latest 3.x version.
