### ISSUE TITLE
Opentelemetry driver is not able to send traces to collector and no error logs are being produced on ambassador to debug the issue 

### ISSUE THREAD

**Issue by yashrastogi21** [emissary-ingress/emissary#5422]
**Describe the bug**
We are using TracingService for enabling tracing on Ambassador version 3.7 and using opentelemtry driver to send the spans to collector but we are not getting the traces on collector . Also there are no logs being produced on ambassador saying the failure of this service .

We tried to test with both grpc and http endpoints for collector but it didnt work out . 
Tried to change the config as well with and without propagation modes but still didnt get the desired result .

**To Reproduce**
1. Apply this config to your ambassador 

`apiVersion: getambassador.io/v3alpha1
kind:  TracingService
metadata:
  name:  tracing
  namespace: <infrastructure>
spec:
  service: "<collector_url>"
  driver: opentelemetry
  config:
    propagation_modes: ["TRACE_CONTEXT"]
  sampling:
    overall: 100`
    
    
2. Generate load for the services
3. Test if you receiving the traces on collector correctly .

**Expected behavior**
We should be able to recieve the traces on collector after applying this config file .

**Versions (please complete the following information):**
 - Ambassador: 3.7

**Additional context**

**Comment by cindymullins-dw** [comment]
Sample yaml provided by @psalaberria002, code contributor
apiVersion: [getambassador.io/v2](http://getambassador.io/v2)
kind: TracingService
metadata:
  name: tracing
  namespace: x
spec:
  config:
    service_name: emissary
  driver: opentelemetry
  service: lightstep-microsatellite-headless.internal-services:8011
  v3CustomTags:
  - environment:
      name: K8S_NODE_NAME
    tag: k8s.node.name
  - environment:
      name: K8S_POD_NAME
    tag: k8s.pod.name
  - environment:
      name: K8S_POD_NAMESPACE
    tag: k8s.namespace.name
  - environment:
      name: TRACING_SERVICE_VERSION
    tag: service.version
  v3StatsName: tracingservice

**Comment by cindymullins-dw** [comment]
Hope this config is working for you.  Feel free to reopen if issue is not resolved.
